package commands

import (
	"errors"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"

	"github.com/semanticash/cli/internal/service/handoff"
)

// stubExecutor records the spec it was called with instead of
// actually exec'ing a binary, so command-level tests can drive
// the spawn path without spawning anything.
type stubExecutor struct {
	called   bool
	spec     *handoff.LaunchSpec
	workdir  string
	returnFn func() error
}

func (s *stubExecutor) execute(workdir string, spec *handoff.LaunchSpec) error {
	s.called = true
	s.spec = spec
	s.workdir = workdir
	if s.returnFn != nil {
		return s.returnFn()
	}
	return nil
}

// withStubExecutor swaps the package-level executor for a test
// stub and restores it on cleanup.
func withStubExecutor(t *testing.T) *stubExecutor {
	t.Helper()
	stub := &stubExecutor{}
	orig := continueExecutor
	continueExecutor = stub.execute
	t.Cleanup(func() { continueExecutor = orig })
	return stub
}

// withClaudeOnPath swaps the launcher's lookPath seam so the
// command-level tests run deterministically regardless of whether
// `claude` is actually installed on the test machine.
func withClaudeOnPath(t *testing.T, available bool) {
	t.Helper()
	orig := handoff.LookPathForTest()
	handoff.SetLookPathForTest(func(name string) (string, error) {
		if available && name == "claude" {
			return "/fake/claude", nil
		}
		return "", exec.ErrNotFound
	})
	t.Cleanup(func() { handoff.SetLookPathForTest(orig) })
}

// initRepoWithBundle creates a temp git repo and writes a fake
// handoff.md bundle that names the given provider in the
// "Original session" line.
func initRepoWithBundle(t *testing.T, provider string) string {
	t.Helper()
	dir := t.TempDir()
	if resolved, err := filepath.EvalSymlinks(dir); err == nil {
		dir = resolved
	}
	cmd := exec.Command("git", "init", dir)
	cmd.Env = append(os.Environ(), "GIT_CONFIG_GLOBAL=/dev/null")
	if out, err := cmd.CombinedOutput(); err != nil {
		t.Fatalf("git init: %v\n%s", err, out)
	}

	semDir := filepath.Join(dir, ".semantica")
	if err := os.MkdirAll(semDir, 0o755); err != nil {
		t.Fatal(err)
	}
	bundle := "# Session continuation: x on main\n\n" +
		"Generated by Semantica at 2026-05-10T12:00:00Z. " +
		"Original session: abc-123 (" + provider + ").\n"
	if err := os.WriteFile(filepath.Join(semDir, "handoff.md"), []byte(bundle), 0o644); err != nil {
		t.Fatal(err)
	}
	return dir
}

func TestHandoffContinue_MissingBundleErrorsClearly(t *testing.T) {
	dir := t.TempDir()
	if resolved, err := filepath.EvalSymlinks(dir); err == nil {
		dir = resolved
	}
	cmd := exec.Command("git", "init", dir)
	cmd.Env = append(os.Environ(), "GIT_CONFIG_GLOBAL=/dev/null")
	_ = cmd.Run()

	out, runErr := runRoot(t, []string{"--repo", dir, "handoff", "continue"})
	if runErr == nil {
		t.Fatalf("expected error for missing bundle\nstdout:\n%s", out)
	}
	if !errors.Is(runErr, handoff.ErrBundleMissing) {
		t.Errorf("expected handoff.ErrBundleMissing, got %v", runErr)
	}
	if !strings.Contains(runErr.Error(), "semantica handoff --write") {
		t.Errorf("error should point user at --write:\n%s", runErr.Error())
	}
}

func TestHandoffContinue_ClaudeSpawnPath(t *testing.T) {
	withClaudeOnPath(t, true)
	stub := withStubExecutor(t)
	dir := initRepoWithBundle(t, "claude-code")

	_, err := runRoot(t, []string{"--repo", dir, "handoff", "continue"})
	if err != nil {
		t.Fatalf("continue: %v", err)
	}
	if !stub.called {
		t.Fatal("executor was not invoked for claude-code spawn")
	}
	if !stub.spec.Spawn || stub.spec.Binary != "claude" {
		t.Errorf("spec = %+v, want Spawn=true Binary=claude", stub.spec)
	}
	if len(stub.spec.Args) != 1 || stub.spec.Args[0] != handoff.ContinuePromptFor(filepath.Join(dir, ".semantica", "handoff.md")) {
		t.Errorf("Args = %v, want [%q]", stub.spec.Args, handoff.ContinuePromptFor(filepath.Join(dir, ".semantica", "handoff.md")))
	}
	if stub.workdir != dir {
		t.Errorf("workdir = %q, want %q", stub.workdir, dir)
	}
}

func TestHandoffContinue_PrintFlagSuppressesSpawn(t *testing.T) {
	withClaudeOnPath(t, true)
	stub := withStubExecutor(t)
	dir := initRepoWithBundle(t, "claude-code")

	out, err := runRoot(t, []string{"--repo", dir, "handoff", "continue", "--print"})
	if err != nil {
		t.Fatalf("continue --print: %v", err)
	}
	if stub.called {
		t.Errorf("--print should not exec, but executor was called: %+v", stub.spec)
	}
	if !strings.Contains(out, handoff.ContinuePromptFor(filepath.Join(dir, ".semantica", "handoff.md"))) {
		t.Errorf("print output should include the starter prompt:\n%s", out)
	}
}

// TestHandoffContinue_AgentOverrideForcesPrintPathForKiroIDE
// pins that --agent override targeting a provider with no CLI
// (kiro-ide is the IDE surface, not a binary) routes to the
// print path rather than erroring. cursor used to be the test
// fixture here, but cursor now has a verified spawn path; the
// only remaining no-CLI provider in the launcher's known set is
// kiro-ide.
func TestHandoffContinue_AgentOverrideForcesPrintPathForKiroIDE(t *testing.T) {
	withClaudeOnPath(t, true)
	stub := withStubExecutor(t)
	dir := initRepoWithBundle(t, "claude-code")

	out, err := runRoot(t, []string{"--repo", dir, "handoff", "continue", "--agent", "kiro-ide"})
	if err != nil {
		t.Fatalf("continue --agent kiro-ide: %v", err)
	}
	if stub.called {
		t.Errorf("kiro-ide should fall to print path, but executor was called: %+v", stub.spec)
	}
	if !strings.Contains(out, "kiro-ide") {
		t.Errorf("print message should mention kiro-ide:\n%s", out)
	}
}

func TestHandoffContinue_UnknownProviderErrors(t *testing.T) {
	withClaudeOnPath(t, true)
	withStubExecutor(t)
	dir := initRepoWithBundle(t, "claude-code")

	_, err := runRoot(t, []string{"--repo", dir, "handoff", "continue", "--agent", "not-a-real-agent"})
	if !errors.Is(err, handoff.ErrUnknownProvider) {
		t.Errorf("expected ErrUnknownProvider, got %v", err)
	}
}

func TestHandoffContinue_MalformedBundleAsksForExplicitAgent(t *testing.T) {
	withClaudeOnPath(t, true)
	withStubExecutor(t)
	// Bundle present but missing the Original-session line.
	dir := t.TempDir()
	if resolved, err := filepath.EvalSymlinks(dir); err == nil {
		dir = resolved
	}
	cmd := exec.Command("git", "init", dir)
	cmd.Env = append(os.Environ(), "GIT_CONFIG_GLOBAL=/dev/null")
	_ = cmd.Run()
	semDir := filepath.Join(dir, ".semantica")
	_ = os.MkdirAll(semDir, 0o755)
	_ = os.WriteFile(filepath.Join(semDir, "handoff.md"), []byte("# header only\n"), 0o644)

	_, err := runRoot(t, []string{"--repo", dir, "handoff", "continue"})
	if err == nil {
		t.Fatal("expected error for unparseable bundle without --agent")
	}
	if !strings.Contains(err.Error(), "--agent") {
		t.Errorf("error should suggest --agent:\n%s", err.Error())
	}
}
