package handoff

import (
	"errors"
	"os/exec"
	"strings"
	"testing"
)

// --- ProviderFromBundle ---

func TestProviderFromBundle_ParsesProviderFromHeader(t *testing.T) {
	bundle := []byte("# Session continuation: myrepo on main\n\n" +
		"Generated by Semantica at 2026-05-10T12:00:00Z. Original session: abc-123 (claude-code).\n\n" +
		"## Files touched this session\n")
	if got := ProviderFromBundle(bundle); got != "claude-code" {
		t.Errorf("got %q, want claude-code", got)
	}
}

func TestProviderFromBundle_HandlesAllSupportedProviders(t *testing.T) {
	for _, provider := range []string{
		"claude-code", "cursor", "gemini-cli", "copilot", "kiro-cli", "kiro-ide",
	} {
		bundle := []byte("Original session: x (" + provider + ").")
		if got := ProviderFromBundle(bundle); got != provider {
			t.Errorf("provider %q: got %q", provider, got)
		}
	}
}

func TestProviderFromBundle_ReturnsEmptyOnMalformed(t *testing.T) {
	cases := [][]byte{
		[]byte(""),
		[]byte("Generated by Semantica."),
		[]byte("Original session: just-an-id"), // no provider parens
	}
	for i, c := range cases {
		if got := ProviderFromBundle(c); got != "" {
			t.Errorf("case %d: expected empty, got %q", i, got)
		}
	}
}

// --- BuildLaunchSpec ---

// withLookPath swaps the package-level binary detector so spawn
// branches are deterministic regardless of what's on the test
// machine's PATH.
func withLookPath(t *testing.T, available map[string]bool) {
	t.Helper()
	orig := lookPath
	lookPath = func(name string) (string, error) {
		if available[name] {
			return "/fake/" + name, nil
		}
		return "", exec.ErrNotFound
	}
	t.Cleanup(func() { lookPath = orig })
}

// testBundlePath is the absolute path the launcher tests pass
// through BuildLaunchSpec. The exact value is not important; what
// matters is that the message and args carry it verbatim,
// confirming the prompt and manual hints are usable from any cwd.
const testBundlePath = "/abs/path/to/repo/.semantica/handoff.md"

func TestBuildLaunchSpec_ClaudeSpawnsWhenBinaryPresent(t *testing.T) {
	withLookPath(t, map[string]bool{"claude": true})
	spec, err := BuildLaunchSpec("claude-code", testBundlePath, false)
	if err != nil {
		t.Fatalf("BuildLaunchSpec: %v", err)
	}
	if !spec.Spawn {
		t.Errorf("expected Spawn=true; got spec=%+v", spec)
	}
	if spec.Binary != "claude" {
		t.Errorf("Binary = %q, want claude", spec.Binary)
	}
	wantPrompt := ContinuePromptFor(testBundlePath)
	if len(spec.Args) != 1 || spec.Args[0] != wantPrompt {
		t.Errorf("Args = %v, want [%q]", spec.Args, wantPrompt)
	}
	if !strings.Contains(spec.Args[0], testBundlePath) {
		t.Errorf("prompt should embed absolute bundle path; got %q", spec.Args[0])
	}
}

func TestBuildLaunchSpec_ClaudePrintOnlyOverride(t *testing.T) {
	withLookPath(t, map[string]bool{"claude": true})
	spec, err := BuildLaunchSpec("claude-code", testBundlePath, true)
	if err != nil {
		t.Fatalf("BuildLaunchSpec: %v", err)
	}
	if spec.Spawn {
		t.Errorf("expected Spawn=false under --print; got spec=%+v", spec)
	}
	if !strings.Contains(spec.Message, "claude") || !strings.Contains(spec.Message, testBundlePath) {
		t.Errorf("print message missing binary or absolute bundle path:\n%s", spec.Message)
	}
}

func TestBuildLaunchSpec_ClaudeFallsBackToPrintWhenBinaryMissing(t *testing.T) {
	withLookPath(t, map[string]bool{}) // empty; claude not on PATH
	spec, err := BuildLaunchSpec("claude-code", testBundlePath, false)
	if err != nil {
		t.Fatalf("BuildLaunchSpec: %v", err)
	}
	if spec.Spawn {
		t.Errorf("expected Spawn=false when claude binary absent; got spec=%+v", spec)
	}
	if !strings.Contains(spec.Message, "claude") {
		t.Errorf("print message should mention the missing binary:\n%s", spec.Message)
	}
}

// TestBuildLaunchSpec_OtherProvidersAreManualLaunch covers all
// the providers Semantica's capture pipeline emits but the
// launcher hasn't verified spawn arguments for. kiro-ide is
// included because Semantica captures Kiro IDE sessions too. A
// kiro-ide bundle must produce a graceful manual hint, not an
// unknown-provider error.
func TestBuildLaunchSpec_OtherProvidersAreManualLaunch(t *testing.T) {
	withLookPath(t, map[string]bool{}) // doesn't matter; manual path
	for _, provider := range []string{"cursor", "copilot", "gemini-cli", "kiro-cli", "kiro-ide"} {
		spec, err := BuildLaunchSpec(provider, testBundlePath, false)
		if err != nil {
			t.Errorf("provider %q: BuildLaunchSpec: %v", provider, err)
			continue
		}
		if spec.Spawn {
			t.Errorf("provider %q should not auto-spawn yet; got spec=%+v", provider, spec)
		}
		if !strings.Contains(spec.Message, provider) {
			t.Errorf("provider %q manual hint should mention provider name:\n%s", provider, spec.Message)
		}
		if !strings.Contains(spec.Message, testBundlePath) {
			t.Errorf("provider %q manual hint should embed the absolute bundle path %q:\n%s",
				provider, testBundlePath, spec.Message)
		}
	}
}

func TestBuildLaunchSpec_UnknownProviderErrors(t *testing.T) {
	cases := []string{"", "  ", "not-a-real-agent"}
	for _, p := range cases {
		_, err := BuildLaunchSpec(p, testBundlePath, false)
		if !errors.Is(err, ErrUnknownProvider) {
			t.Errorf("provider %q: expected ErrUnknownProvider, got %v", p, err)
		}
	}
}

// --- shell quoting ---
//
// The launcher's printed command may include a user-controlled
// repo path. Single-quote escaping is deliberate so the printed
// text does not let shell expansions through when pasted: $VAR,
// $(...) command substitution, `` ` `` backticks, and backslashes
// must all stay literal. Each adversarial case below pins one of
// those non-expansions.

func TestQuoteForShell_PreservesSafeArgsAndQuotesUnsafeOnes(t *testing.T) {
	cases := []struct {
		name string
		in   string
		want string
	}{
		{name: "alphanumeric", in: "abc123", want: "abc123"},
		{name: "safe punctuation", in: "abc.def-ghi/x_y", want: "abc.def-ghi/x_y"},
		{name: "absolute path", in: "/tmp/safe-path", want: "/tmp/safe-path"},
		{name: "whitespace", in: "with space", want: `'with space'`},
		{name: "double quotes inside", in: `has "quote"`, want: `'has "quote"'`},

		// Adversarial: every one of these would be expanded by a
		// real shell under double-quote escaping. Single quotes
		// neutralize all of them.
		{name: "dollar variable", in: "$HOME/repo", want: `'$HOME/repo'`},
		{name: "command substitution", in: "$(rm -rf /)", want: `'$(rm -rf /)'`},
		{name: "backtick substitution", in: "`whoami`", want: "'`whoami`'"},
		{name: "backslash literal", in: `a\b\c`, want: `'a\b\c'`},
		{name: "escaped backslash sequence", in: `\n\t`, want: `'\n\t'`},

		// Embedded single quote must round-trip via POSIX
		// '\''  pattern: close, escaped literal, reopen.
		{name: "single quote inside", in: "can't stop", want: `'can'\''t stop'`},
		{name: "leading single quote", in: "'leading", want: `''\''leading'`},
		{name: "only single quote", in: "'", want: `''\'''`},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			got := quoteForShell([]string{tc.in})
			if len(got) != 1 {
				t.Fatalf("got %d args, want 1", len(got))
			}
			if got[0] != tc.want {
				t.Errorf("got %q, want %q", got[0], tc.want)
			}
		})
	}
}

// TestFormatManualMessage_DangerousPathStaysLiteral is the
// integration-level guard for the printed command: a repo path
// that contains $HOME, backticks, or command substitution must
// appear verbatim in the manual-launch hint, not as the
// expansion of those tokens. Single-quote-bearing paths are
// covered by the unit test above (they fragment across quoted
// segments via the POSIX `'\”` pattern, so a literal-substring
// assertion doesn't apply).
func TestFormatManualMessage_DangerousPathStaysLiteral(t *testing.T) {
	cases := []string{
		`/tmp/repo $HOME/handoff.md`,
		"/tmp/repo `whoami`/handoff.md",
		`/tmp/repo $(id -u)/handoff.md`,
		`/tmp/repo \n\t/handoff.md`,
	}
	for _, p := range cases {
		t.Run(p, func(t *testing.T) {
			msg := formatManualMessage("claude", []string{p})
			if !strings.Contains(msg, p) {
				t.Errorf("manual message should contain the literal path %q:\n%s", p, msg)
			}
		})
	}
}
