// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: agents.sql

package db

import (
	"context"
	"database/sql"
)

const getActiveAgentSessionForRepo = `-- name: GetActiveAgentSessionForRepo :one
select session_id, provider_session_id, parent_session_id, repository_id, provider, source_id, started_at, last_seen_at, metadata_json, source_repo_path, model from agent_sessions where repository_id = ? order by last_seen_at desc limit 1
`

func (q *Queries) GetActiveAgentSessionForRepo(ctx context.Context, repositoryID string) (AgentSession, error) {
	row := q.queryRow(ctx, q.getActiveAgentSessionForRepoStmt, getActiveAgentSessionForRepo, repositoryID)
	var i AgentSession
	err := row.Scan(
		&i.SessionID,
		&i.ProviderSessionID,
		&i.ParentSessionID,
		&i.RepositoryID,
		&i.Provider,
		&i.SourceID,
		&i.StartedAt,
		&i.LastSeenAt,
		&i.MetadataJson,
		&i.SourceRepoPath,
		&i.Model,
	)
	return i, err
}

const getAgentSessionByID = `-- name: GetAgentSessionByID :one
select session_id, provider_session_id, parent_session_id, repository_id, provider, source_id, started_at, last_seen_at, metadata_json, source_repo_path, model from agent_sessions where session_id = ?
`

func (q *Queries) GetAgentSessionByID(ctx context.Context, sessionID string) (AgentSession, error) {
	row := q.queryRow(ctx, q.getAgentSessionByIDStmt, getAgentSessionByID, sessionID)
	var i AgentSession
	err := row.Scan(
		&i.SessionID,
		&i.ProviderSessionID,
		&i.ParentSessionID,
		&i.RepositoryID,
		&i.Provider,
		&i.SourceID,
		&i.StartedAt,
		&i.LastSeenAt,
		&i.MetadataJson,
		&i.SourceRepoPath,
		&i.Model,
	)
	return i, err
}

const getAgentSessionByProviderID = `-- name: GetAgentSessionByProviderID :one
select session_id, provider_session_id, parent_session_id, repository_id, provider, source_id, started_at, last_seen_at, metadata_json, source_repo_path, model from agent_sessions
where repository_id = ? and provider = ? and provider_session_id = ?
`

type GetAgentSessionByProviderIDParams struct {
	RepositoryID      string `json:"repository_id"`
	Provider          string `json:"provider"`
	ProviderSessionID string `json:"provider_session_id"`
}

func (q *Queries) GetAgentSessionByProviderID(ctx context.Context, arg GetAgentSessionByProviderIDParams) (AgentSession, error) {
	row := q.queryRow(ctx, q.getAgentSessionByProviderIDStmt, getAgentSessionByProviderID, arg.RepositoryID, arg.Provider, arg.ProviderSessionID)
	var i AgentSession
	err := row.Scan(
		&i.SessionID,
		&i.ProviderSessionID,
		&i.ParentSessionID,
		&i.RepositoryID,
		&i.Provider,
		&i.SourceID,
		&i.StartedAt,
		&i.LastSeenAt,
		&i.MetadataJson,
		&i.SourceRepoPath,
		&i.Model,
	)
	return i, err
}

const getManifestCommitLink = `-- name: GetManifestCommitLink :one
with covering_checkpoint as (
    select cp.checkpoint_id
    from session_checkpoints sc
    join checkpoints cp on sc.checkpoint_id = cp.checkpoint_id
    where sc.session_id = ?
      and cp.created_at >= ?
    order by cp.created_at asc
    limit 1
)
select cl.commit_hash, cl.checkpoint_id
from covering_checkpoint cc
join commit_links cl on cc.checkpoint_id = cl.checkpoint_id
`

type GetManifestCommitLinkParams struct {
	SessionID string `json:"session_id"`
	CreatedAt int64  `json:"created_at"`
}

type GetManifestCommitLinkRow struct {
	CommitHash   string `json:"commit_hash"`
	CheckpointID string `json:"checkpoint_id"`
}

// Resolves the commit link for the checkpoint that covers a manifest.
// First finds the earliest checkpoint in the session created at or after
// the manifest's start time (the covering checkpoint), then joins to
// commit_links. Returns no rows if the covering checkpoint has no commit.
func (q *Queries) GetManifestCommitLink(ctx context.Context, arg GetManifestCommitLinkParams) (GetManifestCommitLinkRow, error) {
	row := q.queryRow(ctx, q.getManifestCommitLinkStmt, getManifestCommitLink, arg.SessionID, arg.CreatedAt)
	var i GetManifestCommitLinkRow
	err := row.Scan(&i.CommitHash, &i.CheckpointID)
	return i, err
}

const getNextToolResultAfter = `-- name: GetNextToolResultAfter :one
select event_id, payload_hash, summary, role, kind, ts
from agent_events
where session_id = ?
  and turn_id = ?
  and kind = 'tool_result'
  and ts > ?
order by ts asc
limit 1
`

type GetNextToolResultAfterParams struct {
	SessionID string         `json:"session_id"`
	TurnID    sql.NullString `json:"turn_id"`
	Ts        int64          `json:"ts"`
}

type GetNextToolResultAfterRow struct {
	EventID     string         `json:"event_id"`
	PayloadHash sql.NullString `json:"payload_hash"`
	Summary     sql.NullString `json:"summary"`
	Role        sql.NullString `json:"role"`
	Kind        string         `json:"kind"`
	Ts          int64          `json:"ts"`
}

// Temporal fallback for companion matching when tool_use_id is empty.
// Returns the first tool_result in the same turn after the given timestamp.
// Used by Claude transcript enrichment where tool_result rows lack tool_use_id.
func (q *Queries) GetNextToolResultAfter(ctx context.Context, arg GetNextToolResultAfterParams) (GetNextToolResultAfterRow, error) {
	row := q.queryRow(ctx, q.getNextToolResultAfterStmt, getNextToolResultAfter, arg.SessionID, arg.TurnID, arg.Ts)
	var i GetNextToolResultAfterRow
	err := row.Scan(
		&i.EventID,
		&i.PayloadHash,
		&i.Summary,
		&i.Role,
		&i.Kind,
		&i.Ts,
	)
	return i, err
}

const getPromptEventForTurn = `-- name: GetPromptEventForTurn :one
select event_id, payload_hash from agent_events
where session_id = ? and turn_id = ?
  and role = 'user' and kind = 'user' and event_source = 'hook'
limit 1
`

type GetPromptEventForTurnParams struct {
	SessionID string         `json:"session_id"`
	TurnID    sql.NullString `json:"turn_id"`
}

type GetPromptEventForTurnRow struct {
	EventID     string         `json:"event_id"`
	PayloadHash sql.NullString `json:"payload_hash"`
}

func (q *Queries) GetPromptEventForTurn(ctx context.Context, arg GetPromptEventForTurnParams) (GetPromptEventForTurnRow, error) {
	row := q.queryRow(ctx, q.getPromptEventForTurnStmt, getPromptEventForTurn, arg.SessionID, arg.TurnID)
	var i GetPromptEventForTurnRow
	err := row.Scan(&i.EventID, &i.PayloadHash)
	return i, err
}

const getSessionWithStats = `-- name: GetSessionWithStats :one
with session_scope as (
    select session_id, provider_session_id, parent_session_id, repository_id, provider, source_id, started_at, last_seen_at, metadata_json, source_repo_path, model from agent_sessions as base where base.session_id = ?
),
event_stats as (
    select
        s.session_id,
        cast(coalesce(max(e.ts), s.last_seen_at) as integer) as last_event_ts,
        cast(count(e.event_id) as integer) as step_count,
        cast(coalesce(sum(case when e.role = 'assistant' and (
            (e.tool_name is not null and e.tool_name != '')
            or (
                e.tool_uses is not null and e.tool_uses != '' and (
                    (json_type(e.tool_uses) = 'array' and json_array_length(e.tool_uses) > 0)
                    or coalesce(json_array_length(json_extract(e.tool_uses, '$.tools')), 0) > 0
                )
            )
        ) then 1 else 0 end), 0) as integer) as tool_call_count
    from session_scope s
    left join agent_events e on e.session_id = s.session_id
    group by s.session_id
),
token_groups as (
    select
        e.session_id,
        coalesce(e.tokens_in, 0) as tokens_in,
        coalesce(e.tokens_out, 0) as tokens_out,
        coalesce(e.tokens_cache_read, 0) as tokens_cache_read,
        coalesce(e.tokens_cache_create, 0) as tokens_cache_create,
        row_number() over (
            partition by
                e.session_id,
                case
                    when e.role = 'assistant' and e.provider_event_id is not null and e.provider_event_id != ''
                        then e.provider_event_id
                    else e.event_id
                end
            order by
                case
                    when e.role = 'assistant' and e.provider_event_id is not null and e.provider_event_id != ''
                        then coalesce(e.tokens_out, 0)
                    else 0
                end desc,
                e.ts desc,
                e.event_id desc
        ) as rn
    from agent_events e
    join session_scope s on s.session_id = e.session_id
),
token_stats as (
    select
        session_id,
        cast(coalesce(sum(tokens_in), 0) as integer) as tokens_in,
        cast(coalesce(sum(tokens_out), 0) as integer) as tokens_out,
        cast(coalesce(sum(tokens_cache_read), 0) + coalesce(sum(tokens_cache_create), 0) as integer) as tokens_cached
    from token_groups
    where rn = 1
    group by session_id
)
select
    s.session_id, s.provider_session_id, s.parent_session_id,
    s.provider, s.started_at,
    es.last_event_ts,
    es.step_count,
    es.tool_call_count,
    cast(coalesce(ts.tokens_in, 0) as integer) as tokens_in,
    cast(coalesce(ts.tokens_out, 0) as integer) as tokens_out,
    cast(coalesce(ts.tokens_cached, 0) as integer) as tokens_cached
from session_scope s
join event_stats es on es.session_id = s.session_id
left join token_stats ts on ts.session_id = s.session_id
`

type GetSessionWithStatsRow struct {
	SessionID         string         `json:"session_id"`
	ProviderSessionID string         `json:"provider_session_id"`
	ParentSessionID   sql.NullString `json:"parent_session_id"`
	Provider          string         `json:"provider"`
	StartedAt         int64          `json:"started_at"`
	LastEventTs       int64          `json:"last_event_ts"`
	StepCount         int64          `json:"step_count"`
	ToolCallCount     int64          `json:"tool_call_count"`
	TokensIn          int64          `json:"tokens_in"`
	TokensOut         int64          `json:"tokens_out"`
	TokensCached      int64          `json:"tokens_cached"`
}

// Single session with computed stats. Same columns as ListSessionsWithStats.
func (q *Queries) GetSessionWithStats(ctx context.Context, sessionID string) (GetSessionWithStatsRow, error) {
	row := q.queryRow(ctx, q.getSessionWithStatsStmt, getSessionWithStats, sessionID)
	var i GetSessionWithStatsRow
	err := row.Scan(
		&i.SessionID,
		&i.ProviderSessionID,
		&i.ParentSessionID,
		&i.Provider,
		&i.StartedAt,
		&i.LastEventTs,
		&i.StepCount,
		&i.ToolCallCount,
		&i.TokensIn,
		&i.TokensOut,
		&i.TokensCached,
	)
	return i, err
}

const insertAgentEvent = `-- name: InsertAgentEvent :exec
insert or ignore into agent_events (
    event_id, session_id, repository_id, ts, kind,
    payload_hash, role, tool_uses,
    tokens_in, tokens_out, tokens_cache_read, tokens_cache_create,
    summary, provider_event_id,
    turn_id, tool_use_id, tool_name, event_source,
    provenance_hash
) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertAgentEventParams struct {
	EventID           string         `json:"event_id"`
	SessionID         string         `json:"session_id"`
	RepositoryID      string         `json:"repository_id"`
	Ts                int64          `json:"ts"`
	Kind              string         `json:"kind"`
	PayloadHash       sql.NullString `json:"payload_hash"`
	Role              sql.NullString `json:"role"`
	ToolUses          sql.NullString `json:"tool_uses"`
	TokensIn          sql.NullInt64  `json:"tokens_in"`
	TokensOut         sql.NullInt64  `json:"tokens_out"`
	TokensCacheRead   sql.NullInt64  `json:"tokens_cache_read"`
	TokensCacheCreate sql.NullInt64  `json:"tokens_cache_create"`
	Summary           sql.NullString `json:"summary"`
	ProviderEventID   sql.NullString `json:"provider_event_id"`
	TurnID            sql.NullString `json:"turn_id"`
	ToolUseID         sql.NullString `json:"tool_use_id"`
	ToolName          sql.NullString `json:"tool_name"`
	EventSource       string         `json:"event_source"`
	ProvenanceHash    sql.NullString `json:"provenance_hash"`
}

func (q *Queries) InsertAgentEvent(ctx context.Context, arg InsertAgentEventParams) error {
	_, err := q.exec(ctx, q.insertAgentEventStmt, insertAgentEvent,
		arg.EventID,
		arg.SessionID,
		arg.RepositoryID,
		arg.Ts,
		arg.Kind,
		arg.PayloadHash,
		arg.Role,
		arg.ToolUses,
		arg.TokensIn,
		arg.TokensOut,
		arg.TokensCacheRead,
		arg.TokensCacheCreate,
		arg.Summary,
		arg.ProviderEventID,
		arg.TurnID,
		arg.ToolUseID,
		arg.ToolName,
		arg.EventSource,
		arg.ProvenanceHash,
	)
	return err
}

const insertSessionCheckpoint = `-- name: InsertSessionCheckpoint :exec
insert or ignore into session_checkpoints (session_id, checkpoint_id) values (?, ?)
`

type InsertSessionCheckpointParams struct {
	SessionID    string `json:"session_id"`
	CheckpointID string `json:"checkpoint_id"`
}

func (q *Queries) InsertSessionCheckpoint(ctx context.Context, arg InsertSessionCheckpointParams) error {
	_, err := q.exec(ctx, q.insertSessionCheckpointStmt, insertSessionCheckpoint, arg.SessionID, arg.CheckpointID)
	return err
}

const listAgentEventsBySession = `-- name: ListAgentEventsBySession :many
select event_id, session_id, repository_id, ts, kind, payload_hash, role, tool_uses, tokens_in, tokens_out, tokens_cache_read, tokens_cache_create, summary, provider_event_id, turn_id, tool_use_id, tool_name, event_source, provenance_hash from agent_events where session_id = ? order by ts desc limit ?
`

type ListAgentEventsBySessionParams struct {
	SessionID string `json:"session_id"`
	Limit     int64  `json:"limit"`
}

func (q *Queries) ListAgentEventsBySession(ctx context.Context, arg ListAgentEventsBySessionParams) ([]AgentEvent, error) {
	rows, err := q.query(ctx, q.listAgentEventsBySessionStmt, listAgentEventsBySession, arg.SessionID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentEvent{}
	for rows.Next() {
		var i AgentEvent
		if err := rows.Scan(
			&i.EventID,
			&i.SessionID,
			&i.RepositoryID,
			&i.Ts,
			&i.Kind,
			&i.PayloadHash,
			&i.Role,
			&i.ToolUses,
			&i.TokensIn,
			&i.TokensOut,
			&i.TokensCacheRead,
			&i.TokensCacheCreate,
			&i.Summary,
			&i.ProviderEventID,
			&i.TurnID,
			&i.ToolUseID,
			&i.ToolName,
			&i.EventSource,
			&i.ProvenanceHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCrossRepoSessions = `-- name: ListCrossRepoSessions :many
select session_id, provider_session_id, parent_session_id, repository_id, provider, source_id, started_at, last_seen_at, metadata_json, source_repo_path, model from agent_sessions
where repository_id = ? and source_repo_path is not null
order by last_seen_at desc limit ?
`

type ListCrossRepoSessionsParams struct {
	RepositoryID string `json:"repository_id"`
	Limit        int64  `json:"limit"`
}

func (q *Queries) ListCrossRepoSessions(ctx context.Context, arg ListCrossRepoSessionsParams) ([]AgentSession, error) {
	rows, err := q.query(ctx, q.listCrossRepoSessionsStmt, listCrossRepoSessions, arg.RepositoryID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentSession{}
	for rows.Next() {
		var i AgentSession
		if err := rows.Scan(
			&i.SessionID,
			&i.ProviderSessionID,
			&i.ParentSessionID,
			&i.RepositoryID,
			&i.Provider,
			&i.SourceID,
			&i.StartedAt,
			&i.LastSeenAt,
			&i.MetadataJson,
			&i.SourceRepoPath,
			&i.Model,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDistinctProviders = `-- name: ListDistinctProviders :many
select distinct provider from agent_sessions where repository_id = ?
`

func (q *Queries) ListDistinctProviders(ctx context.Context, repositoryID string) ([]string, error) {
	rows, err := q.query(ctx, q.listDistinctProvidersStmt, listDistinctProviders, repositoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var provider string
		if err := rows.Scan(&provider); err != nil {
			return nil, err
		}
		items = append(items, provider)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsBySessionASC = `-- name: ListEventsBySessionASC :many
select e.event_id, e.session_id, e.repository_id, e.ts, e.kind, e.payload_hash, e.role, e.tool_uses, e.tokens_in, e.tokens_out, e.tokens_cache_read, e.tokens_cache_create, e.summary, e.provider_event_id, e.turn_id, e.tool_use_id, e.tool_name, e.event_source, e.provenance_hash, s.provider from agent_events e
    join agent_sessions s on s.session_id = e.session_id
where e.session_id = ? order by e.ts, e.event_id
`

type ListEventsBySessionASCRow struct {
	EventID           string         `json:"event_id"`
	SessionID         string         `json:"session_id"`
	RepositoryID      string         `json:"repository_id"`
	Ts                int64          `json:"ts"`
	Kind              string         `json:"kind"`
	PayloadHash       sql.NullString `json:"payload_hash"`
	Role              sql.NullString `json:"role"`
	ToolUses          sql.NullString `json:"tool_uses"`
	TokensIn          sql.NullInt64  `json:"tokens_in"`
	TokensOut         sql.NullInt64  `json:"tokens_out"`
	TokensCacheRead   sql.NullInt64  `json:"tokens_cache_read"`
	TokensCacheCreate sql.NullInt64  `json:"tokens_cache_create"`
	Summary           sql.NullString `json:"summary"`
	ProviderEventID   sql.NullString `json:"provider_event_id"`
	TurnID            sql.NullString `json:"turn_id"`
	ToolUseID         sql.NullString `json:"tool_use_id"`
	ToolName          sql.NullString `json:"tool_name"`
	EventSource       string         `json:"event_source"`
	ProvenanceHash    sql.NullString `json:"provenance_hash"`
	Provider          string         `json:"provider"`
}

func (q *Queries) ListEventsBySessionASC(ctx context.Context, sessionID string) ([]ListEventsBySessionASCRow, error) {
	rows, err := q.query(ctx, q.listEventsBySessionASCStmt, listEventsBySessionASC, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEventsBySessionASCRow{}
	for rows.Next() {
		var i ListEventsBySessionASCRow
		if err := rows.Scan(
			&i.EventID,
			&i.SessionID,
			&i.RepositoryID,
			&i.Ts,
			&i.Kind,
			&i.PayloadHash,
			&i.Role,
			&i.ToolUses,
			&i.TokensIn,
			&i.TokensOut,
			&i.TokensCacheRead,
			&i.TokensCacheCreate,
			&i.Summary,
			&i.ProviderEventID,
			&i.TurnID,
			&i.ToolUseID,
			&i.ToolName,
			&i.EventSource,
			&i.ProvenanceHash,
			&i.Provider,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPackagedManifests = `-- name: ListPackagedManifests :many
select manifest_id, repository_id, session_id, turn_id, provider, kind, transcript_ref, provenance_bundle_hash, started_at, completed_at, status, upload_attempts, last_error, upload_transform_version, remote_verified_at, created_at, updated_at from provenance_manifests
where repository_id = ? and status = 'packaged'
  and upload_attempts < 5
  and (? = 0 or created_at <= ?)
order by created_at
limit ?
`

type ListPackagedManifestsParams struct {
	RepositoryID string      `json:"repository_id"`
	Column2      interface{} `json:"column_2"`
	CreatedAt    int64       `json:"created_at"`
	Limit        int64       `json:"limit"`
}

// Returns manifests ready for upload, scoped to a watermark timestamp.
// Only packaged status with attempts below the retry cap. Pass 0 for
// watermark_ts to drain all.
func (q *Queries) ListPackagedManifests(ctx context.Context, arg ListPackagedManifestsParams) ([]ProvenanceManifest, error) {
	rows, err := q.query(ctx, q.listPackagedManifestsStmt, listPackagedManifests,
		arg.RepositoryID,
		arg.Column2,
		arg.CreatedAt,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProvenanceManifest{}
	for rows.Next() {
		var i ProvenanceManifest
		if err := rows.Scan(
			&i.ManifestID,
			&i.RepositoryID,
			&i.SessionID,
			&i.TurnID,
			&i.Provider,
			&i.Kind,
			&i.TranscriptRef,
			&i.ProvenanceBundleHash,
			&i.StartedAt,
			&i.CompletedAt,
			&i.Status,
			&i.UploadAttempts,
			&i.LastError,
			&i.UploadTransformVersion,
			&i.RemoteVerifiedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingManifests = `-- name: ListPendingManifests :many
select manifest_id, repository_id, session_id, turn_id, provider, kind, transcript_ref, provenance_bundle_hash, started_at, completed_at, status, upload_attempts, last_error, upload_transform_version, remote_verified_at, created_at, updated_at from provenance_manifests
where repository_id = ? and status in ('pending', 'packaged')
order by created_at
limit ?
`

type ListPendingManifestsParams struct {
	RepositoryID string `json:"repository_id"`
	Limit        int64  `json:"limit"`
}

func (q *Queries) ListPendingManifests(ctx context.Context, arg ListPendingManifestsParams) ([]ProvenanceManifest, error) {
	rows, err := q.query(ctx, q.listPendingManifestsStmt, listPendingManifests, arg.RepositoryID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProvenanceManifest{}
	for rows.Next() {
		var i ProvenanceManifest
		if err := rows.Scan(
			&i.ManifestID,
			&i.RepositoryID,
			&i.SessionID,
			&i.TurnID,
			&i.Provider,
			&i.Kind,
			&i.TranscriptRef,
			&i.ProvenanceBundleHash,
			&i.StartedAt,
			&i.CompletedAt,
			&i.Status,
			&i.UploadAttempts,
			&i.LastError,
			&i.UploadTransformVersion,
			&i.RemoteVerifiedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProvidersByCheckpoint = `-- name: ListProvidersByCheckpoint :many
select distinct s.provider from agent_sessions s
    join session_checkpoints sc on sc.session_id = s.session_id
where sc.checkpoint_id = ?
`

func (q *Queries) ListProvidersByCheckpoint(ctx context.Context, checkpointID string) ([]string, error) {
	rows, err := q.query(ctx, q.listProvidersByCheckpointStmt, listProvidersByCheckpoint, checkpointID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var provider string
		if err := rows.Scan(&provider); err != nil {
			return nil, err
		}
		items = append(items, provider)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentSessionsWithStats = `-- name: ListRecentSessionsWithStats :many
with session_scope as (
    select session_id, provider_session_id, parent_session_id, repository_id, provider, source_id, started_at, last_seen_at, metadata_json, source_repo_path, model from agent_sessions as base
    where base.repository_id = ? and base.last_seen_at > ?3
),
event_stats as (
    select
        s.session_id,
        cast(coalesce(max(e.ts), s.last_seen_at) as integer) as last_event_ts,
        cast(count(e.event_id) as integer) as step_count
    from session_scope s
    left join agent_events e on e.session_id = s.session_id
    group by s.session_id
),
token_groups as (
    select
        e.session_id,
        coalesce(e.tokens_in, 0) as tokens_in,
        coalesce(e.tokens_out, 0) as tokens_out,
        coalesce(e.tokens_cache_read, 0) as tokens_cache_read,
        coalesce(e.tokens_cache_create, 0) as tokens_cache_create,
        row_number() over (
            partition by
                e.session_id,
                case
                    when e.role = 'assistant' and e.provider_event_id is not null and e.provider_event_id != ''
                        then e.provider_event_id
                    else e.event_id
                end
            order by
                case
                    when e.role = 'assistant' and e.provider_event_id is not null and e.provider_event_id != ''
                        then coalesce(e.tokens_out, 0)
                    else 0
                end desc,
                e.ts desc,
                e.event_id desc
        ) as rn
    from agent_events e
    join session_scope s on s.session_id = e.session_id
),
token_stats as (
    select
        session_id,
        cast(coalesce(sum(tokens_in), 0) as integer) as tokens_in,
        cast(coalesce(sum(tokens_out), 0) as integer) as tokens_out,
        cast(coalesce(sum(tokens_cache_read), 0) + coalesce(sum(tokens_cache_create), 0) as integer) as tokens_cached
    from token_groups
    where rn = 1
    group by session_id
)
select
    s.session_id, s.provider_session_id, s.parent_session_id,
    s.provider, s.started_at,
    es.last_event_ts,
    es.step_count,
    cast(coalesce(ts.tokens_in, 0) as integer) as tokens_in,
    cast(coalesce(ts.tokens_out, 0) as integer) as tokens_out,
    cast(coalesce(ts.tokens_cached, 0) as integer) as tokens_cached
from session_scope s
join event_stats es on es.session_id = s.session_id
left join token_stats ts on ts.session_id = s.session_id
where es.step_count > 0
order by es.last_event_ts desc
limit ?
`

type ListRecentSessionsWithStatsParams struct {
	RepositoryID string `json:"repository_id"`
	SinceTs      int64  `json:"since_ts"`
	Limit        int64  `json:"limit"`
}

type ListRecentSessionsWithStatsRow struct {
	SessionID         string         `json:"session_id"`
	ProviderSessionID string         `json:"provider_session_id"`
	ParentSessionID   sql.NullString `json:"parent_session_id"`
	Provider          string         `json:"provider"`
	StartedAt         int64          `json:"started_at"`
	LastEventTs       int64          `json:"last_event_ts"`
	StepCount         int64          `json:"step_count"`
	TokensIn          int64          `json:"tokens_in"`
	TokensOut         int64          `json:"tokens_out"`
	TokensCached      int64          `json:"tokens_cached"`
}

// Same token separation as ListSessionsWithStats (see comment above).
func (q *Queries) ListRecentSessionsWithStats(ctx context.Context, arg ListRecentSessionsWithStatsParams) ([]ListRecentSessionsWithStatsRow, error) {
	rows, err := q.query(ctx, q.listRecentSessionsWithStatsStmt, listRecentSessionsWithStats, arg.RepositoryID, arg.SinceTs, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecentSessionsWithStatsRow{}
	for rows.Next() {
		var i ListRecentSessionsWithStatsRow
		if err := rows.Scan(
			&i.SessionID,
			&i.ProviderSessionID,
			&i.ParentSessionID,
			&i.Provider,
			&i.StartedAt,
			&i.LastEventTs,
			&i.StepCount,
			&i.TokensIn,
			&i.TokensOut,
			&i.TokensCached,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionsForCheckpoint = `-- name: ListSessionsForCheckpoint :many
select s.session_id, s.provider_session_id, s.parent_session_id, s.repository_id, s.provider, s.source_id, s.started_at, s.last_seen_at, s.metadata_json, s.source_repo_path, s.model from agent_sessions s
    join session_checkpoints sc on sc.session_id = s.session_id
where sc.checkpoint_id = ? order by s.started_at
`

func (q *Queries) ListSessionsForCheckpoint(ctx context.Context, checkpointID string) ([]AgentSession, error) {
	rows, err := q.query(ctx, q.listSessionsForCheckpointStmt, listSessionsForCheckpoint, checkpointID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentSession{}
	for rows.Next() {
		var i AgentSession
		if err := rows.Scan(
			&i.SessionID,
			&i.ProviderSessionID,
			&i.ParentSessionID,
			&i.RepositoryID,
			&i.Provider,
			&i.SourceID,
			&i.StartedAt,
			&i.LastSeenAt,
			&i.MetadataJson,
			&i.SourceRepoPath,
			&i.Model,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionsForRepository = `-- name: ListSessionsForRepository :many
select session_id, provider_session_id, parent_session_id, repository_id, provider, source_id, started_at, last_seen_at, metadata_json, source_repo_path, model from agent_sessions where repository_id = ?
order by last_seen_at desc limit ?
`

type ListSessionsForRepositoryParams struct {
	RepositoryID string `json:"repository_id"`
	Limit        int64  `json:"limit"`
}

func (q *Queries) ListSessionsForRepository(ctx context.Context, arg ListSessionsForRepositoryParams) ([]AgentSession, error) {
	rows, err := q.query(ctx, q.listSessionsForRepositoryStmt, listSessionsForRepository, arg.RepositoryID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentSession{}
	for rows.Next() {
		var i AgentSession
		if err := rows.Scan(
			&i.SessionID,
			&i.ProviderSessionID,
			&i.ParentSessionID,
			&i.RepositoryID,
			&i.Provider,
			&i.SourceID,
			&i.StartedAt,
			&i.LastSeenAt,
			&i.MetadataJson,
			&i.SourceRepoPath,
			&i.Model,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionsWithEventsInWindow = `-- name: ListSessionsWithEventsInWindow :many
select distinct e.session_id from agent_events e
where e.repository_id = ?
  and e.ts > ?2
  and e.ts <= ?3
`

type ListSessionsWithEventsInWindowParams struct {
	RepositoryID string `json:"repository_id"`
	AfterTs      int64  `json:"after_ts"`
	UpToTs       int64  `json:"up_to_ts"`
}

// Returns distinct session IDs that have at least one event in the given
// time window [after_ts, up_to_ts] for the specified repository.
func (q *Queries) ListSessionsWithEventsInWindow(ctx context.Context, arg ListSessionsWithEventsInWindowParams) ([]string, error) {
	rows, err := q.query(ctx, q.listSessionsWithEventsInWindowStmt, listSessionsWithEventsInWindow, arg.RepositoryID, arg.AfterTs, arg.UpToTs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var session_id string
		if err := rows.Scan(&session_id); err != nil {
			return nil, err
		}
		items = append(items, session_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionsWithStats = `-- name: ListSessionsWithStats :many
with session_scope as (
    select session_id, provider_session_id, parent_session_id, repository_id, provider, source_id, started_at, last_seen_at, metadata_json, source_repo_path, model from agent_sessions as base where base.repository_id = ?
),
event_stats as (
    select
        s.session_id,
        cast(coalesce(max(e.ts), s.last_seen_at) as integer) as last_event_ts,
        cast(count(e.event_id) as integer) as step_count,
        cast(coalesce(sum(case when e.role = 'assistant' and (
            (e.tool_name is not null and e.tool_name != '')
            or (
                e.tool_uses is not null and e.tool_uses != '' and (
                    (json_type(e.tool_uses) = 'array' and json_array_length(e.tool_uses) > 0)
                    or coalesce(json_array_length(json_extract(e.tool_uses, '$.tools')), 0) > 0
                )
            )
        ) then 1 else 0 end), 0) as integer) as tool_call_count
    from session_scope s
    left join agent_events e on e.session_id = s.session_id
    group by s.session_id
),
token_groups as (
    select
        e.session_id,
        coalesce(e.tokens_in, 0) as tokens_in,
        coalesce(e.tokens_out, 0) as tokens_out,
        coalesce(e.tokens_cache_read, 0) as tokens_cache_read,
        coalesce(e.tokens_cache_create, 0) as tokens_cache_create,
        row_number() over (
            partition by
                e.session_id,
                case
                    when e.role = 'assistant' and e.provider_event_id is not null and e.provider_event_id != ''
                        then e.provider_event_id
                    else e.event_id
                end
            order by
                case
                    when e.role = 'assistant' and e.provider_event_id is not null and e.provider_event_id != ''
                        then coalesce(e.tokens_out, 0)
                    else 0
                end desc,
                e.ts desc,
                e.event_id desc
        ) as rn
    from agent_events e
    join session_scope s on s.session_id = e.session_id
),
token_stats as (
    select
        session_id,
        cast(coalesce(sum(tokens_in), 0) as integer) as tokens_in,
        cast(coalesce(sum(tokens_out), 0) as integer) as tokens_out,
        cast(coalesce(sum(tokens_cache_read), 0) + coalesce(sum(tokens_cache_create), 0) as integer) as tokens_cached
    from token_groups
    where rn = 1
    group by session_id
)
select
    s.session_id, s.provider_session_id, s.parent_session_id,
    s.provider, s.started_at,
    es.last_event_ts,
    es.step_count,
    es.tool_call_count,
    cast(coalesce(ts.tokens_in, 0) as integer) as tokens_in,
    cast(coalesce(ts.tokens_out, 0) as integer) as tokens_out,
    cast(coalesce(ts.tokens_cached, 0) as integer) as tokens_cached
from session_scope s
join event_stats es on es.session_id = s.session_id
left join token_stats ts on ts.session_id = s.session_id
where es.step_count > 0
order by es.last_event_ts desc
limit ?
`

type ListSessionsWithStatsParams struct {
	RepositoryID string `json:"repository_id"`
	Limit        int64  `json:"limit"`
}

type ListSessionsWithStatsRow struct {
	SessionID         string         `json:"session_id"`
	ProviderSessionID string         `json:"provider_session_id"`
	ParentSessionID   sql.NullString `json:"parent_session_id"`
	Provider          string         `json:"provider"`
	StartedAt         int64          `json:"started_at"`
	LastEventTs       int64          `json:"last_event_ts"`
	StepCount         int64          `json:"step_count"`
	ToolCallCount     int64          `json:"tool_call_count"`
	TokensIn          int64          `json:"tokens_in"`
	TokensOut         int64          `json:"tokens_out"`
	TokensCached      int64          `json:"tokens_cached"`
}

// tokens_in is the non-cached input token count reported by the provider.
// tokens_cached is cache_read + cache_create. Claude's API reports input_tokens
// as only the non-cached portion; with heavy prompt caching the cached portion
// can be >99% of actual context, so we report them separately for clarity.
func (q *Queries) ListSessionsWithStats(ctx context.Context, arg ListSessionsWithStatsParams) ([]ListSessionsWithStatsRow, error) {
	rows, err := q.query(ctx, q.listSessionsWithStatsStmt, listSessionsWithStats, arg.RepositoryID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSessionsWithStatsRow{}
	for rows.Next() {
		var i ListSessionsWithStatsRow
		if err := rows.Scan(
			&i.SessionID,
			&i.ProviderSessionID,
			&i.ParentSessionID,
			&i.Provider,
			&i.StartedAt,
			&i.LastEventTs,
			&i.StepCount,
			&i.ToolCallCount,
			&i.TokensIn,
			&i.TokensOut,
			&i.TokensCached,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionsWithStatsAll = `-- name: ListSessionsWithStatsAll :many
with session_scope as (
    select session_id, provider_session_id, parent_session_id, repository_id, provider, source_id, started_at, last_seen_at, metadata_json, source_repo_path, model from agent_sessions as base where base.repository_id = ?
),
event_stats as (
    select
        s.session_id,
        cast(coalesce(max(e.ts), s.last_seen_at) as integer) as last_event_ts,
        cast(count(e.event_id) as integer) as step_count,
        cast(coalesce(sum(case when e.role = 'assistant' and (
            (e.tool_name is not null and e.tool_name != '')
            or (
                e.tool_uses is not null and e.tool_uses != '' and (
                    (json_type(e.tool_uses) = 'array' and json_array_length(e.tool_uses) > 0)
                    or coalesce(json_array_length(json_extract(e.tool_uses, '$.tools')), 0) > 0
                )
            )
        ) then 1 else 0 end), 0) as integer) as tool_call_count
    from session_scope s
    left join agent_events e on e.session_id = s.session_id
    group by s.session_id
),
token_groups as (
    select
        e.session_id,
        coalesce(e.tokens_in, 0) as tokens_in,
        coalesce(e.tokens_out, 0) as tokens_out,
        coalesce(e.tokens_cache_read, 0) as tokens_cache_read,
        coalesce(e.tokens_cache_create, 0) as tokens_cache_create,
        row_number() over (
            partition by
                e.session_id,
                case
                    when e.role = 'assistant' and e.provider_event_id is not null and e.provider_event_id != ''
                        then e.provider_event_id
                    else e.event_id
                end
            order by
                case
                    when e.role = 'assistant' and e.provider_event_id is not null and e.provider_event_id != ''
                        then coalesce(e.tokens_out, 0)
                    else 0
                end desc,
                e.ts desc,
                e.event_id desc
        ) as rn
    from agent_events e
    join session_scope s on s.session_id = e.session_id
),
token_stats as (
    select
        session_id,
        cast(coalesce(sum(tokens_in), 0) as integer) as tokens_in,
        cast(coalesce(sum(tokens_out), 0) as integer) as tokens_out,
        cast(coalesce(sum(tokens_cache_read), 0) + coalesce(sum(tokens_cache_create), 0) as integer) as tokens_cached
    from token_groups
    where rn = 1
    group by session_id
)
select
    s.session_id, s.provider_session_id, s.parent_session_id,
    s.provider, s.started_at,
    es.last_event_ts,
    es.step_count,
    es.tool_call_count,
    cast(coalesce(ts.tokens_in, 0) as integer) as tokens_in,
    cast(coalesce(ts.tokens_out, 0) as integer) as tokens_out,
    cast(coalesce(ts.tokens_cached, 0) as integer) as tokens_cached
from session_scope s
join event_stats es on es.session_id = s.session_id
left join token_stats ts on ts.session_id = s.session_id
order by es.last_event_ts desc
limit ?
`

type ListSessionsWithStatsAllParams struct {
	RepositoryID string `json:"repository_id"`
	Limit        int64  `json:"limit"`
}

type ListSessionsWithStatsAllRow struct {
	SessionID         string         `json:"session_id"`
	ProviderSessionID string         `json:"provider_session_id"`
	ParentSessionID   sql.NullString `json:"parent_session_id"`
	Provider          string         `json:"provider"`
	StartedAt         int64          `json:"started_at"`
	LastEventTs       int64          `json:"last_event_ts"`
	StepCount         int64          `json:"step_count"`
	ToolCallCount     int64          `json:"tool_call_count"`
	TokensIn          int64          `json:"tokens_in"`
	TokensOut         int64          `json:"tokens_out"`
	TokensCached      int64          `json:"tokens_cached"`
}

// Same as ListSessionsWithStats but includes sessions with zero events.
func (q *Queries) ListSessionsWithStatsAll(ctx context.Context, arg ListSessionsWithStatsAllParams) ([]ListSessionsWithStatsAllRow, error) {
	rows, err := q.query(ctx, q.listSessionsWithStatsAllStmt, listSessionsWithStatsAll, arg.RepositoryID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSessionsWithStatsAllRow{}
	for rows.Next() {
		var i ListSessionsWithStatsAllRow
		if err := rows.Scan(
			&i.SessionID,
			&i.ProviderSessionID,
			&i.ParentSessionID,
			&i.Provider,
			&i.StartedAt,
			&i.LastEventTs,
			&i.StepCount,
			&i.ToolCallCount,
			&i.TokensIn,
			&i.TokensOut,
			&i.TokensCached,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStepCompanionResults = `-- name: ListStepCompanionResults :many
select event_id, payload_hash, summary, role, kind, ts
from agent_events
where session_id = ?
  and turn_id = ?
  and tool_use_id = ?
  and kind = 'tool_result'
order by ts asc
`

type ListStepCompanionResultsParams struct {
	SessionID string         `json:"session_id"`
	TurnID    sql.NullString `json:"turn_id"`
	ToolUseID sql.NullString `json:"tool_use_id"`
}

type ListStepCompanionResultsRow struct {
	EventID     string         `json:"event_id"`
	PayloadHash sql.NullString `json:"payload_hash"`
	Summary     sql.NullString `json:"summary"`
	Role        sql.NullString `json:"role"`
	Kind        string         `json:"kind"`
	Ts          int64          `json:"ts"`
}

// Returns tool_result events matching a step's tool_use_id, ordered by
// timestamp. Returned as :many so the provider enricher can choose the
// right pairing when multiple results exist (e.g., retried tool calls).
func (q *Queries) ListStepCompanionResults(ctx context.Context, arg ListStepCompanionResultsParams) ([]ListStepCompanionResultsRow, error) {
	rows, err := q.query(ctx, q.listStepCompanionResultsStmt, listStepCompanionResults, arg.SessionID, arg.TurnID, arg.ToolUseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStepCompanionResultsRow{}
	for rows.Next() {
		var i ListStepCompanionResultsRow
		if err := rows.Scan(
			&i.EventID,
			&i.PayloadHash,
			&i.Summary,
			&i.Role,
			&i.Kind,
			&i.Ts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStepEventsForTurn = `-- name: ListStepEventsForTurn :many
select event_id, ts, tool_name, tool_use_id, provenance_hash, payload_hash,
       summary, event_source, tool_uses
from agent_events
where session_id = ? and turn_id = ?
  and tool_name is not null
order by ts
`

type ListStepEventsForTurnParams struct {
	SessionID string         `json:"session_id"`
	TurnID    sql.NullString `json:"turn_id"`
}

type ListStepEventsForTurnRow struct {
	EventID        string         `json:"event_id"`
	Ts             int64          `json:"ts"`
	ToolName       sql.NullString `json:"tool_name"`
	ToolUseID      sql.NullString `json:"tool_use_id"`
	ProvenanceHash sql.NullString `json:"provenance_hash"`
	PayloadHash    sql.NullString `json:"payload_hash"`
	Summary        sql.NullString `json:"summary"`
	EventSource    string         `json:"event_source"`
	ToolUses       sql.NullString `json:"tool_uses"`
}

// Returns step events for provenance bundle packaging.
// Includes both hook-captured and transcript-sourced events
// so providers without direct hook capture are covered.
func (q *Queries) ListStepEventsForTurn(ctx context.Context, arg ListStepEventsForTurnParams) ([]ListStepEventsForTurnRow, error) {
	rows, err := q.query(ctx, q.listStepEventsForTurnStmt, listStepEventsForTurn, arg.SessionID, arg.TurnID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStepEventsForTurnRow{}
	for rows.Next() {
		var i ListStepEventsForTurnRow
		if err := rows.Scan(
			&i.EventID,
			&i.Ts,
			&i.ToolName,
			&i.ToolUseID,
			&i.ProvenanceHash,
			&i.PayloadHash,
			&i.Summary,
			&i.EventSource,
			&i.ToolUses,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStepProvenanceForTurn = `-- name: ListStepProvenanceForTurn :many
select event_id, tool_use_id, tool_name, provenance_hash
from agent_events
where session_id = ? and turn_id = ?
  and provenance_hash is not null
  and tool_name is not null
order by ts
`

type ListStepProvenanceForTurnParams struct {
	SessionID string         `json:"session_id"`
	TurnID    sql.NullString `json:"turn_id"`
}

type ListStepProvenanceForTurnRow struct {
	EventID        string         `json:"event_id"`
	ToolUseID      sql.NullString `json:"tool_use_id"`
	ToolName       sql.NullString `json:"tool_name"`
	ProvenanceHash sql.NullString `json:"provenance_hash"`
}

// Returns step provenance hashes for a turn, used to build the upload envelope.
func (q *Queries) ListStepProvenanceForTurn(ctx context.Context, arg ListStepProvenanceForTurnParams) ([]ListStepProvenanceForTurnRow, error) {
	rows, err := q.query(ctx, q.listStepProvenanceForTurnStmt, listStepProvenanceForTurn, arg.SessionID, arg.TurnID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStepProvenanceForTurnRow{}
	for rows.Next() {
		var i ListStepProvenanceForTurnRow
		if err := rows.Scan(
			&i.EventID,
			&i.ToolUseID,
			&i.ToolName,
			&i.ProvenanceHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markManifestFailed = `-- name: MarkManifestFailed :exec
update provenance_manifests set
    status = 'failed',
    upload_attempts = upload_attempts + 1,
    last_error = ?,
    updated_at = ?
where manifest_id = ?
`

type MarkManifestFailedParams struct {
	LastError  sql.NullString `json:"last_error"`
	UpdatedAt  int64          `json:"updated_at"`
	ManifestID string         `json:"manifest_id"`
}

func (q *Queries) MarkManifestFailed(ctx context.Context, arg MarkManifestFailedParams) error {
	_, err := q.exec(ctx, q.markManifestFailedStmt, markManifestFailed, arg.LastError, arg.UpdatedAt, arg.ManifestID)
	return err
}

const markManifestUploaded = `-- name: MarkManifestUploaded :exec
update provenance_manifests set status = 'uploaded', updated_at = ? where manifest_id = ?
`

type MarkManifestUploadedParams struct {
	UpdatedAt  int64  `json:"updated_at"`
	ManifestID string `json:"manifest_id"`
}

func (q *Queries) MarkManifestUploaded(ctx context.Context, arg MarkManifestUploadedParams) error {
	_, err := q.exec(ctx, q.markManifestUploadedStmt, markManifestUploaded, arg.UpdatedAt, arg.ManifestID)
	return err
}

const markManifestUploading = `-- name: MarkManifestUploading :execrows
update provenance_manifests set status = 'uploading', updated_at = ?
where manifest_id = ? and status = 'packaged'
`

type MarkManifestUploadingParams struct {
	UpdatedAt  int64  `json:"updated_at"`
	ManifestID string `json:"manifest_id"`
}

// Guards on status='packaged' so concurrent sync workers cannot both claim
// the same manifest. Caller checks rows affected: 0 means already claimed.
func (q *Queries) MarkManifestUploading(ctx context.Context, arg MarkManifestUploadingParams) (int64, error) {
	result, err := q.exec(ctx, q.markManifestUploadingStmt, markManifestUploading, arg.UpdatedAt, arg.ManifestID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const promptEventExists = `-- name: PromptEventExists :one
select count(*) > 0 as exists_flag from agent_events
where turn_id = ?
  and role = 'user'
  and kind = 'user'
  and event_source = 'hook'
`

func (q *Queries) PromptEventExists(ctx context.Context, turnID sql.NullString) (bool, error) {
	row := q.queryRow(ctx, q.promptEventExistsStmt, promptEventExists, turnID)
	var exists_flag bool
	err := row.Scan(&exists_flag)
	return exists_flag, err
}

const recoverStaleUploading = `-- name: RecoverStaleUploading :exec
update provenance_manifests set status = 'packaged', updated_at = ?
where status = 'uploading' and updated_at < ?
`

type RecoverStaleUploadingParams struct {
	UpdatedAt   int64 `json:"updated_at"`
	UpdatedAt_2 int64 `json:"updated_at_2"`
}

// Resets manifests stuck in uploading after a crash. Threshold is a unix ms
// timestamp; rows with updated_at older than this are reset to packaged.
func (q *Queries) RecoverStaleUploading(ctx context.Context, arg RecoverStaleUploadingParams) error {
	_, err := q.exec(ctx, q.recoverStaleUploadingStmt, recoverStaleUploading, arg.UpdatedAt, arg.UpdatedAt_2)
	return err
}

const resetManifestForRetry = `-- name: ResetManifestForRetry :exec
update provenance_manifests set
    status = 'packaged',
    upload_attempts = upload_attempts + 1,
    last_error = ?,
    updated_at = ?
where manifest_id = ?
`

type ResetManifestForRetryParams struct {
	LastError  sql.NullString `json:"last_error"`
	UpdatedAt  int64          `json:"updated_at"`
	ManifestID string         `json:"manifest_id"`
}

// Resets a failed or uploading manifest back to packaged for retry.
// Increments upload_attempts and records the error for diagnostics.
func (q *Queries) ResetManifestForRetry(ctx context.Context, arg ResetManifestForRetryParams) error {
	_, err := q.exec(ctx, q.resetManifestForRetryStmt, resetManifestForRetry, arg.LastError, arg.UpdatedAt, arg.ManifestID)
	return err
}

const resetManifestToPackaged = `-- name: ResetManifestToPackaged :exec
update provenance_manifests set
    status = 'packaged',
    updated_at = ?
where manifest_id = ?
`

type ResetManifestToPackagedParams struct {
	UpdatedAt  int64  `json:"updated_at"`
	ManifestID string `json:"manifest_id"`
}

// Resets a manifest back to packaged without incrementing upload_attempts.
// Used for auth failures where the manifest itself is healthy and should
// not burn a retry attempt.
func (q *Queries) ResetManifestToPackaged(ctx context.Context, arg ResetManifestToPackagedParams) error {
	_, err := q.exec(ctx, q.resetManifestToPackagedStmt, resetManifestToPackaged, arg.UpdatedAt, arg.ManifestID)
	return err
}

const resolveSessionByPrefix = `-- name: ResolveSessionByPrefix :many
select session_id from agent_sessions
where session_id like ? and repository_id = ?
limit 2
`

type ResolveSessionByPrefixParams struct {
	SessionID    string `json:"session_id"`
	RepositoryID string `json:"repository_id"`
}

func (q *Queries) ResolveSessionByPrefix(ctx context.Context, arg ResolveSessionByPrefixParams) ([]string, error) {
	rows, err := q.query(ctx, q.resolveSessionByPrefixStmt, resolveSessionByPrefix, arg.SessionID, arg.RepositoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var session_id string
		if err := rows.Scan(&session_id); err != nil {
			return nil, err
		}
		items = append(items, session_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const stepEventExists = `-- name: StepEventExists :one
select count(*) > 0 as exists_flag from agent_events
where turn_id = ? and tool_use_id = ? and tool_name = ?
`

type StepEventExistsParams struct {
	TurnID    sql.NullString `json:"turn_id"`
	ToolUseID sql.NullString `json:"tool_use_id"`
	ToolName  sql.NullString `json:"tool_name"`
}

func (q *Queries) StepEventExists(ctx context.Context, arg StepEventExistsParams) (bool, error) {
	row := q.queryRow(ctx, q.stepEventExistsStmt, stepEventExists, arg.TurnID, arg.ToolUseID, arg.ToolName)
	var exists_flag bool
	err := row.Scan(&exists_flag)
	return exists_flag, err
}

const upsertAgentSession = `-- name: UpsertAgentSession :one
insert into agent_sessions (
    session_id, provider_session_id, parent_session_id,
    repository_id, provider, source_id,
    started_at, last_seen_at, metadata_json,
    source_repo_path, model
) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
on conflict(repository_id, provider, provider_session_id) do update set
    parent_session_id=excluded.parent_session_id,
    last_seen_at=excluded.last_seen_at,
    metadata_json=excluded.metadata_json,
    source_repo_path=coalesce(agent_sessions.source_repo_path, excluded.source_repo_path),
    model=coalesce(excluded.model, agent_sessions.model)
returning session_id, provider_session_id, parent_session_id, repository_id, provider, source_id, started_at, last_seen_at, metadata_json, source_repo_path, model
`

type UpsertAgentSessionParams struct {
	SessionID         string         `json:"session_id"`
	ProviderSessionID string         `json:"provider_session_id"`
	ParentSessionID   sql.NullString `json:"parent_session_id"`
	RepositoryID      string         `json:"repository_id"`
	Provider          string         `json:"provider"`
	SourceID          string         `json:"source_id"`
	StartedAt         int64          `json:"started_at"`
	LastSeenAt        int64          `json:"last_seen_at"`
	MetadataJson      string         `json:"metadata_json"`
	SourceRepoPath    sql.NullString `json:"source_repo_path"`
	Model             sql.NullString `json:"model"`
}

func (q *Queries) UpsertAgentSession(ctx context.Context, arg UpsertAgentSessionParams) (AgentSession, error) {
	row := q.queryRow(ctx, q.upsertAgentSessionStmt, upsertAgentSession,
		arg.SessionID,
		arg.ProviderSessionID,
		arg.ParentSessionID,
		arg.RepositoryID,
		arg.Provider,
		arg.SourceID,
		arg.StartedAt,
		arg.LastSeenAt,
		arg.MetadataJson,
		arg.SourceRepoPath,
		arg.Model,
	)
	var i AgentSession
	err := row.Scan(
		&i.SessionID,
		&i.ProviderSessionID,
		&i.ParentSessionID,
		&i.RepositoryID,
		&i.Provider,
		&i.SourceID,
		&i.StartedAt,
		&i.LastSeenAt,
		&i.MetadataJson,
		&i.SourceRepoPath,
		&i.Model,
	)
	return i, err
}

const upsertAgentSource = `-- name: UpsertAgentSource :one
insert into agent_sources (
    source_id, repository_id, provider, source_key, last_seen_at, created_at
) values (?, ?, ?, ?, ?, ?)
on conflict(repository_id, provider, source_key) do update set
    last_seen_at=excluded.last_seen_at
returning source_id, repository_id, provider, source_key, last_seen_at, created_at
`

type UpsertAgentSourceParams struct {
	SourceID     string `json:"source_id"`
	RepositoryID string `json:"repository_id"`
	Provider     string `json:"provider"`
	SourceKey    string `json:"source_key"`
	LastSeenAt   int64  `json:"last_seen_at"`
	CreatedAt    int64  `json:"created_at"`
}

func (q *Queries) UpsertAgentSource(ctx context.Context, arg UpsertAgentSourceParams) (AgentSource, error) {
	row := q.queryRow(ctx, q.upsertAgentSourceStmt, upsertAgentSource,
		arg.SourceID,
		arg.RepositoryID,
		arg.Provider,
		arg.SourceKey,
		arg.LastSeenAt,
		arg.CreatedAt,
	)
	var i AgentSource
	err := row.Scan(
		&i.SourceID,
		&i.RepositoryID,
		&i.Provider,
		&i.SourceKey,
		&i.LastSeenAt,
		&i.CreatedAt,
	)
	return i, err
}

const upsertProvenanceManifest = `-- name: UpsertProvenanceManifest :exec
insert into provenance_manifests (
    manifest_id, repository_id, session_id, turn_id, provider, kind,
    transcript_ref, provenance_bundle_hash,
    started_at, completed_at, status,
    upload_attempts, created_at, updated_at
) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 0, ?, ?)
on conflict(repository_id, session_id, turn_id, kind) do update set
    transcript_ref=excluded.transcript_ref,
    provenance_bundle_hash=excluded.provenance_bundle_hash,
    completed_at=excluded.completed_at,
    status=excluded.status,
    updated_at=excluded.updated_at
`

type UpsertProvenanceManifestParams struct {
	ManifestID           string         `json:"manifest_id"`
	RepositoryID         string         `json:"repository_id"`
	SessionID            string         `json:"session_id"`
	TurnID               string         `json:"turn_id"`
	Provider             string         `json:"provider"`
	Kind                 string         `json:"kind"`
	TranscriptRef        sql.NullString `json:"transcript_ref"`
	ProvenanceBundleHash sql.NullString `json:"provenance_bundle_hash"`
	StartedAt            int64          `json:"started_at"`
	CompletedAt          sql.NullInt64  `json:"completed_at"`
	Status               string         `json:"status"`
	CreatedAt            int64          `json:"created_at"`
	UpdatedAt            int64          `json:"updated_at"`
}

func (q *Queries) UpsertProvenanceManifest(ctx context.Context, arg UpsertProvenanceManifestParams) error {
	_, err := q.exec(ctx, q.upsertProvenanceManifestStmt, upsertProvenanceManifest,
		arg.ManifestID,
		arg.RepositoryID,
		arg.SessionID,
		arg.TurnID,
		arg.Provider,
		arg.Kind,
		arg.TranscriptRef,
		arg.ProvenanceBundleHash,
		arg.StartedAt,
		arg.CompletedAt,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
