// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: backfill.sql

package db

import (
	"context"
	"database/sql"
)

const advanceBackfillCursor = `-- name: AdvanceBackfillCursor :exec
update remote_attribution_backfills set
    cursor_linked_at = ?,
    cursor_commit_hash = ?,
    failed_commit_hash = null,
    retry_attempts = 0,
    last_error = null,
    updated_at = ?
where connected_repo_id = ?
`

type AdvanceBackfillCursorParams struct {
	CursorLinkedAt   int64  `json:"cursor_linked_at"`
	CursorCommitHash string `json:"cursor_commit_hash"`
	UpdatedAt        int64  `json:"updated_at"`
	ConnectedRepoID  string `json:"connected_repo_id"`
}

// Advances the cursor past a successfully pushed or skipped commit.
// Also clears any failure state since the head-of-line commit moved.
func (q *Queries) AdvanceBackfillCursor(ctx context.Context, arg AdvanceBackfillCursorParams) error {
	_, err := q.exec(ctx, q.advanceBackfillCursorStmt, advanceBackfillCursor,
		arg.CursorLinkedAt,
		arg.CursorCommitHash,
		arg.UpdatedAt,
		arg.ConnectedRepoID,
	)
	return err
}

const completeBackfill = `-- name: CompleteBackfill :exec
update remote_attribution_backfills set
    status = 'complete',
    failed_commit_hash = null,
    retry_attempts = 0,
    last_error = null,
    updated_at = ?
where connected_repo_id = ?
`

type CompleteBackfillParams struct {
	UpdatedAt       int64  `json:"updated_at"`
	ConnectedRepoID string `json:"connected_repo_id"`
}

func (q *Queries) CompleteBackfill(ctx context.Context, arg CompleteBackfillParams) error {
	_, err := q.exec(ctx, q.completeBackfillStmt, completeBackfill, arg.UpdatedAt, arg.ConnectedRepoID)
	return err
}

const getAttributionBackfill = `-- name: GetAttributionBackfill :one
select connected_repo_id, repository_id, cutoff_linked_at, cutoff_commit_hash, cursor_linked_at, cursor_commit_hash, status, failed_commit_hash, retry_attempts, last_error, updated_at from remote_attribution_backfills where connected_repo_id = ?
`

func (q *Queries) GetAttributionBackfill(ctx context.Context, connectedRepoID string) (RemoteAttributionBackfill, error) {
	row := q.queryRow(ctx, q.getAttributionBackfillStmt, getAttributionBackfill, connectedRepoID)
	var i RemoteAttributionBackfill
	err := row.Scan(
		&i.ConnectedRepoID,
		&i.RepositoryID,
		&i.CutoffLinkedAt,
		&i.CutoffCommitHash,
		&i.CursorLinkedAt,
		&i.CursorCommitHash,
		&i.Status,
		&i.FailedCommitHash,
		&i.RetryAttempts,
		&i.LastError,
		&i.UpdatedAt,
	)
	return i, err
}

const getLatestCommitLink = `-- name: GetLatestCommitLink :one
select commit_hash, linked_at
from commit_links
where repository_id = ?
order by linked_at desc, commit_hash desc
limit 1
`

type GetLatestCommitLinkRow struct {
	CommitHash string `json:"commit_hash"`
	LinkedAt   int64  `json:"linked_at"`
}

// Returns the most recent commit link for a repository. Used to snapshot
// the backfill cutoff at connect time.
func (q *Queries) GetLatestCommitLink(ctx context.Context, repositoryID string) (GetLatestCommitLinkRow, error) {
	row := q.queryRow(ctx, q.getLatestCommitLinkStmt, getLatestCommitLink, repositoryID)
	var i GetLatestCommitLinkRow
	err := row.Scan(&i.CommitHash, &i.LinkedAt)
	return i, err
}

const listBackfillReplayCandidates = `-- name: ListBackfillReplayCandidates :many
select cl.commit_hash, cl.checkpoint_id, cl.linked_at
from commit_links cl
where cl.repository_id = ?1
  and (
    cl.linked_at > ?2
    or (cl.linked_at = ?2 and cl.commit_hash > ?3)
  )
  and (
    cl.linked_at < ?4
    or (cl.linked_at = ?4 and cl.commit_hash <= ?5)
  )
order by cl.linked_at asc, cl.commit_hash asc
limit ?6
`

type ListBackfillReplayCandidatesParams struct {
	RepositoryID     string `json:"repository_id"`
	CursorLinkedAt   int64  `json:"cursor_linked_at"`
	CursorCommitHash string `json:"cursor_commit_hash"`
	CutoffLinkedAt   int64  `json:"cutoff_linked_at"`
	CutoffCommitHash string `json:"cutoff_commit_hash"`
	BatchLimit       int64  `json:"batch_limit"`
}

type ListBackfillReplayCandidatesRow struct {
	CommitHash   string `json:"commit_hash"`
	CheckpointID string `json:"checkpoint_id"`
	LinkedAt     int64  `json:"linked_at"`
}

// Returns the next batch of commit links eligible for replay, ordered
// oldest-first. Uses (linked_at, commit_hash) tuple comparison for
// deterministic cursor-based pagination.
func (q *Queries) ListBackfillReplayCandidates(ctx context.Context, arg ListBackfillReplayCandidatesParams) ([]ListBackfillReplayCandidatesRow, error) {
	rows, err := q.query(ctx, q.listBackfillReplayCandidatesStmt, listBackfillReplayCandidates,
		arg.RepositoryID,
		arg.CursorLinkedAt,
		arg.CursorCommitHash,
		arg.CutoffLinkedAt,
		arg.CutoffCommitHash,
		arg.BatchLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBackfillReplayCandidatesRow{}
	for rows.Next() {
		var i ListBackfillReplayCandidatesRow
		if err := rows.Scan(&i.CommitHash, &i.CheckpointID, &i.LinkedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordBackfillFailure = `-- name: RecordBackfillFailure :exec
update remote_attribution_backfills set
    failed_commit_hash = ?,
    retry_attempts = retry_attempts + 1,
    last_error = ?,
    updated_at = ?
where connected_repo_id = ?
`

type RecordBackfillFailureParams struct {
	FailedCommitHash sql.NullString `json:"failed_commit_hash"`
	LastError        sql.NullString `json:"last_error"`
	UpdatedAt        int64          `json:"updated_at"`
	ConnectedRepoID  string         `json:"connected_repo_id"`
}

// Records a retryable failure on the current head-of-line commit.
func (q *Queries) RecordBackfillFailure(ctx context.Context, arg RecordBackfillFailureParams) error {
	_, err := q.exec(ctx, q.recordBackfillFailureStmt, recordBackfillFailure,
		arg.FailedCommitHash,
		arg.LastError,
		arg.UpdatedAt,
		arg.ConnectedRepoID,
	)
	return err
}

const upsertAttributionBackfill = `-- name: UpsertAttributionBackfill :exec
insert into remote_attribution_backfills (
    connected_repo_id, repository_id,
    cutoff_linked_at, cutoff_commit_hash,
    cursor_linked_at, cursor_commit_hash,
    status, updated_at
) values (?, ?, ?, ?, 0, '', 'pending', ?)
on conflict(connected_repo_id) do update set
    cutoff_linked_at = case
        when excluded.cutoff_linked_at > remote_attribution_backfills.cutoff_linked_at
            or (excluded.cutoff_linked_at = remote_attribution_backfills.cutoff_linked_at
                and excluded.cutoff_commit_hash > remote_attribution_backfills.cutoff_commit_hash)
        then excluded.cutoff_linked_at
        else remote_attribution_backfills.cutoff_linked_at
    end,
    cutoff_commit_hash = case
        when excluded.cutoff_linked_at > remote_attribution_backfills.cutoff_linked_at
            or (excluded.cutoff_linked_at = remote_attribution_backfills.cutoff_linked_at
                and excluded.cutoff_commit_hash > remote_attribution_backfills.cutoff_commit_hash)
        then excluded.cutoff_commit_hash
        else remote_attribution_backfills.cutoff_commit_hash
    end,
    status = case
        when remote_attribution_backfills.status = 'complete'
            and (excluded.cutoff_linked_at > remote_attribution_backfills.cutoff_linked_at
                or (excluded.cutoff_linked_at = remote_attribution_backfills.cutoff_linked_at
                    and excluded.cutoff_commit_hash > remote_attribution_backfills.cutoff_commit_hash))
        then 'pending'
        else remote_attribution_backfills.status
    end,
    updated_at = excluded.updated_at
`

type UpsertAttributionBackfillParams struct {
	ConnectedRepoID  string `json:"connected_repo_id"`
	RepositoryID     string `json:"repository_id"`
	CutoffLinkedAt   int64  `json:"cutoff_linked_at"`
	CutoffCommitHash string `json:"cutoff_commit_hash"`
	UpdatedAt        int64  `json:"updated_at"`
}

// Initializes replay state for a connected repo binding. If the row already
// exists, extends the cutoff if the new cutoff is newer (never shrinks).
func (q *Queries) UpsertAttributionBackfill(ctx context.Context, arg UpsertAttributionBackfillParams) error {
	_, err := q.exec(ctx, q.upsertAttributionBackfillStmt, upsertAttributionBackfill,
		arg.ConnectedRepoID,
		arg.RepositoryID,
		arg.CutoffLinkedAt,
		arg.CutoffCommitHash,
		arg.UpdatedAt,
	)
	return err
}
