// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: capture_group.sql

package db

import (
	"context"
	"database/sql"
)

const listCaptureGroupLinks = `-- name: ListCaptureGroupLinks :many
select l.event_id, l.evidence_hash, s.provider, e.session_id, e.turn_id
from agent_event_evidence_links l
join agent_events e on e.event_id = l.event_id
join agent_sessions s on s.session_id = e.session_id and s.repository_id = e.repository_id
where l.group_id = ? and l.evidence_kind = 'tool_delta' and e.repository_id = ?
order by l.event_id
`

type ListCaptureGroupLinksParams struct {
	GroupID      string `json:"group_id"`
	RepositoryID string `json:"repository_id"`
}

type ListCaptureGroupLinksRow struct {
	EventID      string         `json:"event_id"`
	EvidenceHash string         `json:"evidence_hash"`
	Provider     string         `json:"provider"`
	SessionID    string         `json:"session_id"`
	TurnID       sql.NullString `json:"turn_id"`
}

// Validate full group membership independently of the attribution window.
func (q *Queries) ListCaptureGroupLinks(ctx context.Context, arg ListCaptureGroupLinksParams) ([]ListCaptureGroupLinksRow, error) {
	rows, err := q.query(ctx, q.listCaptureGroupLinksStmt, listCaptureGroupLinks, arg.GroupID, arg.RepositoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCaptureGroupLinksRow{}
	for rows.Next() {
		var i ListCaptureGroupLinksRow
		if err := rows.Scan(
			&i.EventID,
			&i.EvidenceHash,
			&i.Provider,
			&i.SessionID,
			&i.TurnID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
