// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: capture_readiness.sql

package db

import (
	"context"
	"database/sql"
)

const getCheckpointCapture = `-- name: GetCheckpointCapture :one
select record_json from checkpoint_capture where checkpoint_id = ?
`

func (q *Queries) GetCheckpointCapture(ctx context.Context, checkpointID string) (string, error) {
	row := q.queryRow(ctx, q.getCheckpointCaptureStmt, getCheckpointCapture, checkpointID)
	var record_json string
	err := row.Scan(&record_json)
	return record_json, err
}

const releaseCheckpointForCapture = `-- name: ReleaseCheckpointForCapture :execrows
update checkpoints set
    last_error = ?, next_attempt_at = ?, attempt_count = max(0, attempt_count - 1),
    lease_owner = null, lease_until = null
where checkpoint_id = ? and lease_owner = ? and status = 'pending'
`

type ReleaseCheckpointForCaptureParams struct {
	LastError     sql.NullString `json:"last_error"`
	NextAttemptAt int64          `json:"next_attempt_at"`
	CheckpointID  string         `json:"checkpoint_id"`
	LeaseOwner    sql.NullString `json:"lease_owner"`
}

// Capture waits release the claim without spending a processing attempt.
func (q *Queries) ReleaseCheckpointForCapture(ctx context.Context, arg ReleaseCheckpointForCaptureParams) (int64, error) {
	result, err := q.exec(ctx, q.releaseCheckpointForCaptureStmt, releaseCheckpointForCapture,
		arg.LastError,
		arg.NextAttemptAt,
		arg.CheckpointID,
		arg.LeaseOwner,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const saveCheckpointCapture = `-- name: SaveCheckpointCapture :exec
insert into checkpoint_capture(checkpoint_id, record_json) values (?, ?)
on conflict(checkpoint_id) do update set record_json = excluded.record_json
`

type SaveCheckpointCaptureParams struct {
	CheckpointID string `json:"checkpoint_id"`
	RecordJson   string `json:"record_json"`
}

func (q *Queries) SaveCheckpointCapture(ctx context.Context, arg SaveCheckpointCaptureParams) error {
	_, err := q.exec(ctx, q.saveCheckpointCaptureStmt, saveCheckpointCapture, arg.CheckpointID, arg.RecordJson)
	return err
}
