// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: checkpoints.sql

package db

import (
	"context"
	"database/sql"
)

const completeCheckpoint = `-- name: CompleteCheckpoint :exec
update checkpoints
set manifest_hash = ?, size_bytes = ?, status = 'complete', completed_at = ?
where checkpoint_id = ?
`

type CompleteCheckpointParams struct {
	ManifestHash sql.NullString `json:"manifest_hash"`
	SizeBytes    sql.NullInt64  `json:"size_bytes"`
	CompletedAt  sql.NullInt64  `json:"completed_at"`
	CheckpointID string         `json:"checkpoint_id"`
}

func (q *Queries) CompleteCheckpoint(ctx context.Context, arg CompleteCheckpointParams) error {
	_, err := q.exec(ctx, q.completeCheckpointStmt, completeCheckpoint,
		arg.ManifestHash,
		arg.SizeBytes,
		arg.CompletedAt,
		arg.CheckpointID,
	)
	return err
}

const countCheckpointsWithSummary = `-- name: CountCheckpointsWithSummary :one
select cast(count(*) as integer) from checkpoints
where repository_id = ? and status = 'complete' and summary_json is not null
`

func (q *Queries) CountCheckpointsWithSummary(ctx context.Context, repositoryID string) (int64, error) {
	row := q.queryRow(ctx, q.countCheckpointsWithSummaryStmt, countCheckpointsWithSummary, repositoryID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countSessionsForCheckpoint = `-- name: CountSessionsForCheckpoint :one
select count(*) from session_checkpoints where checkpoint_id = ?
`

func (q *Queries) CountSessionsForCheckpoint(ctx context.Context, checkpointID string) (int64, error) {
	row := q.queryRow(ctx, q.countSessionsForCheckpointStmt, countSessionsForCheckpoint, checkpointID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteCheckpointByID = `-- name: DeleteCheckpointByID :exec
delete from checkpoints where checkpoint_id = ?
`

func (q *Queries) DeleteCheckpointByID(ctx context.Context, checkpointID string) error {
	_, err := q.exec(ctx, q.deleteCheckpointByIDStmt, deleteCheckpointByID, checkpointID)
	return err
}

const failCheckpoint = `-- name: FailCheckpoint :exec
update checkpoints
set status = 'failed', completed_at = ?
where checkpoint_id = ?
`

type FailCheckpointParams struct {
	CompletedAt  sql.NullInt64 `json:"completed_at"`
	CheckpointID string        `json:"checkpoint_id"`
}

func (q *Queries) FailCheckpoint(ctx context.Context, arg FailCheckpointParams) error {
	_, err := q.exec(ctx, q.failCheckpointStmt, failCheckpoint, arg.CompletedAt, arg.CheckpointID)
	return err
}

const getCheckpointByID = `-- name: GetCheckpointByID :one
select checkpoint_id, repository_id, created_at, kind, "trigger", message, manifest_hash, size_bytes, status, completed_at, summary_json, summary_model from checkpoints where checkpoint_id = ?
`

func (q *Queries) GetCheckpointByID(ctx context.Context, checkpointID string) (Checkpoint, error) {
	row := q.queryRow(ctx, q.getCheckpointByIDStmt, getCheckpointByID, checkpointID)
	var i Checkpoint
	err := row.Scan(
		&i.CheckpointID,
		&i.RepositoryID,
		&i.CreatedAt,
		&i.Kind,
		&i.Trigger,
		&i.Message,
		&i.ManifestHash,
		&i.SizeBytes,
		&i.Status,
		&i.CompletedAt,
		&i.SummaryJson,
		&i.SummaryModel,
	)
	return i, err
}

const getCheckpointStats = `-- name: GetCheckpointStats :one
select checkpoint_id, session_count, files_changed, ai_percentage from checkpoint_stats where checkpoint_id = ?
`

func (q *Queries) GetCheckpointStats(ctx context.Context, checkpointID string) (CheckpointStat, error) {
	row := q.queryRow(ctx, q.getCheckpointStatsStmt, getCheckpointStats, checkpointID)
	var i CheckpointStat
	err := row.Scan(
		&i.CheckpointID,
		&i.SessionCount,
		&i.FilesChanged,
		&i.AiPercentage,
	)
	return i, err
}

const getCheckpointSummary = `-- name: GetCheckpointSummary :one
select checkpoint_id, summary_json, summary_model from checkpoints
where checkpoint_id = ? and summary_json is not null
`

type GetCheckpointSummaryRow struct {
	CheckpointID string         `json:"checkpoint_id"`
	SummaryJson  sql.NullString `json:"summary_json"`
	SummaryModel sql.NullString `json:"summary_model"`
}

func (q *Queries) GetCheckpointSummary(ctx context.Context, checkpointID string) (GetCheckpointSummaryRow, error) {
	row := q.queryRow(ctx, q.getCheckpointSummaryStmt, getCheckpointSummary, checkpointID)
	var i GetCheckpointSummaryRow
	err := row.Scan(&i.CheckpointID, &i.SummaryJson, &i.SummaryModel)
	return i, err
}

const getLatestCheckpointForRepo = `-- name: GetLatestCheckpointForRepo :one
select checkpoint_id, repository_id, created_at, kind, "trigger", message, manifest_hash, size_bytes, status, completed_at, summary_json, summary_model from checkpoints where repository_id = ? order by created_at desc limit 1
`

func (q *Queries) GetLatestCheckpointForRepo(ctx context.Context, repositoryID string) (Checkpoint, error) {
	row := q.queryRow(ctx, q.getLatestCheckpointForRepoStmt, getLatestCheckpointForRepo, repositoryID)
	var i Checkpoint
	err := row.Scan(
		&i.CheckpointID,
		&i.RepositoryID,
		&i.CreatedAt,
		&i.Kind,
		&i.Trigger,
		&i.Message,
		&i.ManifestHash,
		&i.SizeBytes,
		&i.Status,
		&i.CompletedAt,
		&i.SummaryJson,
		&i.SummaryModel,
	)
	return i, err
}

const getPreviousCommitLinkedCheckpoint = `-- name: GetPreviousCommitLinkedCheckpoint :one
select c.checkpoint_id, c.repository_id, c.created_at, c.kind, c."trigger", c.message, c.manifest_hash, c.size_bytes, c.status, c.completed_at, c.summary_json, c.summary_model from checkpoints c
    join commit_links cl on cl.checkpoint_id = c.checkpoint_id
where c.repository_id = ?
  and c.status = 'complete'
  and c.created_at < ?
order by c.created_at desc
limit 1
`

type GetPreviousCommitLinkedCheckpointParams struct {
	RepositoryID string `json:"repository_id"`
	CreatedAt    int64  `json:"created_at"`
}

// Returns the most recent completed checkpoint before the given timestamp
// that has an associated commit link. Used by attribution to anchor the
// delta window to the previous commit rather than an intermediate manual
// or baseline checkpoint.
func (q *Queries) GetPreviousCommitLinkedCheckpoint(ctx context.Context, arg GetPreviousCommitLinkedCheckpointParams) (Checkpoint, error) {
	row := q.queryRow(ctx, q.getPreviousCommitLinkedCheckpointStmt, getPreviousCommitLinkedCheckpoint, arg.RepositoryID, arg.CreatedAt)
	var i Checkpoint
	err := row.Scan(
		&i.CheckpointID,
		&i.RepositoryID,
		&i.CreatedAt,
		&i.Kind,
		&i.Trigger,
		&i.Message,
		&i.ManifestHash,
		&i.SizeBytes,
		&i.Status,
		&i.CompletedAt,
		&i.SummaryJson,
		&i.SummaryModel,
	)
	return i, err
}

const getPreviousCompletedCheckpoint = `-- name: GetPreviousCompletedCheckpoint :one
select checkpoint_id, repository_id, created_at, kind, "trigger", message, manifest_hash, size_bytes, status, completed_at, summary_json, summary_model from checkpoints
where repository_id = ?
  and status = 'complete'
  and manifest_hash is not null
  and created_at < ?
order by created_at desc
limit 1
`

type GetPreviousCompletedCheckpointParams struct {
	RepositoryID string `json:"repository_id"`
	CreatedAt    int64  `json:"created_at"`
}

func (q *Queries) GetPreviousCompletedCheckpoint(ctx context.Context, arg GetPreviousCompletedCheckpointParams) (Checkpoint, error) {
	row := q.queryRow(ctx, q.getPreviousCompletedCheckpointStmt, getPreviousCompletedCheckpoint, arg.RepositoryID, arg.CreatedAt)
	var i Checkpoint
	err := row.Scan(
		&i.CheckpointID,
		&i.RepositoryID,
		&i.CreatedAt,
		&i.Kind,
		&i.Trigger,
		&i.Message,
		&i.ManifestHash,
		&i.SizeBytes,
		&i.Status,
		&i.CompletedAt,
		&i.SummaryJson,
		&i.SummaryModel,
	)
	return i, err
}

const insertCheckpoint = `-- name: InsertCheckpoint :exec
insert into checkpoints(
    checkpoint_id, repository_id, created_at, kind, trigger, message,
    manifest_hash, size_bytes, status, completed_at
) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertCheckpointParams struct {
	CheckpointID string         `json:"checkpoint_id"`
	RepositoryID string         `json:"repository_id"`
	CreatedAt    int64          `json:"created_at"`
	Kind         string         `json:"kind"`
	Trigger      sql.NullString `json:"trigger"`
	Message      sql.NullString `json:"message"`
	ManifestHash sql.NullString `json:"manifest_hash"`
	SizeBytes    sql.NullInt64  `json:"size_bytes"`
	Status       string         `json:"status"`
	CompletedAt  sql.NullInt64  `json:"completed_at"`
}

func (q *Queries) InsertCheckpoint(ctx context.Context, arg InsertCheckpointParams) error {
	_, err := q.exec(ctx, q.insertCheckpointStmt, insertCheckpoint,
		arg.CheckpointID,
		arg.RepositoryID,
		arg.CreatedAt,
		arg.Kind,
		arg.Trigger,
		arg.Message,
		arg.ManifestHash,
		arg.SizeBytes,
		arg.Status,
		arg.CompletedAt,
	)
	return err
}

const listCheckpointsByRepository = `-- name: ListCheckpointsByRepository :many
select checkpoint_id, repository_id, created_at, kind, "trigger", message, manifest_hash, size_bytes, status, completed_at, summary_json, summary_model from checkpoints where repository_id = ? order by created_at desc limit ?
`

type ListCheckpointsByRepositoryParams struct {
	RepositoryID string `json:"repository_id"`
	Limit        int64  `json:"limit"`
}

func (q *Queries) ListCheckpointsByRepository(ctx context.Context, arg ListCheckpointsByRepositoryParams) ([]Checkpoint, error) {
	rows, err := q.query(ctx, q.listCheckpointsByRepositoryStmt, listCheckpointsByRepository, arg.RepositoryID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Checkpoint{}
	for rows.Next() {
		var i Checkpoint
		if err := rows.Scan(
			&i.CheckpointID,
			&i.RepositoryID,
			&i.CreatedAt,
			&i.Kind,
			&i.Trigger,
			&i.Message,
			&i.ManifestHash,
			&i.SizeBytes,
			&i.Status,
			&i.CompletedAt,
			&i.SummaryJson,
			&i.SummaryModel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCheckpointsWithCommit = `-- name: ListCheckpointsWithCommit :many
select c.checkpoint_id, c.created_at, c.kind, c.trigger, c.message,
       c.size_bytes, c.status, c.completed_at, cl.commit_hash, c.manifest_hash
from checkpoints c
    left join commit_links cl on cl.checkpoint_id = c.checkpoint_id
where c.repository_id = ?
order by c.created_at desc limit ?
`

type ListCheckpointsWithCommitParams struct {
	RepositoryID string `json:"repository_id"`
	Limit        int64  `json:"limit"`
}

type ListCheckpointsWithCommitRow struct {
	CheckpointID string         `json:"checkpoint_id"`
	CreatedAt    int64          `json:"created_at"`
	Kind         string         `json:"kind"`
	Trigger      sql.NullString `json:"trigger"`
	Message      sql.NullString `json:"message"`
	SizeBytes    sql.NullInt64  `json:"size_bytes"`
	Status       string         `json:"status"`
	CompletedAt  sql.NullInt64  `json:"completed_at"`
	CommitHash   sql.NullString `json:"commit_hash"`
	ManifestHash sql.NullString `json:"manifest_hash"`
}

func (q *Queries) ListCheckpointsWithCommit(ctx context.Context, arg ListCheckpointsWithCommitParams) ([]ListCheckpointsWithCommitRow, error) {
	rows, err := q.query(ctx, q.listCheckpointsWithCommitStmt, listCheckpointsWithCommit, arg.RepositoryID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCheckpointsWithCommitRow{}
	for rows.Next() {
		var i ListCheckpointsWithCommitRow
		if err := rows.Scan(
			&i.CheckpointID,
			&i.CreatedAt,
			&i.Kind,
			&i.Trigger,
			&i.Message,
			&i.SizeBytes,
			&i.Status,
			&i.CompletedAt,
			&i.CommitHash,
			&i.ManifestHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentAIPercentages = `-- name: ListRecentAIPercentages :many
select cs.checkpoint_id, cs.ai_percentage, c.created_at, cl.commit_hash
from checkpoint_stats cs
    join checkpoints c on c.checkpoint_id = cs.checkpoint_id
    join commit_links cl on cl.checkpoint_id = cs.checkpoint_id
where c.repository_id = ? and cs.ai_percentage >= 0
order by c.created_at desc
limit ?
`

type ListRecentAIPercentagesParams struct {
	RepositoryID string `json:"repository_id"`
	Limit        int64  `json:"limit"`
}

type ListRecentAIPercentagesRow struct {
	CheckpointID string  `json:"checkpoint_id"`
	AiPercentage float64 `json:"ai_percentage"`
	CreatedAt    int64   `json:"created_at"`
	CommitHash   string  `json:"commit_hash"`
}

func (q *Queries) ListRecentAIPercentages(ctx context.Context, arg ListRecentAIPercentagesParams) ([]ListRecentAIPercentagesRow, error) {
	rows, err := q.query(ctx, q.listRecentAIPercentagesStmt, listRecentAIPercentages, arg.RepositoryID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecentAIPercentagesRow{}
	for rows.Next() {
		var i ListRecentAIPercentagesRow
		if err := rows.Scan(
			&i.CheckpointID,
			&i.AiPercentage,
			&i.CreatedAt,
			&i.CommitHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStalePendingCheckpoints = `-- name: ListStalePendingCheckpoints :many
select c.checkpoint_id, c.created_at from checkpoints c
    left join commit_links cl on cl.checkpoint_id = c.checkpoint_id
where c.repository_id = ?
  and c.status = 'pending'
  and c.manifest_hash is null
  and cl.commit_hash is null
  and c.created_at < ?2
`

type ListStalePendingCheckpointsParams struct {
	RepositoryID string `json:"repository_id"`
	BeforeTs     int64  `json:"before_ts"`
}

type ListStalePendingCheckpointsRow struct {
	CheckpointID string `json:"checkpoint_id"`
	CreatedAt    int64  `json:"created_at"`
}

// Returns pending checkpoints older than the given threshold that have
// no manifest and no commit link. Used by tidy to mark abandoned checkpoints
// as failed.
func (q *Queries) ListStalePendingCheckpoints(ctx context.Context, arg ListStalePendingCheckpointsParams) ([]ListStalePendingCheckpointsRow, error) {
	rows, err := q.query(ctx, q.listStalePendingCheckpointsStmt, listStalePendingCheckpoints, arg.RepositoryID, arg.BeforeTs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStalePendingCheckpointsRow{}
	for rows.Next() {
		var i ListStalePendingCheckpointsRow
		if err := rows.Scan(&i.CheckpointID, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveCheckpointByPrefix = `-- name: ResolveCheckpointByPrefix :many
select checkpoint_id from checkpoints
where checkpoint_id like ? and repository_id = ?
limit 2
`

type ResolveCheckpointByPrefixParams struct {
	CheckpointID string `json:"checkpoint_id"`
	RepositoryID string `json:"repository_id"`
}

func (q *Queries) ResolveCheckpointByPrefix(ctx context.Context, arg ResolveCheckpointByPrefixParams) ([]string, error) {
	rows, err := q.query(ctx, q.resolveCheckpointByPrefixStmt, resolveCheckpointByPrefix, arg.CheckpointID, arg.RepositoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var checkpoint_id string
		if err := rows.Scan(&checkpoint_id); err != nil {
			return nil, err
		}
		items = append(items, checkpoint_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveCheckpointSummary = `-- name: SaveCheckpointSummary :exec
update checkpoints
set summary_json = ?, summary_model = ?
where checkpoint_id = ?
`

type SaveCheckpointSummaryParams struct {
	SummaryJson  sql.NullString `json:"summary_json"`
	SummaryModel sql.NullString `json:"summary_model"`
	CheckpointID string         `json:"checkpoint_id"`
}

func (q *Queries) SaveCheckpointSummary(ctx context.Context, arg SaveCheckpointSummaryParams) error {
	_, err := q.exec(ctx, q.saveCheckpointSummaryStmt, saveCheckpointSummary, arg.SummaryJson, arg.SummaryModel, arg.CheckpointID)
	return err
}

const updateCheckpointAIPercentage = `-- name: UpdateCheckpointAIPercentage :exec
update checkpoint_stats set ai_percentage = ? where checkpoint_id = ?
`

type UpdateCheckpointAIPercentageParams struct {
	AiPercentage float64 `json:"ai_percentage"`
	CheckpointID string  `json:"checkpoint_id"`
}

func (q *Queries) UpdateCheckpointAIPercentage(ctx context.Context, arg UpdateCheckpointAIPercentageParams) error {
	_, err := q.exec(ctx, q.updateCheckpointAIPercentageStmt, updateCheckpointAIPercentage, arg.AiPercentage, arg.CheckpointID)
	return err
}

const upsertCheckpointStats = `-- name: UpsertCheckpointStats :exec
insert into checkpoint_stats (
    checkpoint_id, session_count, files_changed
) values (?, ?, ?)
on conflict(checkpoint_id) do update set
    session_count=excluded.session_count,
    files_changed=excluded.files_changed
`

type UpsertCheckpointStatsParams struct {
	CheckpointID string `json:"checkpoint_id"`
	SessionCount int64  `json:"session_count"`
	FilesChanged int64  `json:"files_changed"`
}

func (q *Queries) UpsertCheckpointStats(ctx context.Context, arg UpsertCheckpointStatsParams) error {
	_, err := q.exec(ctx, q.upsertCheckpointStatsStmt, upsertCheckpointStats, arg.CheckpointID, arg.SessionCount, arg.FilesChanged)
	return err
}
