// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: checkpoints.sql

package db

import (
	"context"
	"database/sql"
)

const claimCheckpoint = `-- name: ClaimCheckpoint :one
update checkpoints
set lease_owner = ?1,
    lease_until = ?2,
    attempt_count = attempt_count + 1
where checkpoint_id = ?3
  and status = 'pending'
  and next_attempt_at <= ?4
  and (lease_owner is null or lease_until < ?4)
returning checkpoint_id, repository_id, created_at, kind, "trigger", message, manifest_hash, size_bytes, status, completed_at, summary_json, summary_model, repository_sequence, event_cursor, attempt_count, last_error, next_attempt_at, lease_owner, lease_until
`

type ClaimCheckpointParams struct {
	LeaseOwner   sql.NullString `json:"lease_owner"`
	LeaseUntil   sql.NullInt64  `json:"lease_until"`
	CheckpointID string         `json:"checkpoint_id"`
	Now          int64          `json:"now"`
}

// Atomic claim: takes a due pending checkpoint whose lease is free or
// expired and increments attempt_count exactly once. A live lease on a
// pending row represents processing. Returns no row when unavailable.
func (q *Queries) ClaimCheckpoint(ctx context.Context, arg ClaimCheckpointParams) (Checkpoint, error) {
	row := q.queryRow(ctx, q.claimCheckpointStmt, claimCheckpoint,
		arg.LeaseOwner,
		arg.LeaseUntil,
		arg.CheckpointID,
		arg.Now,
	)
	var i Checkpoint
	err := row.Scan(
		&i.CheckpointID,
		&i.RepositoryID,
		&i.CreatedAt,
		&i.Kind,
		&i.Trigger,
		&i.Message,
		&i.ManifestHash,
		&i.SizeBytes,
		&i.Status,
		&i.CompletedAt,
		&i.SummaryJson,
		&i.SummaryModel,
		&i.RepositorySequence,
		&i.EventCursor,
		&i.AttemptCount,
		&i.LastError,
		&i.NextAttemptAt,
		&i.LeaseOwner,
		&i.LeaseUntil,
	)
	return i, err
}

const completeCheckpoint = `-- name: CompleteCheckpoint :exec
update checkpoints
set manifest_hash = ?, size_bytes = ?, status = 'complete', completed_at = ?,
    lease_owner = null, lease_until = null, last_error = null, next_attempt_at = 0
where checkpoint_id = ?
`

type CompleteCheckpointParams struct {
	ManifestHash sql.NullString `json:"manifest_hash"`
	SizeBytes    sql.NullInt64  `json:"size_bytes"`
	CompletedAt  sql.NullInt64  `json:"completed_at"`
	CheckpointID string         `json:"checkpoint_id"`
}

func (q *Queries) CompleteCheckpoint(ctx context.Context, arg CompleteCheckpointParams) error {
	_, err := q.exec(ctx, q.completeCheckpointStmt, completeCheckpoint,
		arg.ManifestHash,
		arg.SizeBytes,
		arg.CompletedAt,
		arg.CheckpointID,
	)
	return err
}

const countCheckpointsWithSummary = `-- name: CountCheckpointsWithSummary :one
select cast(count(*) as integer) from checkpoints
where repository_id = ? and status = 'complete' and summary_json is not null
`

func (q *Queries) CountCheckpointsWithSummary(ctx context.Context, repositoryID string) (int64, error) {
	row := q.queryRow(ctx, q.countCheckpointsWithSummaryStmt, countCheckpointsWithSummary, repositoryID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countSessionsForCheckpoint = `-- name: CountSessionsForCheckpoint :one
select count(*) from session_checkpoints where checkpoint_id = ?
`

func (q *Queries) CountSessionsForCheckpoint(ctx context.Context, checkpointID string) (int64, error) {
	row := q.queryRow(ctx, q.countSessionsForCheckpointStmt, countSessionsForCheckpoint, checkpointID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countWindowTurnProvenance = `-- name: CountWindowTurnProvenance :one
select
    cast(count(distinct e.turn_id) as integer) as total_turns,
    cast(count(distinct case when ok.turn_id is not null then e.turn_id end) as integer) as packaged_turns,
    cast(count(distinct case when up.turn_id is not null then e.turn_id end) as integer) as uploaded_turns,
    cast(count(distinct case when fl.turn_id is not null then e.turn_id end) as integer) as failed_upload_turns
from agent_events e
    left join provenance_manifests ok
        on ok.repository_id = e.repository_id
        and ok.session_id = e.session_id
        and ok.turn_id = e.turn_id
        and ok.kind = 'turn_bundle'
        and coalesce(ok.provenance_bundle_hash, '') != ''
    left join provenance_manifests up
        on up.repository_id = e.repository_id
        and up.session_id = e.session_id
        and up.turn_id = e.turn_id
        and up.kind = 'turn_bundle'
        and coalesce(up.provenance_bundle_hash, '') != ''
        and up.status = 'uploaded'
    left join provenance_manifests fl
        on fl.repository_id = e.repository_id
        and fl.session_id = e.session_id
        and fl.turn_id = e.turn_id
        and fl.kind = 'turn_bundle'
        and coalesce(fl.provenance_bundle_hash, '') != ''
        and fl.status = 'failed'
where e.repository_id = ?
  and e.turn_id is not null
  and ((cast(?2 as integer) = 1
          and (e.ts > ?3
               or (e.ts = ?3 and e.insert_seq > ?4))
          and (e.ts < ?5
               or (e.ts = ?5 and e.insert_seq <= ?6)))
       or (cast(?2 as integer) = 0
          and e.ts > ?3 and e.ts <= ?5))
`

type CountWindowTurnProvenanceParams struct {
	RepositoryID string        `json:"repository_id"`
	UseCursor    int64         `json:"use_cursor"`
	AfterTs      int64         `json:"after_ts"`
	AfterCursor  sql.NullInt64 `json:"after_cursor"`
	UpToTs       int64         `json:"up_to_ts"`
	UpToCursor   sql.NullInt64 `json:"up_to_cursor"`
}

type CountWindowTurnProvenanceRow struct {
	TotalTurns        int64 `json:"total_turns"`
	PackagedTurns     int64 `json:"packaged_turns"`
	UploadedTurns     int64 `json:"uploaded_turns"`
	FailedUploadTurns int64 `json:"failed_upload_turns"`
}

// Counts turn bundles in the checkpoint event window. A non-empty bundle hash
// means local packaging succeeded; failed rows with a hash represent terminal
// upload failures. Joins use repository, session, turn, and kind. Window bounds
// use (ts, insert_seq).
func (q *Queries) CountWindowTurnProvenance(ctx context.Context, arg CountWindowTurnProvenanceParams) (CountWindowTurnProvenanceRow, error) {
	row := q.queryRow(ctx, q.countWindowTurnProvenanceStmt, countWindowTurnProvenance,
		arg.RepositoryID,
		arg.UseCursor,
		arg.AfterTs,
		arg.AfterCursor,
		arg.UpToTs,
		arg.UpToCursor,
	)
	var i CountWindowTurnProvenanceRow
	err := row.Scan(
		&i.TotalTurns,
		&i.PackagedTurns,
		&i.UploadedTurns,
		&i.FailedUploadTurns,
	)
	return i, err
}

const deleteCheckpointByID = `-- name: DeleteCheckpointByID :exec
delete from checkpoints where checkpoint_id = ?
`

func (q *Queries) DeleteCheckpointByID(ctx context.Context, checkpointID string) error {
	_, err := q.exec(ctx, q.deleteCheckpointByIDStmt, deleteCheckpointByID, checkpointID)
	return err
}

const failCheckpoint = `-- name: FailCheckpoint :execrows
update checkpoints
set status = 'failed', completed_at = ?, last_error = ?,
    lease_owner = null, lease_until = null, next_attempt_at = 0
where checkpoint_id = ?
`

type FailCheckpointParams struct {
	CompletedAt  sql.NullInt64  `json:"completed_at"`
	LastError    sql.NullString `json:"last_error"`
	CheckpointID string         `json:"checkpoint_id"`
}

// Terminal failure: permanent error or attempts exhausted; the final
// error is preserved for doctor and manual retry.
func (q *Queries) FailCheckpoint(ctx context.Context, arg FailCheckpointParams) (int64, error) {
	result, err := q.exec(ctx, q.failCheckpointStmt, failCheckpoint, arg.CompletedAt, arg.LastError, arg.CheckpointID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getCheckpointByID = `-- name: GetCheckpointByID :one
select checkpoint_id, repository_id, created_at, kind, "trigger", message, manifest_hash, size_bytes, status, completed_at, summary_json, summary_model, repository_sequence, event_cursor, attempt_count, last_error, next_attempt_at, lease_owner, lease_until from checkpoints where checkpoint_id = ?
`

func (q *Queries) GetCheckpointByID(ctx context.Context, checkpointID string) (Checkpoint, error) {
	row := q.queryRow(ctx, q.getCheckpointByIDStmt, getCheckpointByID, checkpointID)
	var i Checkpoint
	err := row.Scan(
		&i.CheckpointID,
		&i.RepositoryID,
		&i.CreatedAt,
		&i.Kind,
		&i.Trigger,
		&i.Message,
		&i.ManifestHash,
		&i.SizeBytes,
		&i.Status,
		&i.CompletedAt,
		&i.SummaryJson,
		&i.SummaryModel,
		&i.RepositorySequence,
		&i.EventCursor,
		&i.AttemptCount,
		&i.LastError,
		&i.NextAttemptAt,
		&i.LeaseOwner,
		&i.LeaseUntil,
	)
	return i, err
}

const getCheckpointStats = `-- name: GetCheckpointStats :one
select checkpoint_id, session_count, files_changed, ai_percentage, attribution_computed_at, attribution_pushed_at, attribution_version from checkpoint_stats where checkpoint_id = ?
`

func (q *Queries) GetCheckpointStats(ctx context.Context, checkpointID string) (CheckpointStat, error) {
	row := q.queryRow(ctx, q.getCheckpointStatsStmt, getCheckpointStats, checkpointID)
	var i CheckpointStat
	err := row.Scan(
		&i.CheckpointID,
		&i.SessionCount,
		&i.FilesChanged,
		&i.AiPercentage,
		&i.AttributionComputedAt,
		&i.AttributionPushedAt,
		&i.AttributionVersion,
	)
	return i, err
}

const getCheckpointSummary = `-- name: GetCheckpointSummary :one
select checkpoint_id, summary_json, summary_model from checkpoints
where checkpoint_id = ? and summary_json is not null
`

type GetCheckpointSummaryRow struct {
	CheckpointID string         `json:"checkpoint_id"`
	SummaryJson  sql.NullString `json:"summary_json"`
	SummaryModel sql.NullString `json:"summary_model"`
}

func (q *Queries) GetCheckpointSummary(ctx context.Context, checkpointID string) (GetCheckpointSummaryRow, error) {
	row := q.queryRow(ctx, q.getCheckpointSummaryStmt, getCheckpointSummary, checkpointID)
	var i GetCheckpointSummaryRow
	err := row.Scan(&i.CheckpointID, &i.SummaryJson, &i.SummaryModel)
	return i, err
}

const getLatestCheckpointForRepo = `-- name: GetLatestCheckpointForRepo :one
select checkpoint_id, repository_id, created_at, kind, "trigger", message, manifest_hash, size_bytes, status, completed_at, summary_json, summary_model, repository_sequence, event_cursor, attempt_count, last_error, next_attempt_at, lease_owner, lease_until from checkpoints where repository_id = ? order by repository_sequence desc limit 1
`

func (q *Queries) GetLatestCheckpointForRepo(ctx context.Context, repositoryID string) (Checkpoint, error) {
	row := q.queryRow(ctx, q.getLatestCheckpointForRepoStmt, getLatestCheckpointForRepo, repositoryID)
	var i Checkpoint
	err := row.Scan(
		&i.CheckpointID,
		&i.RepositoryID,
		&i.CreatedAt,
		&i.Kind,
		&i.Trigger,
		&i.Message,
		&i.ManifestHash,
		&i.SizeBytes,
		&i.Status,
		&i.CompletedAt,
		&i.SummaryJson,
		&i.SummaryModel,
		&i.RepositorySequence,
		&i.EventCursor,
		&i.AttemptCount,
		&i.LastError,
		&i.NextAttemptAt,
		&i.LeaseOwner,
		&i.LeaseUntil,
	)
	return i, err
}

const getMostRecentCommitLinkedCheckpoint = `-- name: GetMostRecentCommitLinkedCheckpoint :one
select c.checkpoint_id, c.repository_id, c.created_at, c.kind, c."trigger", c.message, c.manifest_hash, c.size_bytes, c.status, c.completed_at, c.summary_json, c.summary_model, c.repository_sequence, c.event_cursor, c.attempt_count, c.last_error, c.next_attempt_at, c.lease_owner, c.lease_until from checkpoints c
    join commit_links cl on cl.checkpoint_id = c.checkpoint_id
where c.repository_id = ?
  and c.status = 'complete'
order by c.repository_sequence desc
limit 1
`

// Latest completed commit-linked checkpoint by repository sequence.
func (q *Queries) GetMostRecentCommitLinkedCheckpoint(ctx context.Context, repositoryID string) (Checkpoint, error) {
	row := q.queryRow(ctx, q.getMostRecentCommitLinkedCheckpointStmt, getMostRecentCommitLinkedCheckpoint, repositoryID)
	var i Checkpoint
	err := row.Scan(
		&i.CheckpointID,
		&i.RepositoryID,
		&i.CreatedAt,
		&i.Kind,
		&i.Trigger,
		&i.Message,
		&i.ManifestHash,
		&i.SizeBytes,
		&i.Status,
		&i.CompletedAt,
		&i.SummaryJson,
		&i.SummaryModel,
		&i.RepositorySequence,
		&i.EventCursor,
		&i.AttemptCount,
		&i.LastError,
		&i.NextAttemptAt,
		&i.LeaseOwner,
		&i.LeaseUntil,
	)
	return i, err
}

const getPreviousCommitLinkedCheckpoint = `-- name: GetPreviousCommitLinkedCheckpoint :one
select c.checkpoint_id, c.repository_id, c.created_at, c.kind, c."trigger", c.message, c.manifest_hash, c.size_bytes, c.status, c.completed_at, c.summary_json, c.summary_model, c.repository_sequence, c.event_cursor, c.attempt_count, c.last_error, c.next_attempt_at, c.lease_owner, c.lease_until from checkpoints c
    join commit_links cl on cl.checkpoint_id = c.checkpoint_id
where c.repository_id = ?
  and c.status = 'complete'
  and c.repository_sequence < ?
order by c.repository_sequence desc
limit 1
`

type GetPreviousCommitLinkedCheckpointParams struct {
	RepositoryID       string `json:"repository_id"`
	RepositorySequence int64  `json:"repository_sequence"`
}

// Ignore manual and baseline checkpoints when anchoring attribution.
func (q *Queries) GetPreviousCommitLinkedCheckpoint(ctx context.Context, arg GetPreviousCommitLinkedCheckpointParams) (Checkpoint, error) {
	row := q.queryRow(ctx, q.getPreviousCommitLinkedCheckpointStmt, getPreviousCommitLinkedCheckpoint, arg.RepositoryID, arg.RepositorySequence)
	var i Checkpoint
	err := row.Scan(
		&i.CheckpointID,
		&i.RepositoryID,
		&i.CreatedAt,
		&i.Kind,
		&i.Trigger,
		&i.Message,
		&i.ManifestHash,
		&i.SizeBytes,
		&i.Status,
		&i.CompletedAt,
		&i.SummaryJson,
		&i.SummaryModel,
		&i.RepositorySequence,
		&i.EventCursor,
		&i.AttemptCount,
		&i.LastError,
		&i.NextAttemptAt,
		&i.LeaseOwner,
		&i.LeaseUntil,
	)
	return i, err
}

const getPreviousCompletedCheckpoint = `-- name: GetPreviousCompletedCheckpoint :one
select checkpoint_id, repository_id, created_at, kind, "trigger", message, manifest_hash, size_bytes, status, completed_at, summary_json, summary_model, repository_sequence, event_cursor, attempt_count, last_error, next_attempt_at, lease_owner, lease_until from checkpoints
where repository_id = ?
  and status = 'complete'
  and manifest_hash is not null
  and repository_sequence < ?
order by repository_sequence desc
limit 1
`

type GetPreviousCompletedCheckpointParams struct {
	RepositoryID       string `json:"repository_id"`
	RepositorySequence int64  `json:"repository_sequence"`
}

// Sequence selects the predecessor; timestamps bound its event window.
func (q *Queries) GetPreviousCompletedCheckpoint(ctx context.Context, arg GetPreviousCompletedCheckpointParams) (Checkpoint, error) {
	row := q.queryRow(ctx, q.getPreviousCompletedCheckpointStmt, getPreviousCompletedCheckpoint, arg.RepositoryID, arg.RepositorySequence)
	var i Checkpoint
	err := row.Scan(
		&i.CheckpointID,
		&i.RepositoryID,
		&i.CreatedAt,
		&i.Kind,
		&i.Trigger,
		&i.Message,
		&i.ManifestHash,
		&i.SizeBytes,
		&i.Status,
		&i.CompletedAt,
		&i.SummaryJson,
		&i.SummaryModel,
		&i.RepositorySequence,
		&i.EventCursor,
		&i.AttemptCount,
		&i.LastError,
		&i.NextAttemptAt,
		&i.LeaseOwner,
		&i.LeaseUntil,
	)
	return i, err
}

const insertCheckpoint = `-- name: InsertCheckpoint :exec
insert into checkpoints(
    checkpoint_id, repository_id, created_at, kind, trigger, message,
    manifest_hash, size_bytes, status, completed_at, repository_sequence,
    event_cursor
) values (?1, ?2, ?3,
    ?4, ?5, ?6, ?7,
    ?8, ?9, ?10,
    (select coalesce(max(repository_sequence), 0) + 1
     from checkpoints c2 where c2.repository_id = ?2),
    (select coalesce(max(e.insert_seq), 0) from agent_events e))
`

type InsertCheckpointParams struct {
	CheckpointID string         `json:"checkpoint_id"`
	RepositoryID string         `json:"repository_id"`
	CreatedAt    int64          `json:"created_at"`
	Kind         string         `json:"kind"`
	Trigger      sql.NullString `json:"trigger"`
	Message      sql.NullString `json:"message"`
	ManifestHash sql.NullString `json:"manifest_hash"`
	SizeBytes    sql.NullInt64  `json:"size_bytes"`
	Status       string         `json:"status"`
	CompletedAt  sql.NullInt64  `json:"completed_at"`
}

// Allocate sequence and event cursor in the insert transaction.
func (q *Queries) InsertCheckpoint(ctx context.Context, arg InsertCheckpointParams) error {
	_, err := q.exec(ctx, q.insertCheckpointStmt, insertCheckpoint,
		arg.CheckpointID,
		arg.RepositoryID,
		arg.CreatedAt,
		arg.Kind,
		arg.Trigger,
		arg.Message,
		arg.ManifestHash,
		arg.SizeBytes,
		arg.Status,
		arg.CompletedAt,
	)
	return err
}

const listCheckpointsByRepository = `-- name: ListCheckpointsByRepository :many
select checkpoint_id, repository_id, created_at, kind, "trigger", message, manifest_hash, size_bytes, status, completed_at, summary_json, summary_model, repository_sequence, event_cursor, attempt_count, last_error, next_attempt_at, lease_owner, lease_until from checkpoints where repository_id = ? order by created_at desc limit ?
`

type ListCheckpointsByRepositoryParams struct {
	RepositoryID string `json:"repository_id"`
	Limit        int64  `json:"limit"`
}

func (q *Queries) ListCheckpointsByRepository(ctx context.Context, arg ListCheckpointsByRepositoryParams) ([]Checkpoint, error) {
	rows, err := q.query(ctx, q.listCheckpointsByRepositoryStmt, listCheckpointsByRepository, arg.RepositoryID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Checkpoint{}
	for rows.Next() {
		var i Checkpoint
		if err := rows.Scan(
			&i.CheckpointID,
			&i.RepositoryID,
			&i.CreatedAt,
			&i.Kind,
			&i.Trigger,
			&i.Message,
			&i.ManifestHash,
			&i.SizeBytes,
			&i.Status,
			&i.CompletedAt,
			&i.SummaryJson,
			&i.SummaryModel,
			&i.RepositorySequence,
			&i.EventCursor,
			&i.AttemptCount,
			&i.LastError,
			&i.NextAttemptAt,
			&i.LeaseOwner,
			&i.LeaseUntil,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCheckpointsWithCommit = `-- name: ListCheckpointsWithCommit :many
select c.checkpoint_id, c.created_at, c.kind, c.trigger, c.message,
       c.size_bytes, c.status, c.completed_at, cl.commit_hash, c.manifest_hash
from checkpoints c
    left join commit_links cl on cl.checkpoint_id = c.checkpoint_id
where c.repository_id = ?
order by c.created_at desc limit ?
`

type ListCheckpointsWithCommitParams struct {
	RepositoryID string `json:"repository_id"`
	Limit        int64  `json:"limit"`
}

type ListCheckpointsWithCommitRow struct {
	CheckpointID string         `json:"checkpoint_id"`
	CreatedAt    int64          `json:"created_at"`
	Kind         string         `json:"kind"`
	Trigger      sql.NullString `json:"trigger"`
	Message      sql.NullString `json:"message"`
	SizeBytes    sql.NullInt64  `json:"size_bytes"`
	Status       string         `json:"status"`
	CompletedAt  sql.NullInt64  `json:"completed_at"`
	CommitHash   sql.NullString `json:"commit_hash"`
	ManifestHash sql.NullString `json:"manifest_hash"`
}

func (q *Queries) ListCheckpointsWithCommit(ctx context.Context, arg ListCheckpointsWithCommitParams) ([]ListCheckpointsWithCommitRow, error) {
	rows, err := q.query(ctx, q.listCheckpointsWithCommitStmt, listCheckpointsWithCommit, arg.RepositoryID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCheckpointsWithCommitRow{}
	for rows.Next() {
		var i ListCheckpointsWithCommitRow
		if err := rows.Scan(
			&i.CheckpointID,
			&i.CreatedAt,
			&i.Kind,
			&i.Trigger,
			&i.Message,
			&i.SizeBytes,
			&i.Status,
			&i.CompletedAt,
			&i.CommitHash,
			&i.ManifestHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompletedManifestCheckpointsBefore = `-- name: ListCompletedManifestCheckpointsBefore :many
select c.checkpoint_id, c.repository_sequence, c.event_cursor,
       c.manifest_hash, c.created_at,
       (select count(*) from commit_links cl where cl.checkpoint_id = c.checkpoint_id) as commit_link_count
from checkpoints c
where c.repository_id = ?
  and c.status = 'complete'
  and c.manifest_hash is not null
  and c.repository_sequence < ?
order by c.repository_sequence desc
limit ?
`

type ListCompletedManifestCheckpointsBeforeParams struct {
	RepositoryID       string `json:"repository_id"`
	RepositorySequence int64  `json:"repository_sequence"`
	Limit              int64  `json:"limit"`
}

type ListCompletedManifestCheckpointsBeforeRow struct {
	CheckpointID       string         `json:"checkpoint_id"`
	RepositorySequence int64          `json:"repository_sequence"`
	EventCursor        sql.NullInt64  `json:"event_cursor"`
	ManifestHash       sql.NullString `json:"manifest_hash"`
	CreatedAt          int64          `json:"created_at"`
	CommitLinkCount    int64          `json:"commit_link_count"`
}

// Lists completed manifest checkpoints before a sequence, newest first.
// commit_link_count identifies linked checkpoints without duplicating rows.
func (q *Queries) ListCompletedManifestCheckpointsBefore(ctx context.Context, arg ListCompletedManifestCheckpointsBeforeParams) ([]ListCompletedManifestCheckpointsBeforeRow, error) {
	rows, err := q.query(ctx, q.listCompletedManifestCheckpointsBeforeStmt, listCompletedManifestCheckpointsBefore, arg.RepositoryID, arg.RepositorySequence, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCompletedManifestCheckpointsBeforeRow{}
	for rows.Next() {
		var i ListCompletedManifestCheckpointsBeforeRow
		if err := rows.Scan(
			&i.CheckpointID,
			&i.RepositorySequence,
			&i.EventCursor,
			&i.ManifestHash,
			&i.CreatedAt,
			&i.CommitLinkCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingCommitLinkedCheckpoints = `-- name: ListPendingCommitLinkedCheckpoints :many
select c.checkpoint_id, c.repository_sequence, c.status, cl.commit_hash,
       c.attempt_count, c.last_error, c.next_attempt_at, c.lease_until
from checkpoints c
    join commit_links cl on cl.checkpoint_id = c.checkpoint_id
where c.repository_id = ?
  and c.status in ('pending', 'failed')
order by c.repository_sequence asc, cl.linked_at desc, cl.commit_hash desc
`

type ListPendingCommitLinkedCheckpointsRow struct {
	CheckpointID       string         `json:"checkpoint_id"`
	RepositorySequence int64          `json:"repository_sequence"`
	Status             string         `json:"status"`
	CommitHash         string         `json:"commit_hash"`
	AttemptCount       int64          `json:"attempt_count"`
	LastError          sql.NullString `json:"last_error"`
	NextAttemptAt      int64          `json:"next_attempt_at"`
	LeaseUntil         sql.NullInt64  `json:"lease_until"`
}

// Include failed rows because a failed queue head blocks later work.
// Newest commit links sort first for deterministic deduplication.
func (q *Queries) ListPendingCommitLinkedCheckpoints(ctx context.Context, repositoryID string) ([]ListPendingCommitLinkedCheckpointsRow, error) {
	rows, err := q.query(ctx, q.listPendingCommitLinkedCheckpointsStmt, listPendingCommitLinkedCheckpoints, repositoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPendingCommitLinkedCheckpointsRow{}
	for rows.Next() {
		var i ListPendingCommitLinkedCheckpointsRow
		if err := rows.Scan(
			&i.CheckpointID,
			&i.RepositorySequence,
			&i.Status,
			&i.CommitHash,
			&i.AttemptCount,
			&i.LastError,
			&i.NextAttemptAt,
			&i.LeaseUntil,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentAIPercentages = `-- name: ListRecentAIPercentages :many
select cs.checkpoint_id, cs.ai_percentage, c.created_at, cl.commit_hash
from checkpoint_stats cs
    join checkpoints c on c.checkpoint_id = cs.checkpoint_id
    join commit_links cl on cl.checkpoint_id = cs.checkpoint_id
where c.repository_id = ? and cs.ai_percentage >= 0
order by c.created_at desc
limit ?
`

type ListRecentAIPercentagesParams struct {
	RepositoryID string `json:"repository_id"`
	Limit        int64  `json:"limit"`
}

type ListRecentAIPercentagesRow struct {
	CheckpointID string  `json:"checkpoint_id"`
	AiPercentage float64 `json:"ai_percentage"`
	CreatedAt    int64   `json:"created_at"`
	CommitHash   string  `json:"commit_hash"`
}

func (q *Queries) ListRecentAIPercentages(ctx context.Context, arg ListRecentAIPercentagesParams) ([]ListRecentAIPercentagesRow, error) {
	rows, err := q.query(ctx, q.listRecentAIPercentagesStmt, listRecentAIPercentages, arg.RepositoryID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecentAIPercentagesRow{}
	for rows.Next() {
		var i ListRecentAIPercentagesRow
		if err := rows.Scan(
			&i.CheckpointID,
			&i.AiPercentage,
			&i.CreatedAt,
			&i.CommitHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStalePendingCheckpoints = `-- name: ListStalePendingCheckpoints :many
select c.checkpoint_id, c.created_at from checkpoints c
    left join commit_links cl on cl.checkpoint_id = c.checkpoint_id
where c.repository_id = ?
  and c.status = 'pending'
  and c.manifest_hash is null
  and cl.commit_hash is null
  and c.created_at < ?2
`

type ListStalePendingCheckpointsParams struct {
	RepositoryID string `json:"repository_id"`
	BeforeTs     int64  `json:"before_ts"`
}

type ListStalePendingCheckpointsRow struct {
	CheckpointID string `json:"checkpoint_id"`
	CreatedAt    int64  `json:"created_at"`
}

// Returns pending checkpoints older than the given threshold that have
// no manifest and no commit link. Used by tidy to mark abandoned checkpoints
// as failed.
func (q *Queries) ListStalePendingCheckpoints(ctx context.Context, arg ListStalePendingCheckpointsParams) ([]ListStalePendingCheckpointsRow, error) {
	rows, err := q.query(ctx, q.listStalePendingCheckpointsStmt, listStalePendingCheckpoints, arg.RepositoryID, arg.BeforeTs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStalePendingCheckpointsRow{}
	for rows.Next() {
		var i ListStalePendingCheckpointsRow
		if err := rows.Scan(&i.CheckpointID, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markCheckpointAttributionPushed = `-- name: MarkCheckpointAttributionPushed :exec
insert into checkpoint_stats (checkpoint_id, attribution_pushed_at)
values (?, ?)
on conflict(checkpoint_id) do update set
    attribution_pushed_at = excluded.attribution_pushed_at
`

type MarkCheckpointAttributionPushedParams struct {
	CheckpointID        string        `json:"checkpoint_id"`
	AttributionPushedAt sql.NullInt64 `json:"attribution_pushed_at"`
}

// Records a successful hosted attribution push. Upsert creates missing stats rows.
func (q *Queries) MarkCheckpointAttributionPushed(ctx context.Context, arg MarkCheckpointAttributionPushedParams) error {
	_, err := q.exec(ctx, q.markCheckpointAttributionPushedStmt, markCheckpointAttributionPushed, arg.CheckpointID, arg.AttributionPushedAt)
	return err
}

const recordCheckpointAttribution = `-- name: RecordCheckpointAttribution :exec
insert into checkpoint_stats (checkpoint_id, ai_percentage, attribution_computed_at, attribution_version)
values (?, ?, ?, ?)
on conflict(checkpoint_id) do update set
    ai_percentage = excluded.ai_percentage,
    attribution_computed_at = excluded.attribution_computed_at,
    attribution_version = excluded.attribution_version
`

type RecordCheckpointAttributionParams struct {
	CheckpointID          string         `json:"checkpoint_id"`
	AiPercentage          float64        `json:"ai_percentage"`
	AttributionComputedAt sql.NullInt64  `json:"attribution_computed_at"`
	AttributionVersion    sql.NullString `json:"attribution_version"`
}

// Stores the result and its scoring version in one statement. A percentage
// of -1 marks a completed run with no attributable changes.
func (q *Queries) RecordCheckpointAttribution(ctx context.Context, arg RecordCheckpointAttributionParams) error {
	_, err := q.exec(ctx, q.recordCheckpointAttributionStmt, recordCheckpointAttribution,
		arg.CheckpointID,
		arg.AiPercentage,
		arg.AttributionComputedAt,
		arg.AttributionVersion,
	)
	return err
}

const releaseCheckpointForRetry = `-- name: ReleaseCheckpointForRetry :execrows
update checkpoints
set last_error = ?, next_attempt_at = ?,
    lease_owner = null, lease_until = null
where checkpoint_id = ? and lease_owner = ?
`

type ReleaseCheckpointForRetryParams struct {
	LastError     sql.NullString `json:"last_error"`
	NextAttemptAt int64          `json:"next_attempt_at"`
	CheckpointID  string         `json:"checkpoint_id"`
	LeaseOwner    sql.NullString `json:"lease_owner"`
}

// Transient failure: release the lease with a scheduled retry. The
// attempt counter was already incremented by the claim. Callers must
// require one affected row; zero means the lease was lost and the
// transition was not recorded.
func (q *Queries) ReleaseCheckpointForRetry(ctx context.Context, arg ReleaseCheckpointForRetryParams) (int64, error) {
	result, err := q.exec(ctx, q.releaseCheckpointForRetryStmt, releaseCheckpointForRetry,
		arg.LastError,
		arg.NextAttemptAt,
		arg.CheckpointID,
		arg.LeaseOwner,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const resolveCheckpointByPrefix = `-- name: ResolveCheckpointByPrefix :many
select checkpoint_id from checkpoints
where checkpoint_id like ? and repository_id = ?
limit 2
`

type ResolveCheckpointByPrefixParams struct {
	CheckpointID string `json:"checkpoint_id"`
	RepositoryID string `json:"repository_id"`
}

func (q *Queries) ResolveCheckpointByPrefix(ctx context.Context, arg ResolveCheckpointByPrefixParams) ([]string, error) {
	rows, err := q.query(ctx, q.resolveCheckpointByPrefixStmt, resolveCheckpointByPrefix, arg.CheckpointID, arg.RepositoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var checkpoint_id string
		if err := rows.Scan(&checkpoint_id); err != nil {
			return nil, err
		}
		items = append(items, checkpoint_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const retryFailedCheckpoint = `-- name: RetryFailedCheckpoint :execrows
update checkpoints
set status = 'pending', attempt_count = 0, next_attempt_at = 0,
    lease_owner = null, lease_until = null,
    last_error = null, completed_at = null
where checkpoint_id = ? and status = 'failed'
`

// Manual retry: a human intervened, so the attempt budget resets.
func (q *Queries) RetryFailedCheckpoint(ctx context.Context, checkpointID string) (int64, error) {
	result, err := q.exec(ctx, q.retryFailedCheckpointStmt, retryFailedCheckpoint, checkpointID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const saveCheckpointSummary = `-- name: SaveCheckpointSummary :exec
update checkpoints
set summary_json = ?, summary_model = ?
where checkpoint_id = ?
`

type SaveCheckpointSummaryParams struct {
	SummaryJson  sql.NullString `json:"summary_json"`
	SummaryModel sql.NullString `json:"summary_model"`
	CheckpointID string         `json:"checkpoint_id"`
}

func (q *Queries) SaveCheckpointSummary(ctx context.Context, arg SaveCheckpointSummaryParams) error {
	_, err := q.exec(ctx, q.saveCheckpointSummaryStmt, saveCheckpointSummary, arg.SummaryJson, arg.SummaryModel, arg.CheckpointID)
	return err
}

const upsertCheckpointStats = `-- name: UpsertCheckpointStats :exec
insert into checkpoint_stats (
    checkpoint_id, session_count, files_changed
) values (?, ?, ?)
on conflict(checkpoint_id) do update set
    session_count=excluded.session_count,
    files_changed=excluded.files_changed
`

type UpsertCheckpointStatsParams struct {
	CheckpointID string `json:"checkpoint_id"`
	SessionCount int64  `json:"session_count"`
	FilesChanged int64  `json:"files_changed"`
}

func (q *Queries) UpsertCheckpointStats(ctx context.Context, arg UpsertCheckpointStatsParams) error {
	_, err := q.exec(ctx, q.upsertCheckpointStatsStmt, upsertCheckpointStats, arg.CheckpointID, arg.SessionCount, arg.FilesChanged)
	return err
}
