// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: commit_links.sql

package db

import (
	"context"
)

const getCommitLinkByCommitHash = `-- name: GetCommitLinkByCommitHash :one
select commit_hash, repository_id, checkpoint_id, linked_at from commit_links where commit_hash = ?
`

func (q *Queries) GetCommitLinkByCommitHash(ctx context.Context, commitHash string) (CommitLink, error) {
	row := q.queryRow(ctx, q.getCommitLinkByCommitHashStmt, getCommitLinkByCommitHash, commitHash)
	var i CommitLink
	err := row.Scan(
		&i.CommitHash,
		&i.RepositoryID,
		&i.CheckpointID,
		&i.LinkedAt,
	)
	return i, err
}

const getCommitLinksByCheckpoint = `-- name: GetCommitLinksByCheckpoint :many
select commit_hash, repository_id, checkpoint_id, linked_at from commit_links where checkpoint_id = ?
`

func (q *Queries) GetCommitLinksByCheckpoint(ctx context.Context, checkpointID string) ([]CommitLink, error) {
	rows, err := q.query(ctx, q.getCommitLinksByCheckpointStmt, getCommitLinksByCheckpoint, checkpointID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CommitLink{}
	for rows.Next() {
		var i CommitLink
		if err := rows.Scan(
			&i.CommitHash,
			&i.RepositoryID,
			&i.CheckpointID,
			&i.LinkedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertCommitLink = `-- name: InsertCommitLink :exec
insert or ignore into commit_links(commit_hash, repository_id, checkpoint_id, linked_at)
values (?, ?, ?, ?)
`

type InsertCommitLinkParams struct {
	CommitHash   string `json:"commit_hash"`
	RepositoryID string `json:"repository_id"`
	CheckpointID string `json:"checkpoint_id"`
	LinkedAt     int64  `json:"linked_at"`
}

func (q *Queries) InsertCommitLink(ctx context.Context, arg InsertCommitLinkParams) error {
	_, err := q.exec(ctx, q.insertCommitLinkStmt, insertCommitLink,
		arg.CommitHash,
		arg.RepositoryID,
		arg.CheckpointID,
		arg.LinkedAt,
	)
	return err
}

const listCommitLinksByRepository = `-- name: ListCommitLinksByRepository :many
select commit_hash, repository_id, checkpoint_id, linked_at from commit_links where repository_id = ? order by linked_at desc limit ?
`

type ListCommitLinksByRepositoryParams struct {
	RepositoryID string `json:"repository_id"`
	Limit        int64  `json:"limit"`
}

func (q *Queries) ListCommitLinksByRepository(ctx context.Context, arg ListCommitLinksByRepositoryParams) ([]CommitLink, error) {
	rows, err := q.query(ctx, q.listCommitLinksByRepositoryStmt, listCommitLinksByRepository, arg.RepositoryID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CommitLink{}
	for rows.Next() {
		var i CommitLink
		if err := rows.Scan(
			&i.CommitHash,
			&i.RepositoryID,
			&i.CheckpointID,
			&i.LinkedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveCommitLinkByPrefix = `-- name: ResolveCommitLinkByPrefix :many
select commit_hash from commit_links
where commit_hash like ? and repository_id = ?
limit 2
`

type ResolveCommitLinkByPrefixParams struct {
	CommitHash   string `json:"commit_hash"`
	RepositoryID string `json:"repository_id"`
}

func (q *Queries) ResolveCommitLinkByPrefix(ctx context.Context, arg ResolveCommitLinkByPrefixParams) ([]string, error) {
	rows, err := q.query(ctx, q.resolveCommitLinkByPrefixStmt, resolveCommitLinkByPrefix, arg.CommitHash, arg.RepositoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var commit_hash string
		if err := rows.Scan(&commit_hash); err != nil {
			return nil, err
		}
		items = append(items, commit_hash)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
