// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: commit_links.sql

package db

import (
	"context"
	"database/sql"
)

const getCommitLinkByCommitHash = `-- name: GetCommitLinkByCommitHash :one
select commit_hash, repository_id, checkpoint_id, linked_at from commit_links where commit_hash = ?
`

func (q *Queries) GetCommitLinkByCommitHash(ctx context.Context, commitHash string) (CommitLink, error) {
	row := q.queryRow(ctx, q.getCommitLinkByCommitHashStmt, getCommitLinkByCommitHash, commitHash)
	var i CommitLink
	err := row.Scan(
		&i.CommitHash,
		&i.RepositoryID,
		&i.CheckpointID,
		&i.LinkedAt,
	)
	return i, err
}

const getCommitLinksByCheckpoint = `-- name: GetCommitLinksByCheckpoint :many
select commit_hash, repository_id, checkpoint_id, linked_at from commit_links where checkpoint_id = ?
`

func (q *Queries) GetCommitLinksByCheckpoint(ctx context.Context, checkpointID string) ([]CommitLink, error) {
	rows, err := q.query(ctx, q.getCommitLinksByCheckpointStmt, getCommitLinksByCheckpoint, checkpointID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CommitLink{}
	for rows.Next() {
		var i CommitLink
		if err := rows.Scan(
			&i.CommitHash,
			&i.RepositoryID,
			&i.CheckpointID,
			&i.LinkedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertCommitLink = `-- name: InsertCommitLink :exec
insert or ignore into commit_links(commit_hash, repository_id, checkpoint_id, linked_at)
values (?, ?, ?, ?)
`

type InsertCommitLinkParams struct {
	CommitHash   string `json:"commit_hash"`
	RepositoryID string `json:"repository_id"`
	CheckpointID string `json:"checkpoint_id"`
	LinkedAt     int64  `json:"linked_at"`
}

func (q *Queries) InsertCommitLink(ctx context.Context, arg InsertCommitLinkParams) error {
	_, err := q.exec(ctx, q.insertCommitLinkStmt, insertCommitLink,
		arg.CommitHash,
		arg.RepositoryID,
		arg.CheckpointID,
		arg.LinkedAt,
	)
	return err
}

const listCommitLinksByRepository = `-- name: ListCommitLinksByRepository :many
select commit_hash, repository_id, checkpoint_id, linked_at from commit_links where repository_id = ? order by linked_at desc limit ?
`

type ListCommitLinksByRepositoryParams struct {
	RepositoryID string `json:"repository_id"`
	Limit        int64  `json:"limit"`
}

func (q *Queries) ListCommitLinksByRepository(ctx context.Context, arg ListCommitLinksByRepositoryParams) ([]CommitLink, error) {
	rows, err := q.query(ctx, q.listCommitLinksByRepositoryStmt, listCommitLinksByRepository, arg.RepositoryID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CommitLink{}
	for rows.Next() {
		var i CommitLink
		if err := rows.Scan(
			&i.CommitHash,
			&i.RepositoryID,
			&i.CheckpointID,
			&i.LinkedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserPromptsForCommit = `-- name: ListUserPromptsForCommit :many
with this_checkpoint as (
    select c.checkpoint_id, c.repository_id, ck.created_at
    from commit_links c
    join checkpoints ck on ck.checkpoint_id = c.checkpoint_id
    where c.commit_hash = ?
    limit 1
),
prev_checkpoint_ts as (
    select coalesce(max(ck2.created_at), 0) as cutoff
    from commit_links c2
    join checkpoints ck2 on ck2.checkpoint_id = c2.checkpoint_id
    join this_checkpoint tc on tc.repository_id = c2.repository_id
    where ck2.created_at < tc.created_at
),
ranked as (
    select
        e.event_id, e.turn_id, e.ts, e.summary, e.payload_hash,
        row_number() over (partition by e.turn_id order by e.ts asc) as rn
    from this_checkpoint tc
    cross join prev_checkpoint_ts pc
    join session_checkpoints sc on sc.checkpoint_id = tc.checkpoint_id
    join agent_events e on e.session_id = sc.session_id
    where e.role = 'user'
      and e.kind = 'user'
      and e.turn_id is not null
      and e.turn_id != ''
      and e.ts <= tc.created_at
      and e.ts > pc.cutoff
)
select event_id, turn_id, ts, summary, payload_hash
from ranked
where rn = 1
order by ts asc
`

type ListUserPromptsForCommitRow struct {
	EventID     string         `json:"event_id"`
	TurnID      sql.NullString `json:"turn_id"`
	Ts          int64          `json:"ts"`
	Summary     sql.NullString `json:"summary"`
	PayloadHash sql.NullString `json:"payload_hash"`
}

// Returns user prompts attributable to a single commit.
//
// Isolation rules:
//   - User prompt events only; assistant and tool-result events are excluded.
//   - Events must fall within the commit checkpoint window.
//   - Duplicate turn IDs keep the earliest event for deterministic ordering.
//   - Events without a turn ID are excluded because they cannot be cited.
func (q *Queries) ListUserPromptsForCommit(ctx context.Context, commitHash string) ([]ListUserPromptsForCommitRow, error) {
	rows, err := q.query(ctx, q.listUserPromptsForCommitStmt, listUserPromptsForCommit, commitHash)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserPromptsForCommitRow{}
	for rows.Next() {
		var i ListUserPromptsForCommitRow
		if err := rows.Scan(
			&i.EventID,
			&i.TurnID,
			&i.Ts,
			&i.Summary,
			&i.PayloadHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveCommitLinkByPrefix = `-- name: ResolveCommitLinkByPrefix :many
select commit_hash from commit_links
where commit_hash like ? and repository_id = ?
limit 2
`

type ResolveCommitLinkByPrefixParams struct {
	CommitHash   string `json:"commit_hash"`
	RepositoryID string `json:"repository_id"`
}

func (q *Queries) ResolveCommitLinkByPrefix(ctx context.Context, arg ResolveCommitLinkByPrefixParams) ([]string, error) {
	rows, err := q.query(ctx, q.resolveCommitLinkByPrefixStmt, resolveCommitLinkByPrefix, arg.CommitHash, arg.RepositoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var commit_hash string
		if err := rows.Scan(&commit_hash); err != nil {
			return nil, err
		}
		items = append(items, commit_hash)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
