// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.advanceBackfillCursorStmt, err = db.PrepareContext(ctx, advanceBackfillCursor); err != nil {
		return nil, fmt.Errorf("error preparing query AdvanceBackfillCursor: %w", err)
	}
	if q.completeBackfillStmt, err = db.PrepareContext(ctx, completeBackfill); err != nil {
		return nil, fmt.Errorf("error preparing query CompleteBackfill: %w", err)
	}
	if q.completeCheckpointStmt, err = db.PrepareContext(ctx, completeCheckpoint); err != nil {
		return nil, fmt.Errorf("error preparing query CompleteCheckpoint: %w", err)
	}
	if q.countCheckpointsWithSummaryStmt, err = db.PrepareContext(ctx, countCheckpointsWithSummary); err != nil {
		return nil, fmt.Errorf("error preparing query CountCheckpointsWithSummary: %w", err)
	}
	if q.countSessionsForCheckpointStmt, err = db.PrepareContext(ctx, countSessionsForCheckpoint); err != nil {
		return nil, fmt.Errorf("error preparing query CountSessionsForCheckpoint: %w", err)
	}
	if q.deleteCheckpointByIDStmt, err = db.PrepareContext(ctx, deleteCheckpointByID); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteCheckpointByID: %w", err)
	}
	if q.failCheckpointStmt, err = db.PrepareContext(ctx, failCheckpoint); err != nil {
		return nil, fmt.Errorf("error preparing query FailCheckpoint: %w", err)
	}
	if q.getActiveAgentSessionForRepoStmt, err = db.PrepareContext(ctx, getActiveAgentSessionForRepo); err != nil {
		return nil, fmt.Errorf("error preparing query GetActiveAgentSessionForRepo: %w", err)
	}
	if q.getAgentSessionByIDStmt, err = db.PrepareContext(ctx, getAgentSessionByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetAgentSessionByID: %w", err)
	}
	if q.getAgentSessionByProviderIDStmt, err = db.PrepareContext(ctx, getAgentSessionByProviderID); err != nil {
		return nil, fmt.Errorf("error preparing query GetAgentSessionByProviderID: %w", err)
	}
	if q.getAttributionBackfillStmt, err = db.PrepareContext(ctx, getAttributionBackfill); err != nil {
		return nil, fmt.Errorf("error preparing query GetAttributionBackfill: %w", err)
	}
	if q.getCheckpointByIDStmt, err = db.PrepareContext(ctx, getCheckpointByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetCheckpointByID: %w", err)
	}
	if q.getCheckpointStatsStmt, err = db.PrepareContext(ctx, getCheckpointStats); err != nil {
		return nil, fmt.Errorf("error preparing query GetCheckpointStats: %w", err)
	}
	if q.getCheckpointSummaryStmt, err = db.PrepareContext(ctx, getCheckpointSummary); err != nil {
		return nil, fmt.Errorf("error preparing query GetCheckpointSummary: %w", err)
	}
	if q.getCommitLinkByCommitHashStmt, err = db.PrepareContext(ctx, getCommitLinkByCommitHash); err != nil {
		return nil, fmt.Errorf("error preparing query GetCommitLinkByCommitHash: %w", err)
	}
	if q.getCommitLinksByCheckpointStmt, err = db.PrepareContext(ctx, getCommitLinksByCheckpoint); err != nil {
		return nil, fmt.Errorf("error preparing query GetCommitLinksByCheckpoint: %w", err)
	}
	if q.getLatestCheckpointForRepoStmt, err = db.PrepareContext(ctx, getLatestCheckpointForRepo); err != nil {
		return nil, fmt.Errorf("error preparing query GetLatestCheckpointForRepo: %w", err)
	}
	if q.getLatestCommitLinkStmt, err = db.PrepareContext(ctx, getLatestCommitLink); err != nil {
		return nil, fmt.Errorf("error preparing query GetLatestCommitLink: %w", err)
	}
	if q.getManifestCommitLinkStmt, err = db.PrepareContext(ctx, getManifestCommitLink); err != nil {
		return nil, fmt.Errorf("error preparing query GetManifestCommitLink: %w", err)
	}
	if q.getNextToolResultAfterStmt, err = db.PrepareContext(ctx, getNextToolResultAfter); err != nil {
		return nil, fmt.Errorf("error preparing query GetNextToolResultAfter: %w", err)
	}
	if q.getPreviousCommitLinkedCheckpointStmt, err = db.PrepareContext(ctx, getPreviousCommitLinkedCheckpoint); err != nil {
		return nil, fmt.Errorf("error preparing query GetPreviousCommitLinkedCheckpoint: %w", err)
	}
	if q.getPreviousCompletedCheckpointStmt, err = db.PrepareContext(ctx, getPreviousCompletedCheckpoint); err != nil {
		return nil, fmt.Errorf("error preparing query GetPreviousCompletedCheckpoint: %w", err)
	}
	if q.getPromptEventForTurnStmt, err = db.PrepareContext(ctx, getPromptEventForTurn); err != nil {
		return nil, fmt.Errorf("error preparing query GetPromptEventForTurn: %w", err)
	}
	if q.getRepositoryByIDStmt, err = db.PrepareContext(ctx, getRepositoryByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetRepositoryByID: %w", err)
	}
	if q.getRepositoryByRootPathStmt, err = db.PrepareContext(ctx, getRepositoryByRootPath); err != nil {
		return nil, fmt.Errorf("error preparing query GetRepositoryByRootPath: %w", err)
	}
	if q.getSessionWithStatsStmt, err = db.PrepareContext(ctx, getSessionWithStats); err != nil {
		return nil, fmt.Errorf("error preparing query GetSessionWithStats: %w", err)
	}
	if q.insertAgentEventStmt, err = db.PrepareContext(ctx, insertAgentEvent); err != nil {
		return nil, fmt.Errorf("error preparing query InsertAgentEvent: %w", err)
	}
	if q.insertCheckpointStmt, err = db.PrepareContext(ctx, insertCheckpoint); err != nil {
		return nil, fmt.Errorf("error preparing query InsertCheckpoint: %w", err)
	}
	if q.insertCommitLinkStmt, err = db.PrepareContext(ctx, insertCommitLink); err != nil {
		return nil, fmt.Errorf("error preparing query InsertCommitLink: %w", err)
	}
	if q.insertRepositoryStmt, err = db.PrepareContext(ctx, insertRepository); err != nil {
		return nil, fmt.Errorf("error preparing query InsertRepository: %w", err)
	}
	if q.insertSessionCheckpointStmt, err = db.PrepareContext(ctx, insertSessionCheckpoint); err != nil {
		return nil, fmt.Errorf("error preparing query InsertSessionCheckpoint: %w", err)
	}
	if q.listAgentEventsBySessionStmt, err = db.PrepareContext(ctx, listAgentEventsBySession); err != nil {
		return nil, fmt.Errorf("error preparing query ListAgentEventsBySession: %w", err)
	}
	if q.listBackfillReplayCandidatesStmt, err = db.PrepareContext(ctx, listBackfillReplayCandidates); err != nil {
		return nil, fmt.Errorf("error preparing query ListBackfillReplayCandidates: %w", err)
	}
	if q.listCheckpointsByRepositoryStmt, err = db.PrepareContext(ctx, listCheckpointsByRepository); err != nil {
		return nil, fmt.Errorf("error preparing query ListCheckpointsByRepository: %w", err)
	}
	if q.listCheckpointsWithCommitStmt, err = db.PrepareContext(ctx, listCheckpointsWithCommit); err != nil {
		return nil, fmt.Errorf("error preparing query ListCheckpointsWithCommit: %w", err)
	}
	if q.listCommitLinksByRepositoryStmt, err = db.PrepareContext(ctx, listCommitLinksByRepository); err != nil {
		return nil, fmt.Errorf("error preparing query ListCommitLinksByRepository: %w", err)
	}
	if q.listCrossRepoSessionsStmt, err = db.PrepareContext(ctx, listCrossRepoSessions); err != nil {
		return nil, fmt.Errorf("error preparing query ListCrossRepoSessions: %w", err)
	}
	if q.listDistinctProvidersStmt, err = db.PrepareContext(ctx, listDistinctProviders); err != nil {
		return nil, fmt.Errorf("error preparing query ListDistinctProviders: %w", err)
	}
	if q.listEventsBySessionASCStmt, err = db.PrepareContext(ctx, listEventsBySessionASC); err != nil {
		return nil, fmt.Errorf("error preparing query ListEventsBySessionASC: %w", err)
	}
	if q.listEventsInWindowStmt, err = db.PrepareContext(ctx, listEventsInWindow); err != nil {
		return nil, fmt.Errorf("error preparing query ListEventsInWindow: %w", err)
	}
	if q.listPackagedManifestsStmt, err = db.PrepareContext(ctx, listPackagedManifests); err != nil {
		return nil, fmt.Errorf("error preparing query ListPackagedManifests: %w", err)
	}
	if q.listPendingManifestsStmt, err = db.PrepareContext(ctx, listPendingManifests); err != nil {
		return nil, fmt.Errorf("error preparing query ListPendingManifests: %w", err)
	}
	if q.listProvidersByCheckpointStmt, err = db.PrepareContext(ctx, listProvidersByCheckpoint); err != nil {
		return nil, fmt.Errorf("error preparing query ListProvidersByCheckpoint: %w", err)
	}
	if q.listRecentAIPercentagesStmt, err = db.PrepareContext(ctx, listRecentAIPercentages); err != nil {
		return nil, fmt.Errorf("error preparing query ListRecentAIPercentages: %w", err)
	}
	if q.listRecentSessionsWithStatsStmt, err = db.PrepareContext(ctx, listRecentSessionsWithStats); err != nil {
		return nil, fmt.Errorf("error preparing query ListRecentSessionsWithStats: %w", err)
	}
	if q.listRepositoriesStmt, err = db.PrepareContext(ctx, listRepositories); err != nil {
		return nil, fmt.Errorf("error preparing query ListRepositories: %w", err)
	}
	if q.listSessionsForCheckpointStmt, err = db.PrepareContext(ctx, listSessionsForCheckpoint); err != nil {
		return nil, fmt.Errorf("error preparing query ListSessionsForCheckpoint: %w", err)
	}
	if q.listSessionsForRepositoryStmt, err = db.PrepareContext(ctx, listSessionsForRepository); err != nil {
		return nil, fmt.Errorf("error preparing query ListSessionsForRepository: %w", err)
	}
	if q.listSessionsWithEventsInWindowStmt, err = db.PrepareContext(ctx, listSessionsWithEventsInWindow); err != nil {
		return nil, fmt.Errorf("error preparing query ListSessionsWithEventsInWindow: %w", err)
	}
	if q.listSessionsWithStatsStmt, err = db.PrepareContext(ctx, listSessionsWithStats); err != nil {
		return nil, fmt.Errorf("error preparing query ListSessionsWithStats: %w", err)
	}
	if q.listSessionsWithStatsAllStmt, err = db.PrepareContext(ctx, listSessionsWithStatsAll); err != nil {
		return nil, fmt.Errorf("error preparing query ListSessionsWithStatsAll: %w", err)
	}
	if q.listStalePendingCheckpointsStmt, err = db.PrepareContext(ctx, listStalePendingCheckpoints); err != nil {
		return nil, fmt.Errorf("error preparing query ListStalePendingCheckpoints: %w", err)
	}
	if q.listStepCompanionResultsStmt, err = db.PrepareContext(ctx, listStepCompanionResults); err != nil {
		return nil, fmt.Errorf("error preparing query ListStepCompanionResults: %w", err)
	}
	if q.listStepEventsForTurnStmt, err = db.PrepareContext(ctx, listStepEventsForTurn); err != nil {
		return nil, fmt.Errorf("error preparing query ListStepEventsForTurn: %w", err)
	}
	if q.listStepProvenanceForTurnStmt, err = db.PrepareContext(ctx, listStepProvenanceForTurn); err != nil {
		return nil, fmt.Errorf("error preparing query ListStepProvenanceForTurn: %w", err)
	}
	if q.listTranscriptEventsStmt, err = db.PrepareContext(ctx, listTranscriptEvents); err != nil {
		return nil, fmt.Errorf("error preparing query ListTranscriptEvents: %w", err)
	}
	if q.markManifestFailedStmt, err = db.PrepareContext(ctx, markManifestFailed); err != nil {
		return nil, fmt.Errorf("error preparing query MarkManifestFailed: %w", err)
	}
	if q.markManifestUploadedStmt, err = db.PrepareContext(ctx, markManifestUploaded); err != nil {
		return nil, fmt.Errorf("error preparing query MarkManifestUploaded: %w", err)
	}
	if q.markManifestUploadingStmt, err = db.PrepareContext(ctx, markManifestUploading); err != nil {
		return nil, fmt.Errorf("error preparing query MarkManifestUploading: %w", err)
	}
	if q.promptEventExistsStmt, err = db.PrepareContext(ctx, promptEventExists); err != nil {
		return nil, fmt.Errorf("error preparing query PromptEventExists: %w", err)
	}
	if q.recordBackfillFailureStmt, err = db.PrepareContext(ctx, recordBackfillFailure); err != nil {
		return nil, fmt.Errorf("error preparing query RecordBackfillFailure: %w", err)
	}
	if q.recoverStaleUploadingStmt, err = db.PrepareContext(ctx, recoverStaleUploading); err != nil {
		return nil, fmt.Errorf("error preparing query RecoverStaleUploading: %w", err)
	}
	if q.resetManifestForRetryStmt, err = db.PrepareContext(ctx, resetManifestForRetry); err != nil {
		return nil, fmt.Errorf("error preparing query ResetManifestForRetry: %w", err)
	}
	if q.resetManifestToPackagedStmt, err = db.PrepareContext(ctx, resetManifestToPackaged); err != nil {
		return nil, fmt.Errorf("error preparing query ResetManifestToPackaged: %w", err)
	}
	if q.resolveCheckpointByPrefixStmt, err = db.PrepareContext(ctx, resolveCheckpointByPrefix); err != nil {
		return nil, fmt.Errorf("error preparing query ResolveCheckpointByPrefix: %w", err)
	}
	if q.resolveCommitLinkByPrefixStmt, err = db.PrepareContext(ctx, resolveCommitLinkByPrefix); err != nil {
		return nil, fmt.Errorf("error preparing query ResolveCommitLinkByPrefix: %w", err)
	}
	if q.resolveSessionByPrefixStmt, err = db.PrepareContext(ctx, resolveSessionByPrefix); err != nil {
		return nil, fmt.Errorf("error preparing query ResolveSessionByPrefix: %w", err)
	}
	if q.saveCheckpointSummaryStmt, err = db.PrepareContext(ctx, saveCheckpointSummary); err != nil {
		return nil, fmt.Errorf("error preparing query SaveCheckpointSummary: %w", err)
	}
	if q.stepEventExistsStmt, err = db.PrepareContext(ctx, stepEventExists); err != nil {
		return nil, fmt.Errorf("error preparing query StepEventExists: %w", err)
	}
	if q.updateCheckpointAIPercentageStmt, err = db.PrepareContext(ctx, updateCheckpointAIPercentage); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateCheckpointAIPercentage: %w", err)
	}
	if q.updateRepositoryEnabledAtStmt, err = db.PrepareContext(ctx, updateRepositoryEnabledAt); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateRepositoryEnabledAt: %w", err)
	}
	if q.upsertAgentSessionStmt, err = db.PrepareContext(ctx, upsertAgentSession); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertAgentSession: %w", err)
	}
	if q.upsertAgentSourceStmt, err = db.PrepareContext(ctx, upsertAgentSource); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertAgentSource: %w", err)
	}
	if q.upsertAttributionBackfillStmt, err = db.PrepareContext(ctx, upsertAttributionBackfill); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertAttributionBackfill: %w", err)
	}
	if q.upsertCheckpointStatsStmt, err = db.PrepareContext(ctx, upsertCheckpointStats); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertCheckpointStats: %w", err)
	}
	if q.upsertProvenanceManifestStmt, err = db.PrepareContext(ctx, upsertProvenanceManifest); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertProvenanceManifest: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.advanceBackfillCursorStmt != nil {
		if cerr := q.advanceBackfillCursorStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing advanceBackfillCursorStmt: %w", cerr)
		}
	}
	if q.completeBackfillStmt != nil {
		if cerr := q.completeBackfillStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing completeBackfillStmt: %w", cerr)
		}
	}
	if q.completeCheckpointStmt != nil {
		if cerr := q.completeCheckpointStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing completeCheckpointStmt: %w", cerr)
		}
	}
	if q.countCheckpointsWithSummaryStmt != nil {
		if cerr := q.countCheckpointsWithSummaryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countCheckpointsWithSummaryStmt: %w", cerr)
		}
	}
	if q.countSessionsForCheckpointStmt != nil {
		if cerr := q.countSessionsForCheckpointStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countSessionsForCheckpointStmt: %w", cerr)
		}
	}
	if q.deleteCheckpointByIDStmt != nil {
		if cerr := q.deleteCheckpointByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteCheckpointByIDStmt: %w", cerr)
		}
	}
	if q.failCheckpointStmt != nil {
		if cerr := q.failCheckpointStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing failCheckpointStmt: %w", cerr)
		}
	}
	if q.getActiveAgentSessionForRepoStmt != nil {
		if cerr := q.getActiveAgentSessionForRepoStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getActiveAgentSessionForRepoStmt: %w", cerr)
		}
	}
	if q.getAgentSessionByIDStmt != nil {
		if cerr := q.getAgentSessionByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAgentSessionByIDStmt: %w", cerr)
		}
	}
	if q.getAgentSessionByProviderIDStmt != nil {
		if cerr := q.getAgentSessionByProviderIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAgentSessionByProviderIDStmt: %w", cerr)
		}
	}
	if q.getAttributionBackfillStmt != nil {
		if cerr := q.getAttributionBackfillStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAttributionBackfillStmt: %w", cerr)
		}
	}
	if q.getCheckpointByIDStmt != nil {
		if cerr := q.getCheckpointByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getCheckpointByIDStmt: %w", cerr)
		}
	}
	if q.getCheckpointStatsStmt != nil {
		if cerr := q.getCheckpointStatsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getCheckpointStatsStmt: %w", cerr)
		}
	}
	if q.getCheckpointSummaryStmt != nil {
		if cerr := q.getCheckpointSummaryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getCheckpointSummaryStmt: %w", cerr)
		}
	}
	if q.getCommitLinkByCommitHashStmt != nil {
		if cerr := q.getCommitLinkByCommitHashStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getCommitLinkByCommitHashStmt: %w", cerr)
		}
	}
	if q.getCommitLinksByCheckpointStmt != nil {
		if cerr := q.getCommitLinksByCheckpointStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getCommitLinksByCheckpointStmt: %w", cerr)
		}
	}
	if q.getLatestCheckpointForRepoStmt != nil {
		if cerr := q.getLatestCheckpointForRepoStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getLatestCheckpointForRepoStmt: %w", cerr)
		}
	}
	if q.getLatestCommitLinkStmt != nil {
		if cerr := q.getLatestCommitLinkStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getLatestCommitLinkStmt: %w", cerr)
		}
	}
	if q.getManifestCommitLinkStmt != nil {
		if cerr := q.getManifestCommitLinkStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getManifestCommitLinkStmt: %w", cerr)
		}
	}
	if q.getNextToolResultAfterStmt != nil {
		if cerr := q.getNextToolResultAfterStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getNextToolResultAfterStmt: %w", cerr)
		}
	}
	if q.getPreviousCommitLinkedCheckpointStmt != nil {
		if cerr := q.getPreviousCommitLinkedCheckpointStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getPreviousCommitLinkedCheckpointStmt: %w", cerr)
		}
	}
	if q.getPreviousCompletedCheckpointStmt != nil {
		if cerr := q.getPreviousCompletedCheckpointStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getPreviousCompletedCheckpointStmt: %w", cerr)
		}
	}
	if q.getPromptEventForTurnStmt != nil {
		if cerr := q.getPromptEventForTurnStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getPromptEventForTurnStmt: %w", cerr)
		}
	}
	if q.getRepositoryByIDStmt != nil {
		if cerr := q.getRepositoryByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getRepositoryByIDStmt: %w", cerr)
		}
	}
	if q.getRepositoryByRootPathStmt != nil {
		if cerr := q.getRepositoryByRootPathStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getRepositoryByRootPathStmt: %w", cerr)
		}
	}
	if q.getSessionWithStatsStmt != nil {
		if cerr := q.getSessionWithStatsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getSessionWithStatsStmt: %w", cerr)
		}
	}
	if q.insertAgentEventStmt != nil {
		if cerr := q.insertAgentEventStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertAgentEventStmt: %w", cerr)
		}
	}
	if q.insertCheckpointStmt != nil {
		if cerr := q.insertCheckpointStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertCheckpointStmt: %w", cerr)
		}
	}
	if q.insertCommitLinkStmt != nil {
		if cerr := q.insertCommitLinkStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertCommitLinkStmt: %w", cerr)
		}
	}
	if q.insertRepositoryStmt != nil {
		if cerr := q.insertRepositoryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertRepositoryStmt: %w", cerr)
		}
	}
	if q.insertSessionCheckpointStmt != nil {
		if cerr := q.insertSessionCheckpointStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertSessionCheckpointStmt: %w", cerr)
		}
	}
	if q.listAgentEventsBySessionStmt != nil {
		if cerr := q.listAgentEventsBySessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listAgentEventsBySessionStmt: %w", cerr)
		}
	}
	if q.listBackfillReplayCandidatesStmt != nil {
		if cerr := q.listBackfillReplayCandidatesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listBackfillReplayCandidatesStmt: %w", cerr)
		}
	}
	if q.listCheckpointsByRepositoryStmt != nil {
		if cerr := q.listCheckpointsByRepositoryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listCheckpointsByRepositoryStmt: %w", cerr)
		}
	}
	if q.listCheckpointsWithCommitStmt != nil {
		if cerr := q.listCheckpointsWithCommitStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listCheckpointsWithCommitStmt: %w", cerr)
		}
	}
	if q.listCommitLinksByRepositoryStmt != nil {
		if cerr := q.listCommitLinksByRepositoryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listCommitLinksByRepositoryStmt: %w", cerr)
		}
	}
	if q.listCrossRepoSessionsStmt != nil {
		if cerr := q.listCrossRepoSessionsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listCrossRepoSessionsStmt: %w", cerr)
		}
	}
	if q.listDistinctProvidersStmt != nil {
		if cerr := q.listDistinctProvidersStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listDistinctProvidersStmt: %w", cerr)
		}
	}
	if q.listEventsBySessionASCStmt != nil {
		if cerr := q.listEventsBySessionASCStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listEventsBySessionASCStmt: %w", cerr)
		}
	}
	if q.listEventsInWindowStmt != nil {
		if cerr := q.listEventsInWindowStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listEventsInWindowStmt: %w", cerr)
		}
	}
	if q.listPackagedManifestsStmt != nil {
		if cerr := q.listPackagedManifestsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listPackagedManifestsStmt: %w", cerr)
		}
	}
	if q.listPendingManifestsStmt != nil {
		if cerr := q.listPendingManifestsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listPendingManifestsStmt: %w", cerr)
		}
	}
	if q.listProvidersByCheckpointStmt != nil {
		if cerr := q.listProvidersByCheckpointStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listProvidersByCheckpointStmt: %w", cerr)
		}
	}
	if q.listRecentAIPercentagesStmt != nil {
		if cerr := q.listRecentAIPercentagesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listRecentAIPercentagesStmt: %w", cerr)
		}
	}
	if q.listRecentSessionsWithStatsStmt != nil {
		if cerr := q.listRecentSessionsWithStatsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listRecentSessionsWithStatsStmt: %w", cerr)
		}
	}
	if q.listRepositoriesStmt != nil {
		if cerr := q.listRepositoriesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listRepositoriesStmt: %w", cerr)
		}
	}
	if q.listSessionsForCheckpointStmt != nil {
		if cerr := q.listSessionsForCheckpointStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listSessionsForCheckpointStmt: %w", cerr)
		}
	}
	if q.listSessionsForRepositoryStmt != nil {
		if cerr := q.listSessionsForRepositoryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listSessionsForRepositoryStmt: %w", cerr)
		}
	}
	if q.listSessionsWithEventsInWindowStmt != nil {
		if cerr := q.listSessionsWithEventsInWindowStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listSessionsWithEventsInWindowStmt: %w", cerr)
		}
	}
	if q.listSessionsWithStatsStmt != nil {
		if cerr := q.listSessionsWithStatsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listSessionsWithStatsStmt: %w", cerr)
		}
	}
	if q.listSessionsWithStatsAllStmt != nil {
		if cerr := q.listSessionsWithStatsAllStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listSessionsWithStatsAllStmt: %w", cerr)
		}
	}
	if q.listStalePendingCheckpointsStmt != nil {
		if cerr := q.listStalePendingCheckpointsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listStalePendingCheckpointsStmt: %w", cerr)
		}
	}
	if q.listStepCompanionResultsStmt != nil {
		if cerr := q.listStepCompanionResultsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listStepCompanionResultsStmt: %w", cerr)
		}
	}
	if q.listStepEventsForTurnStmt != nil {
		if cerr := q.listStepEventsForTurnStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listStepEventsForTurnStmt: %w", cerr)
		}
	}
	if q.listStepProvenanceForTurnStmt != nil {
		if cerr := q.listStepProvenanceForTurnStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listStepProvenanceForTurnStmt: %w", cerr)
		}
	}
	if q.listTranscriptEventsStmt != nil {
		if cerr := q.listTranscriptEventsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listTranscriptEventsStmt: %w", cerr)
		}
	}
	if q.markManifestFailedStmt != nil {
		if cerr := q.markManifestFailedStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing markManifestFailedStmt: %w", cerr)
		}
	}
	if q.markManifestUploadedStmt != nil {
		if cerr := q.markManifestUploadedStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing markManifestUploadedStmt: %w", cerr)
		}
	}
	if q.markManifestUploadingStmt != nil {
		if cerr := q.markManifestUploadingStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing markManifestUploadingStmt: %w", cerr)
		}
	}
	if q.promptEventExistsStmt != nil {
		if cerr := q.promptEventExistsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing promptEventExistsStmt: %w", cerr)
		}
	}
	if q.recordBackfillFailureStmt != nil {
		if cerr := q.recordBackfillFailureStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing recordBackfillFailureStmt: %w", cerr)
		}
	}
	if q.recoverStaleUploadingStmt != nil {
		if cerr := q.recoverStaleUploadingStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing recoverStaleUploadingStmt: %w", cerr)
		}
	}
	if q.resetManifestForRetryStmt != nil {
		if cerr := q.resetManifestForRetryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing resetManifestForRetryStmt: %w", cerr)
		}
	}
	if q.resetManifestToPackagedStmt != nil {
		if cerr := q.resetManifestToPackagedStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing resetManifestToPackagedStmt: %w", cerr)
		}
	}
	if q.resolveCheckpointByPrefixStmt != nil {
		if cerr := q.resolveCheckpointByPrefixStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing resolveCheckpointByPrefixStmt: %w", cerr)
		}
	}
	if q.resolveCommitLinkByPrefixStmt != nil {
		if cerr := q.resolveCommitLinkByPrefixStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing resolveCommitLinkByPrefixStmt: %w", cerr)
		}
	}
	if q.resolveSessionByPrefixStmt != nil {
		if cerr := q.resolveSessionByPrefixStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing resolveSessionByPrefixStmt: %w", cerr)
		}
	}
	if q.saveCheckpointSummaryStmt != nil {
		if cerr := q.saveCheckpointSummaryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing saveCheckpointSummaryStmt: %w", cerr)
		}
	}
	if q.stepEventExistsStmt != nil {
		if cerr := q.stepEventExistsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing stepEventExistsStmt: %w", cerr)
		}
	}
	if q.updateCheckpointAIPercentageStmt != nil {
		if cerr := q.updateCheckpointAIPercentageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateCheckpointAIPercentageStmt: %w", cerr)
		}
	}
	if q.updateRepositoryEnabledAtStmt != nil {
		if cerr := q.updateRepositoryEnabledAtStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateRepositoryEnabledAtStmt: %w", cerr)
		}
	}
	if q.upsertAgentSessionStmt != nil {
		if cerr := q.upsertAgentSessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertAgentSessionStmt: %w", cerr)
		}
	}
	if q.upsertAgentSourceStmt != nil {
		if cerr := q.upsertAgentSourceStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertAgentSourceStmt: %w", cerr)
		}
	}
	if q.upsertAttributionBackfillStmt != nil {
		if cerr := q.upsertAttributionBackfillStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertAttributionBackfillStmt: %w", cerr)
		}
	}
	if q.upsertCheckpointStatsStmt != nil {
		if cerr := q.upsertCheckpointStatsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertCheckpointStatsStmt: %w", cerr)
		}
	}
	if q.upsertProvenanceManifestStmt != nil {
		if cerr := q.upsertProvenanceManifestStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertProvenanceManifestStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                                    DBTX
	tx                                    *sql.Tx
	advanceBackfillCursorStmt             *sql.Stmt
	completeBackfillStmt                  *sql.Stmt
	completeCheckpointStmt                *sql.Stmt
	countCheckpointsWithSummaryStmt       *sql.Stmt
	countSessionsForCheckpointStmt        *sql.Stmt
	deleteCheckpointByIDStmt              *sql.Stmt
	failCheckpointStmt                    *sql.Stmt
	getActiveAgentSessionForRepoStmt      *sql.Stmt
	getAgentSessionByIDStmt               *sql.Stmt
	getAgentSessionByProviderIDStmt       *sql.Stmt
	getAttributionBackfillStmt            *sql.Stmt
	getCheckpointByIDStmt                 *sql.Stmt
	getCheckpointStatsStmt                *sql.Stmt
	getCheckpointSummaryStmt              *sql.Stmt
	getCommitLinkByCommitHashStmt         *sql.Stmt
	getCommitLinksByCheckpointStmt        *sql.Stmt
	getLatestCheckpointForRepoStmt        *sql.Stmt
	getLatestCommitLinkStmt               *sql.Stmt
	getManifestCommitLinkStmt             *sql.Stmt
	getNextToolResultAfterStmt            *sql.Stmt
	getPreviousCommitLinkedCheckpointStmt *sql.Stmt
	getPreviousCompletedCheckpointStmt    *sql.Stmt
	getPromptEventForTurnStmt             *sql.Stmt
	getRepositoryByIDStmt                 *sql.Stmt
	getRepositoryByRootPathStmt           *sql.Stmt
	getSessionWithStatsStmt               *sql.Stmt
	insertAgentEventStmt                  *sql.Stmt
	insertCheckpointStmt                  *sql.Stmt
	insertCommitLinkStmt                  *sql.Stmt
	insertRepositoryStmt                  *sql.Stmt
	insertSessionCheckpointStmt           *sql.Stmt
	listAgentEventsBySessionStmt          *sql.Stmt
	listBackfillReplayCandidatesStmt      *sql.Stmt
	listCheckpointsByRepositoryStmt       *sql.Stmt
	listCheckpointsWithCommitStmt         *sql.Stmt
	listCommitLinksByRepositoryStmt       *sql.Stmt
	listCrossRepoSessionsStmt             *sql.Stmt
	listDistinctProvidersStmt             *sql.Stmt
	listEventsBySessionASCStmt            *sql.Stmt
	listEventsInWindowStmt                *sql.Stmt
	listPackagedManifestsStmt             *sql.Stmt
	listPendingManifestsStmt              *sql.Stmt
	listProvidersByCheckpointStmt         *sql.Stmt
	listRecentAIPercentagesStmt           *sql.Stmt
	listRecentSessionsWithStatsStmt       *sql.Stmt
	listRepositoriesStmt                  *sql.Stmt
	listSessionsForCheckpointStmt         *sql.Stmt
	listSessionsForRepositoryStmt         *sql.Stmt
	listSessionsWithEventsInWindowStmt    *sql.Stmt
	listSessionsWithStatsStmt             *sql.Stmt
	listSessionsWithStatsAllStmt          *sql.Stmt
	listStalePendingCheckpointsStmt       *sql.Stmt
	listStepCompanionResultsStmt          *sql.Stmt
	listStepEventsForTurnStmt             *sql.Stmt
	listStepProvenanceForTurnStmt         *sql.Stmt
	listTranscriptEventsStmt              *sql.Stmt
	markManifestFailedStmt                *sql.Stmt
	markManifestUploadedStmt              *sql.Stmt
	markManifestUploadingStmt             *sql.Stmt
	promptEventExistsStmt                 *sql.Stmt
	recordBackfillFailureStmt             *sql.Stmt
	recoverStaleUploadingStmt             *sql.Stmt
	resetManifestForRetryStmt             *sql.Stmt
	resetManifestToPackagedStmt           *sql.Stmt
	resolveCheckpointByPrefixStmt         *sql.Stmt
	resolveCommitLinkByPrefixStmt         *sql.Stmt
	resolveSessionByPrefixStmt            *sql.Stmt
	saveCheckpointSummaryStmt             *sql.Stmt
	stepEventExistsStmt                   *sql.Stmt
	updateCheckpointAIPercentageStmt      *sql.Stmt
	updateRepositoryEnabledAtStmt         *sql.Stmt
	upsertAgentSessionStmt                *sql.Stmt
	upsertAgentSourceStmt                 *sql.Stmt
	upsertAttributionBackfillStmt         *sql.Stmt
	upsertCheckpointStatsStmt             *sql.Stmt
	upsertProvenanceManifestStmt          *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                                    tx,
		tx:                                    tx,
		advanceBackfillCursorStmt:             q.advanceBackfillCursorStmt,
		completeBackfillStmt:                  q.completeBackfillStmt,
		completeCheckpointStmt:                q.completeCheckpointStmt,
		countCheckpointsWithSummaryStmt:       q.countCheckpointsWithSummaryStmt,
		countSessionsForCheckpointStmt:        q.countSessionsForCheckpointStmt,
		deleteCheckpointByIDStmt:              q.deleteCheckpointByIDStmt,
		failCheckpointStmt:                    q.failCheckpointStmt,
		getActiveAgentSessionForRepoStmt:      q.getActiveAgentSessionForRepoStmt,
		getAgentSessionByIDStmt:               q.getAgentSessionByIDStmt,
		getAgentSessionByProviderIDStmt:       q.getAgentSessionByProviderIDStmt,
		getAttributionBackfillStmt:            q.getAttributionBackfillStmt,
		getCheckpointByIDStmt:                 q.getCheckpointByIDStmt,
		getCheckpointStatsStmt:                q.getCheckpointStatsStmt,
		getCheckpointSummaryStmt:              q.getCheckpointSummaryStmt,
		getCommitLinkByCommitHashStmt:         q.getCommitLinkByCommitHashStmt,
		getCommitLinksByCheckpointStmt:        q.getCommitLinksByCheckpointStmt,
		getLatestCheckpointForRepoStmt:        q.getLatestCheckpointForRepoStmt,
		getLatestCommitLinkStmt:               q.getLatestCommitLinkStmt,
		getManifestCommitLinkStmt:             q.getManifestCommitLinkStmt,
		getNextToolResultAfterStmt:            q.getNextToolResultAfterStmt,
		getPreviousCommitLinkedCheckpointStmt: q.getPreviousCommitLinkedCheckpointStmt,
		getPreviousCompletedCheckpointStmt:    q.getPreviousCompletedCheckpointStmt,
		getPromptEventForTurnStmt:             q.getPromptEventForTurnStmt,
		getRepositoryByIDStmt:                 q.getRepositoryByIDStmt,
		getRepositoryByRootPathStmt:           q.getRepositoryByRootPathStmt,
		getSessionWithStatsStmt:               q.getSessionWithStatsStmt,
		insertAgentEventStmt:                  q.insertAgentEventStmt,
		insertCheckpointStmt:                  q.insertCheckpointStmt,
		insertCommitLinkStmt:                  q.insertCommitLinkStmt,
		insertRepositoryStmt:                  q.insertRepositoryStmt,
		insertSessionCheckpointStmt:           q.insertSessionCheckpointStmt,
		listAgentEventsBySessionStmt:          q.listAgentEventsBySessionStmt,
		listBackfillReplayCandidatesStmt:      q.listBackfillReplayCandidatesStmt,
		listCheckpointsByRepositoryStmt:       q.listCheckpointsByRepositoryStmt,
		listCheckpointsWithCommitStmt:         q.listCheckpointsWithCommitStmt,
		listCommitLinksByRepositoryStmt:       q.listCommitLinksByRepositoryStmt,
		listCrossRepoSessionsStmt:             q.listCrossRepoSessionsStmt,
		listDistinctProvidersStmt:             q.listDistinctProvidersStmt,
		listEventsBySessionASCStmt:            q.listEventsBySessionASCStmt,
		listEventsInWindowStmt:                q.listEventsInWindowStmt,
		listPackagedManifestsStmt:             q.listPackagedManifestsStmt,
		listPendingManifestsStmt:              q.listPendingManifestsStmt,
		listProvidersByCheckpointStmt:         q.listProvidersByCheckpointStmt,
		listRecentAIPercentagesStmt:           q.listRecentAIPercentagesStmt,
		listRecentSessionsWithStatsStmt:       q.listRecentSessionsWithStatsStmt,
		listRepositoriesStmt:                  q.listRepositoriesStmt,
		listSessionsForCheckpointStmt:         q.listSessionsForCheckpointStmt,
		listSessionsForRepositoryStmt:         q.listSessionsForRepositoryStmt,
		listSessionsWithEventsInWindowStmt:    q.listSessionsWithEventsInWindowStmt,
		listSessionsWithStatsStmt:             q.listSessionsWithStatsStmt,
		listSessionsWithStatsAllStmt:          q.listSessionsWithStatsAllStmt,
		listStalePendingCheckpointsStmt:       q.listStalePendingCheckpointsStmt,
		listStepCompanionResultsStmt:          q.listStepCompanionResultsStmt,
		listStepEventsForTurnStmt:             q.listStepEventsForTurnStmt,
		listStepProvenanceForTurnStmt:         q.listStepProvenanceForTurnStmt,
		listTranscriptEventsStmt:              q.listTranscriptEventsStmt,
		markManifestFailedStmt:                q.markManifestFailedStmt,
		markManifestUploadedStmt:              q.markManifestUploadedStmt,
		markManifestUploadingStmt:             q.markManifestUploadingStmt,
		promptEventExistsStmt:                 q.promptEventExistsStmt,
		recordBackfillFailureStmt:             q.recordBackfillFailureStmt,
		recoverStaleUploadingStmt:             q.recoverStaleUploadingStmt,
		resetManifestForRetryStmt:             q.resetManifestForRetryStmt,
		resetManifestToPackagedStmt:           q.resetManifestToPackagedStmt,
		resolveCheckpointByPrefixStmt:         q.resolveCheckpointByPrefixStmt,
		resolveCommitLinkByPrefixStmt:         q.resolveCommitLinkByPrefixStmt,
		resolveSessionByPrefixStmt:            q.resolveSessionByPrefixStmt,
		saveCheckpointSummaryStmt:             q.saveCheckpointSummaryStmt,
		stepEventExistsStmt:                   q.stepEventExistsStmt,
		updateCheckpointAIPercentageStmt:      q.updateCheckpointAIPercentageStmt,
		updateRepositoryEnabledAtStmt:         q.updateRepositoryEnabledAtStmt,
		upsertAgentSessionStmt:                q.upsertAgentSessionStmt,
		upsertAgentSourceStmt:                 q.upsertAgentSourceStmt,
		upsertAttributionBackfillStmt:         q.upsertAttributionBackfillStmt,
		upsertCheckpointStatsStmt:             q.upsertCheckpointStatsStmt,
		upsertProvenanceManifestStmt:          q.upsertProvenanceManifestStmt,
	}
}
