// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: evidence_links.sql

package db

import (
	"context"
)

const getEvidenceLink = `-- name: GetEvidenceLink :one
select event_id, evidence_kind, evidence_hash, group_id, created_at from agent_event_evidence_links
where event_id = ? and evidence_kind = ? and group_id = ?
`

type GetEvidenceLinkParams struct {
	EventID      string `json:"event_id"`
	EvidenceKind string `json:"evidence_kind"`
	GroupID      string `json:"group_id"`
}

func (q *Queries) GetEvidenceLink(ctx context.Context, arg GetEvidenceLinkParams) (AgentEventEvidenceLink, error) {
	row := q.queryRow(ctx, q.getEvidenceLinkStmt, getEvidenceLink, arg.EventID, arg.EvidenceKind, arg.GroupID)
	var i AgentEventEvidenceLink
	err := row.Scan(
		&i.EventID,
		&i.EvidenceKind,
		&i.EvidenceHash,
		&i.GroupID,
		&i.CreatedAt,
	)
	return i, err
}

const insertEvidenceLinkIfAbsent = `-- name: InsertEvidenceLinkIfAbsent :exec
insert into agent_event_evidence_links (event_id, evidence_kind, evidence_hash, group_id, created_at)
values (?, ?, ?, ?, ?)
on conflict (event_id, evidence_kind, group_id) do nothing
`

type InsertEvidenceLinkIfAbsentParams struct {
	EventID      string `json:"event_id"`
	EvidenceKind string `json:"evidence_kind"`
	EvidenceHash string `json:"evidence_hash"`
	GroupID      string `json:"group_id"`
	CreatedAt    int64  `json:"created_at"`
}

// Idempotent creation half; the caller re-reads the row and fails closed
// on an evidence hash mismatch instead of overwriting it.
func (q *Queries) InsertEvidenceLinkIfAbsent(ctx context.Context, arg InsertEvidenceLinkIfAbsentParams) error {
	_, err := q.exec(ctx, q.insertEvidenceLinkIfAbsentStmt, insertEvidenceLinkIfAbsent,
		arg.EventID,
		arg.EvidenceKind,
		arg.EvidenceHash,
		arg.GroupID,
		arg.CreatedAt,
	)
	return err
}

const listEvidenceLinksByEvent = `-- name: ListEvidenceLinksByEvent :many
select event_id, evidence_kind, evidence_hash, group_id, created_at from agent_event_evidence_links
where event_id = ? order by evidence_kind, group_id
`

func (q *Queries) ListEvidenceLinksByEvent(ctx context.Context, eventID string) ([]AgentEventEvidenceLink, error) {
	rows, err := q.query(ctx, q.listEvidenceLinksByEventStmt, listEvidenceLinksByEvent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentEventEvidenceLink{}
	for rows.Next() {
		var i AgentEventEvidenceLink
		if err := rows.Scan(
			&i.EventID,
			&i.EvidenceKind,
			&i.EvidenceHash,
			&i.GroupID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEvidenceLinksByGroup = `-- name: ListEvidenceLinksByGroup :many
select event_id, evidence_kind, evidence_hash, group_id, created_at from agent_event_evidence_links
where group_id = ? order by event_id
`

func (q *Queries) ListEvidenceLinksByGroup(ctx context.Context, groupID string) ([]AgentEventEvidenceLink, error) {
	rows, err := q.query(ctx, q.listEvidenceLinksByGroupStmt, listEvidenceLinksByGroup, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentEventEvidenceLink{}
	for rows.Next() {
		var i AgentEventEvidenceLink
		if err := rows.Scan(
			&i.EventID,
			&i.EvidenceKind,
			&i.EvidenceHash,
			&i.GroupID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
