// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: evidence_links.sql

package db

import (
	"context"
	"database/sql"
)

const agentEventExists = `-- name: AgentEventExists :one
select count(*) > 0 as exists_flag from agent_events
where event_id = ?
`

func (q *Queries) AgentEventExists(ctx context.Context, eventID string) (bool, error) {
	row := q.queryRow(ctx, q.agentEventExistsStmt, agentEventExists, eventID)
	var exists_flag bool
	err := row.Scan(&exists_flag)
	return exists_flag, err
}

const getEvidenceLink = `-- name: GetEvidenceLink :one
select event_id, evidence_kind, evidence_hash, group_id, created_at from agent_event_evidence_links
where event_id = ? and evidence_kind = ? and group_id = ?
`

type GetEvidenceLinkParams struct {
	EventID      string `json:"event_id"`
	EvidenceKind string `json:"evidence_kind"`
	GroupID      string `json:"group_id"`
}

func (q *Queries) GetEvidenceLink(ctx context.Context, arg GetEvidenceLinkParams) (AgentEventEvidenceLink, error) {
	row := q.queryRow(ctx, q.getEvidenceLinkStmt, getEvidenceLink, arg.EventID, arg.EvidenceKind, arg.GroupID)
	var i AgentEventEvidenceLink
	err := row.Scan(
		&i.EventID,
		&i.EvidenceKind,
		&i.EvidenceHash,
		&i.GroupID,
		&i.CreatedAt,
	)
	return i, err
}

const insertEvidenceLinkIfAbsent = `-- name: InsertEvidenceLinkIfAbsent :exec
insert into agent_event_evidence_links (event_id, evidence_kind, evidence_hash, group_id, created_at)
values (?, ?, ?, ?, ?)
on conflict (event_id, evidence_kind, group_id) do nothing
`

type InsertEvidenceLinkIfAbsentParams struct {
	EventID      string `json:"event_id"`
	EvidenceKind string `json:"evidence_kind"`
	EvidenceHash string `json:"evidence_hash"`
	GroupID      string `json:"group_id"`
	CreatedAt    int64  `json:"created_at"`
}

// Idempotent creation half; the caller re-reads the row and fails closed
// on an evidence hash mismatch instead of overwriting it.
func (q *Queries) InsertEvidenceLinkIfAbsent(ctx context.Context, arg InsertEvidenceLinkIfAbsentParams) error {
	_, err := q.exec(ctx, q.insertEvidenceLinkIfAbsentStmt, insertEvidenceLinkIfAbsent,
		arg.EventID,
		arg.EvidenceKind,
		arg.EvidenceHash,
		arg.GroupID,
		arg.CreatedAt,
	)
	return err
}

const listEvidenceLinksByEvent = `-- name: ListEvidenceLinksByEvent :many
select event_id, evidence_kind, evidence_hash, group_id, created_at from agent_event_evidence_links
where event_id = ? order by evidence_kind, group_id
`

func (q *Queries) ListEvidenceLinksByEvent(ctx context.Context, eventID string) ([]AgentEventEvidenceLink, error) {
	rows, err := q.query(ctx, q.listEvidenceLinksByEventStmt, listEvidenceLinksByEvent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentEventEvidenceLink{}
	for rows.Next() {
		var i AgentEventEvidenceLink
		if err := rows.Scan(
			&i.EventID,
			&i.EvidenceKind,
			&i.EvidenceHash,
			&i.GroupID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEvidenceLinksByGroup = `-- name: ListEvidenceLinksByGroup :many
select event_id, evidence_kind, evidence_hash, group_id, created_at from agent_event_evidence_links
where group_id = ? order by event_id
`

func (q *Queries) ListEvidenceLinksByGroup(ctx context.Context, groupID string) ([]AgentEventEvidenceLink, error) {
	rows, err := q.query(ctx, q.listEvidenceLinksByGroupStmt, listEvidenceLinksByGroup, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentEventEvidenceLink{}
	for rows.Next() {
		var i AgentEventEvidenceLink
		if err := rows.Scan(
			&i.EventID,
			&i.EvidenceKind,
			&i.EvidenceHash,
			&i.GroupID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEvidenceLinksInWindow = `-- name: ListEvidenceLinksInWindow :many
select
    l.event_id,
    l.evidence_hash,
    l.group_id,
    s.provider
from agent_event_evidence_links l
    join agent_events e on e.event_id = l.event_id
    join agent_sessions s
        on s.session_id = e.session_id
        and s.repository_id = e.repository_id
where e.repository_id = ?
    and l.evidence_kind = 'tool_delta'
    and ((cast(?2 as integer) = 1
            and (e.ts > ?3
                 or (e.ts = ?3 and e.insert_seq > ?4))
            and (e.ts < ?5
                 or (e.ts = ?5 and e.insert_seq <= ?6)))
         or (cast(?2 as integer) = 0
            and e.ts > ?3 and e.ts <= ?5))
order by e.ts, e.insert_seq, l.event_id
`

type ListEvidenceLinksInWindowParams struct {
	RepositoryID string        `json:"repository_id"`
	UseCursor    int64         `json:"use_cursor"`
	AfterTs      int64         `json:"after_ts"`
	AfterCursor  sql.NullInt64 `json:"after_cursor"`
	UpToTs       int64         `json:"up_to_ts"`
	UpToCursor   sql.NullInt64 `json:"up_to_cursor"`
}

type ListEvidenceLinksInWindowRow struct {
	EventID      string `json:"event_id"`
	EvidenceHash string `json:"evidence_hash"`
	GroupID      string `json:"group_id"`
	Provider     string `json:"provider"`
}

// Lists tool-delta links and session providers in event-window order.
func (q *Queries) ListEvidenceLinksInWindow(ctx context.Context, arg ListEvidenceLinksInWindowParams) ([]ListEvidenceLinksInWindowRow, error) {
	rows, err := q.query(ctx, q.listEvidenceLinksInWindowStmt, listEvidenceLinksInWindow,
		arg.RepositoryID,
		arg.UseCursor,
		arg.AfterTs,
		arg.AfterCursor,
		arg.UpToTs,
		arg.UpToCursor,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEvidenceLinksInWindowRow{}
	for rows.Next() {
		var i ListEvidenceLinksInWindowRow
		if err := rows.Scan(
			&i.EventID,
			&i.EvidenceHash,
			&i.GroupID,
			&i.Provider,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
