// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"database/sql"
)

type AgentEvent struct {
	EventID           string         `json:"event_id"`
	SessionID         string         `json:"session_id"`
	RepositoryID      string         `json:"repository_id"`
	Ts                int64          `json:"ts"`
	Kind              string         `json:"kind"`
	PayloadHash       sql.NullString `json:"payload_hash"`
	Role              sql.NullString `json:"role"`
	ToolUses          sql.NullString `json:"tool_uses"`
	TokensIn          sql.NullInt64  `json:"tokens_in"`
	TokensOut         sql.NullInt64  `json:"tokens_out"`
	TokensCacheRead   sql.NullInt64  `json:"tokens_cache_read"`
	TokensCacheCreate sql.NullInt64  `json:"tokens_cache_create"`
	Summary           sql.NullString `json:"summary"`
	ProviderEventID   sql.NullString `json:"provider_event_id"`
	TurnID            sql.NullString `json:"turn_id"`
	ToolUseID         sql.NullString `json:"tool_use_id"`
	ToolName          sql.NullString `json:"tool_name"`
	EventSource       string         `json:"event_source"`
	ProvenanceHash    sql.NullString `json:"provenance_hash"`
}

type AgentSession struct {
	SessionID         string         `json:"session_id"`
	ProviderSessionID string         `json:"provider_session_id"`
	ParentSessionID   sql.NullString `json:"parent_session_id"`
	RepositoryID      string         `json:"repository_id"`
	Provider          string         `json:"provider"`
	SourceID          string         `json:"source_id"`
	StartedAt         int64          `json:"started_at"`
	LastSeenAt        int64          `json:"last_seen_at"`
	MetadataJson      string         `json:"metadata_json"`
	SourceRepoPath    sql.NullString `json:"source_repo_path"`
	Model             sql.NullString `json:"model"`
}

type AgentSource struct {
	SourceID     string `json:"source_id"`
	RepositoryID string `json:"repository_id"`
	Provider     string `json:"provider"`
	SourceKey    string `json:"source_key"`
	LastSeenAt   int64  `json:"last_seen_at"`
	CreatedAt    int64  `json:"created_at"`
}

type Checkpoint struct {
	CheckpointID string         `json:"checkpoint_id"`
	RepositoryID string         `json:"repository_id"`
	CreatedAt    int64          `json:"created_at"`
	Kind         string         `json:"kind"`
	Trigger      sql.NullString `json:"trigger"`
	Message      sql.NullString `json:"message"`
	ManifestHash sql.NullString `json:"manifest_hash"`
	SizeBytes    sql.NullInt64  `json:"size_bytes"`
	Status       string         `json:"status"`
	CompletedAt  sql.NullInt64  `json:"completed_at"`
	SummaryJson  sql.NullString `json:"summary_json"`
	SummaryModel sql.NullString `json:"summary_model"`
}

type CheckpointStat struct {
	CheckpointID string  `json:"checkpoint_id"`
	SessionCount int64   `json:"session_count"`
	FilesChanged int64   `json:"files_changed"`
	AiPercentage float64 `json:"ai_percentage"`
}

type CommitLink struct {
	CommitHash   string `json:"commit_hash"`
	RepositoryID string `json:"repository_id"`
	CheckpointID string `json:"checkpoint_id"`
	LinkedAt     int64  `json:"linked_at"`
}

type ProvenanceManifest struct {
	ManifestID             string         `json:"manifest_id"`
	RepositoryID           string         `json:"repository_id"`
	SessionID              string         `json:"session_id"`
	TurnID                 string         `json:"turn_id"`
	Provider               string         `json:"provider"`
	Kind                   string         `json:"kind"`
	TranscriptRef          sql.NullString `json:"transcript_ref"`
	ProvenanceBundleHash   sql.NullString `json:"provenance_bundle_hash"`
	StartedAt              int64          `json:"started_at"`
	CompletedAt            sql.NullInt64  `json:"completed_at"`
	Status                 string         `json:"status"`
	UploadAttempts         int64          `json:"upload_attempts"`
	LastError              sql.NullString `json:"last_error"`
	UploadTransformVersion sql.NullInt64  `json:"upload_transform_version"`
	RemoteVerifiedAt       sql.NullInt64  `json:"remote_verified_at"`
	CreatedAt              int64          `json:"created_at"`
	UpdatedAt              int64          `json:"updated_at"`
}

type RemoteAttributionBackfill struct {
	ConnectedRepoID  string         `json:"connected_repo_id"`
	RepositoryID     string         `json:"repository_id"`
	CutoffLinkedAt   int64          `json:"cutoff_linked_at"`
	CutoffCommitHash string         `json:"cutoff_commit_hash"`
	CursorLinkedAt   int64          `json:"cursor_linked_at"`
	CursorCommitHash string         `json:"cursor_commit_hash"`
	Status           string         `json:"status"`
	FailedCommitHash sql.NullString `json:"failed_commit_hash"`
	RetryAttempts    int64          `json:"retry_attempts"`
	LastError        sql.NullString `json:"last_error"`
	UpdatedAt        int64          `json:"updated_at"`
}

type Repository struct {
	RepositoryID string `json:"repository_id"`
	RootPath     string `json:"root_path"`
	CreatedAt    int64  `json:"created_at"`
	EnabledAt    int64  `json:"enabled_at"`
}

type SessionCheckpoint struct {
	SessionID    string `json:"session_id"`
	CheckpointID string `json:"checkpoint_id"`
}
