// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: repositories.sql

package db

import (
	"context"
)

const getRepositoryByID = `-- name: GetRepositoryByID :one
select repository_id, root_path, created_at, enabled_at from repositories where repository_id = ?
`

func (q *Queries) GetRepositoryByID(ctx context.Context, repositoryID string) (Repository, error) {
	row := q.queryRow(ctx, q.getRepositoryByIDStmt, getRepositoryByID, repositoryID)
	var i Repository
	err := row.Scan(
		&i.RepositoryID,
		&i.RootPath,
		&i.CreatedAt,
		&i.EnabledAt,
	)
	return i, err
}

const getRepositoryByRootPath = `-- name: GetRepositoryByRootPath :one
select repository_id, root_path, created_at, enabled_at from repositories where root_path = ?
`

func (q *Queries) GetRepositoryByRootPath(ctx context.Context, rootPath string) (Repository, error) {
	row := q.queryRow(ctx, q.getRepositoryByRootPathStmt, getRepositoryByRootPath, rootPath)
	var i Repository
	err := row.Scan(
		&i.RepositoryID,
		&i.RootPath,
		&i.CreatedAt,
		&i.EnabledAt,
	)
	return i, err
}

const insertRepository = `-- name: InsertRepository :exec
insert into repositories(repository_id, root_path, created_at, enabled_at)
values (?, ?, ?, ?)
`

type InsertRepositoryParams struct {
	RepositoryID string `json:"repository_id"`
	RootPath     string `json:"root_path"`
	CreatedAt    int64  `json:"created_at"`
	EnabledAt    int64  `json:"enabled_at"`
}

func (q *Queries) InsertRepository(ctx context.Context, arg InsertRepositoryParams) error {
	_, err := q.exec(ctx, q.insertRepositoryStmt, insertRepository,
		arg.RepositoryID,
		arg.RootPath,
		arg.CreatedAt,
		arg.EnabledAt,
	)
	return err
}

const listRepositories = `-- name: ListRepositories :many
select repository_id, root_path, created_at, enabled_at from repositories order by created_at desc
`

func (q *Queries) ListRepositories(ctx context.Context) ([]Repository, error) {
	rows, err := q.query(ctx, q.listRepositoriesStmt, listRepositories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Repository{}
	for rows.Next() {
		var i Repository
		if err := rows.Scan(
			&i.RepositoryID,
			&i.RootPath,
			&i.CreatedAt,
			&i.EnabledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRepositoryEnabledAt = `-- name: UpdateRepositoryEnabledAt :exec
update repositories set enabled_at = ? where repository_id = ?
`

type UpdateRepositoryEnabledAtParams struct {
	EnabledAt    int64  `json:"enabled_at"`
	RepositoryID string `json:"repository_id"`
}

func (q *Queries) UpdateRepositoryEnabledAt(ctx context.Context, arg UpdateRepositoryEnabledAtParams) error {
	_, err := q.exec(ctx, q.updateRepositoryEnabledAtStmt, updateRepositoryEnabledAt, arg.EnabledAt, arg.RepositoryID)
	return err
}
