// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transcripts.sql

package db

import (
	"context"
	"database/sql"
)

const listEventsInWindow = `-- name: ListEventsInWindow :many
select
    e.event_id,
    e.session_id,
    s.provider,
    s.model,
    e.ts,
    e.kind,
    e.role,
    e.tool_uses,
    e.tokens_in,
    e.tokens_out,
    e.tokens_cache_read,
    e.tokens_cache_create,
    e.summary,
    e.provider_event_id,
    e.payload_hash,
    e.insert_seq
from agent_events e
    join agent_sessions s on s.session_id = e.session_id
where e.repository_id = ?
    and ((cast(?2 as integer) = 1
            and (e.ts > ?3
                 or (e.ts = ?3 and e.insert_seq > ?4))
            and (e.ts < ?5
                 or (e.ts = ?5 and e.insert_seq <= ?6)))
         or (cast(?2 as integer) = 0
            and e.ts > ?3 and e.ts <= ?5))
order by e.ts, e.event_id
`

type ListEventsInWindowParams struct {
	RepositoryID string        `json:"repository_id"`
	UseCursor    int64         `json:"use_cursor"`
	AfterTs      int64         `json:"after_ts"`
	AfterCursor  sql.NullInt64 `json:"after_cursor"`
	UpToTs       int64         `json:"up_to_ts"`
	UpToCursor   sql.NullInt64 `json:"up_to_cursor"`
}

type ListEventsInWindowRow struct {
	EventID           string         `json:"event_id"`
	SessionID         string         `json:"session_id"`
	Provider          string         `json:"provider"`
	Model             sql.NullString `json:"model"`
	Ts                int64          `json:"ts"`
	Kind              string         `json:"kind"`
	Role              sql.NullString `json:"role"`
	ToolUses          sql.NullString `json:"tool_uses"`
	TokensIn          sql.NullInt64  `json:"tokens_in"`
	TokensOut         sql.NullInt64  `json:"tokens_out"`
	TokensCacheRead   sql.NullInt64  `json:"tokens_cache_read"`
	TokensCacheCreate sql.NullInt64  `json:"tokens_cache_create"`
	Summary           sql.NullString `json:"summary"`
	ProviderEventID   sql.NullString `json:"provider_event_id"`
	PayloadHash       sql.NullString `json:"payload_hash"`
	InsertSeq         sql.NullInt64  `json:"insert_seq"`
}

// Returns all events for a repository within a time window, without
// requiring session_checkpoints links. Used by attribution to query
// events directly by repository and time range. insert_seq feeds
// deterministic winner selection for equal-quality evidence.
func (q *Queries) ListEventsInWindow(ctx context.Context, arg ListEventsInWindowParams) ([]ListEventsInWindowRow, error) {
	rows, err := q.query(ctx, q.listEventsInWindowStmt, listEventsInWindow,
		arg.RepositoryID,
		arg.UseCursor,
		arg.AfterTs,
		arg.AfterCursor,
		arg.UpToTs,
		arg.UpToCursor,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEventsInWindowRow{}
	for rows.Next() {
		var i ListEventsInWindowRow
		if err := rows.Scan(
			&i.EventID,
			&i.SessionID,
			&i.Provider,
			&i.Model,
			&i.Ts,
			&i.Kind,
			&i.Role,
			&i.ToolUses,
			&i.TokensIn,
			&i.TokensOut,
			&i.TokensCacheRead,
			&i.TokensCacheCreate,
			&i.Summary,
			&i.ProviderEventID,
			&i.PayloadHash,
			&i.InsertSeq,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsInWindowForAnnotations = `-- name: ListEventsInWindowForAnnotations :many
select
    e.event_id,
    e.session_id,
    s.provider,
    e.ts,
    e.role,
    e.tool_uses,
    e.turn_id,
    e.tool_name,
    e.payload_hash,
    e.provenance_hash
from agent_events e
    join agent_sessions s on s.session_id = e.session_id
where e.repository_id = ?
    and ((cast(?2 as integer) = 1
            and (e.ts > ?3
                 or (e.ts = ?3 and e.insert_seq > ?4))
            and (e.ts < ?5
                 or (e.ts = ?5 and e.insert_seq <= ?6)))
         or (cast(?2 as integer) = 0
            and e.ts > ?3 and e.ts <= ?5))
order by e.ts, e.event_id
`

type ListEventsInWindowForAnnotationsParams struct {
	RepositoryID string        `json:"repository_id"`
	UseCursor    int64         `json:"use_cursor"`
	AfterTs      int64         `json:"after_ts"`
	AfterCursor  sql.NullInt64 `json:"after_cursor"`
	UpToTs       int64         `json:"up_to_ts"`
	UpToCursor   sql.NullInt64 `json:"up_to_cursor"`
}

type ListEventsInWindowForAnnotationsRow struct {
	EventID        string         `json:"event_id"`
	SessionID      string         `json:"session_id"`
	Provider       string         `json:"provider"`
	Ts             int64          `json:"ts"`
	Role           sql.NullString `json:"role"`
	ToolUses       sql.NullString `json:"tool_uses"`
	TurnID         sql.NullString `json:"turn_id"`
	ToolName       sql.NullString `json:"tool_name"`
	PayloadHash    sql.NullString `json:"payload_hash"`
	ProvenanceHash sql.NullString `json:"provenance_hash"`
}

// Returns events for a repository within a time window with the turn and
// provenance fields the timeline-annotation detector needs (turn_id and
// provenance_hash) alongside the payload pointer. Ordered chronologically so
// the detector can reason about authored-then-revised / authored-then-removed
// sequences directly.
func (q *Queries) ListEventsInWindowForAnnotations(ctx context.Context, arg ListEventsInWindowForAnnotationsParams) ([]ListEventsInWindowForAnnotationsRow, error) {
	rows, err := q.query(ctx, q.listEventsInWindowForAnnotationsStmt, listEventsInWindowForAnnotations,
		arg.RepositoryID,
		arg.UseCursor,
		arg.AfterTs,
		arg.AfterCursor,
		arg.UpToTs,
		arg.UpToCursor,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEventsInWindowForAnnotationsRow{}
	for rows.Next() {
		var i ListEventsInWindowForAnnotationsRow
		if err := rows.Scan(
			&i.EventID,
			&i.SessionID,
			&i.Provider,
			&i.Ts,
			&i.Role,
			&i.ToolUses,
			&i.TurnID,
			&i.ToolName,
			&i.PayloadHash,
			&i.ProvenanceHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTranscriptEvents = `-- name: ListTranscriptEvents :many
select
    e.event_id, e.session_id, s.provider,
    e.ts, e.kind, e.role, e.tool_uses,
    e.tokens_in, e.tokens_out, e.tokens_cache_read, e.tokens_cache_create,
    e.summary, e.provider_event_id, e.payload_hash
from agent_events e
    join agent_sessions s on s.session_id = e.session_id
where e.repository_id = ?
    and ((cast(?2 as integer) = 1
            and (e.ts > ?3
                 or (e.ts = ?3 and e.insert_seq > ?4))
            and (e.ts < ?5
                 or (e.ts = ?5 and e.insert_seq <= ?6)))
         or (cast(?2 as integer) = 0
            and e.ts > ?3 and e.ts <= ?5))
order by e.ts, s.provider, e.session_id, e.event_id
`

type ListTranscriptEventsParams struct {
	RepositoryID string        `json:"repository_id"`
	UseCursor    int64         `json:"use_cursor"`
	AfterTs      int64         `json:"after_ts"`
	AfterCursor  sql.NullInt64 `json:"after_cursor"`
	UntilTs      int64         `json:"until_ts"`
	UpToCursor   sql.NullInt64 `json:"up_to_cursor"`
}

type ListTranscriptEventsRow struct {
	EventID           string         `json:"event_id"`
	SessionID         string         `json:"session_id"`
	Provider          string         `json:"provider"`
	Ts                int64          `json:"ts"`
	Kind              string         `json:"kind"`
	Role              sql.NullString `json:"role"`
	ToolUses          sql.NullString `json:"tool_uses"`
	TokensIn          sql.NullInt64  `json:"tokens_in"`
	TokensOut         sql.NullInt64  `json:"tokens_out"`
	TokensCacheRead   sql.NullInt64  `json:"tokens_cache_read"`
	TokensCacheCreate sql.NullInt64  `json:"tokens_cache_create"`
	Summary           sql.NullString `json:"summary"`
	ProviderEventID   sql.NullString `json:"provider_event_id"`
	PayloadHash       sql.NullString `json:"payload_hash"`
}

func (q *Queries) ListTranscriptEvents(ctx context.Context, arg ListTranscriptEventsParams) ([]ListTranscriptEventsRow, error) {
	rows, err := q.query(ctx, q.listTranscriptEventsStmt, listTranscriptEvents,
		arg.RepositoryID,
		arg.UseCursor,
		arg.AfterTs,
		arg.AfterCursor,
		arg.UntilTs,
		arg.UpToCursor,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTranscriptEventsRow{}
	for rows.Next() {
		var i ListTranscriptEventsRow
		if err := rows.Scan(
			&i.EventID,
			&i.SessionID,
			&i.Provider,
			&i.Ts,
			&i.Kind,
			&i.Role,
			&i.ToolUses,
			&i.TokensIn,
			&i.TokensOut,
			&i.TokensCacheRead,
			&i.TokensCacheCreate,
			&i.Summary,
			&i.ProviderEventID,
			&i.PayloadHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
