// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: branches.sql

package db

import (
	"context"
)

const deleteBranchesForImplementation = `-- name: DeleteBranchesForImplementation :exec
delete from implementation_branches where implementation_id = ?
`

func (q *Queries) DeleteBranchesForImplementation(ctx context.Context, implementationID string) error {
	_, err := q.exec(ctx, q.deleteBranchesForImplementationStmt, deleteBranchesForImplementation, implementationID)
	return err
}

const deleteBranchesForRepo = `-- name: DeleteBranchesForRepo :exec
delete from implementation_branches
where implementation_id = ? and canonical_path = ?
`

type DeleteBranchesForRepoParams struct {
	ImplementationID string `json:"implementation_id"`
	CanonicalPath    string `json:"canonical_path"`
}

// Remove all branch rows for a specific repo in an implementation.
// Used during force-move to clear stale branch associations.
func (q *Queries) DeleteBranchesForRepo(ctx context.Context, arg DeleteBranchesForRepoParams) error {
	_, err := q.exec(ctx, q.deleteBranchesForRepoStmt, deleteBranchesForRepo, arg.ImplementationID, arg.CanonicalPath)
	return err
}

const deleteOrphanedBranches = `-- name: DeleteOrphanedBranches :exec
delete from implementation_branches
where implementation_branches.implementation_id = ?1
  and implementation_branches.canonical_path not in (
    select distinct rs.canonical_path
    from implementation_repo_sessions rs
    where rs.implementation_id = ?1
  )
`

// Remove branches whose repo no longer has any sessions in this implementation.
func (q *Queries) DeleteOrphanedBranches(ctx context.Context, implID string) error {
	_, err := q.exec(ctx, q.deleteOrphanedBranchesStmt, deleteOrphanedBranches, implID)
	return err
}

const findActiveImplementationByBranch = `-- name: FindActiveImplementationByBranch :one
select i.implementation_id, i.title, i.state, i.created_at, i.last_activity_at, i.closed_at, i.metadata_json from implementations i
join implementation_branches b on i.implementation_id = b.implementation_id
where b.canonical_path = ?
  and b.branch = ?
  and i.state = 'active'
order by i.last_activity_at desc
limit 1
`

type FindActiveImplementationByBranchParams struct {
	CanonicalPath string `json:"canonical_path"`
	Branch        string `json:"branch"`
}

func (q *Queries) FindActiveImplementationByBranch(ctx context.Context, arg FindActiveImplementationByBranchParams) (Implementation, error) {
	row := q.queryRow(ctx, q.findActiveImplementationByBranchStmt, findActiveImplementationByBranch, arg.CanonicalPath, arg.Branch)
	var i Implementation
	err := row.Scan(
		&i.ImplementationID,
		&i.Title,
		&i.State,
		&i.CreatedAt,
		&i.LastActivityAt,
		&i.ClosedAt,
		&i.MetadataJson,
	)
	return i, err
}

const listBranchesForImplementation = `-- name: ListBranchesForImplementation :many
select implementation_id, canonical_path, branch, first_seen_at, last_seen_at from implementation_branches
where implementation_id = ?
order by first_seen_at asc
`

func (q *Queries) ListBranchesForImplementation(ctx context.Context, implementationID string) ([]ImplementationBranch, error) {
	rows, err := q.query(ctx, q.listBranchesForImplementationStmt, listBranchesForImplementation, implementationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ImplementationBranch{}
	for rows.Next() {
		var i ImplementationBranch
		if err := rows.Scan(
			&i.ImplementationID,
			&i.CanonicalPath,
			&i.Branch,
			&i.FirstSeenAt,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertImplementationBranch = `-- name: UpsertImplementationBranch :exec
insert into implementation_branches (
    implementation_id, canonical_path, branch, first_seen_at, last_seen_at
) values (?, ?, ?, ?, ?)
on conflict (implementation_id, canonical_path, branch) do update
set last_seen_at = excluded.last_seen_at
`

type UpsertImplementationBranchParams struct {
	ImplementationID string `json:"implementation_id"`
	CanonicalPath    string `json:"canonical_path"`
	Branch           string `json:"branch"`
	FirstSeenAt      int64  `json:"first_seen_at"`
	LastSeenAt       int64  `json:"last_seen_at"`
}

func (q *Queries) UpsertImplementationBranch(ctx context.Context, arg UpsertImplementationBranchParams) error {
	_, err := q.exec(ctx, q.upsertImplementationBranchStmt, upsertImplementationBranch,
		arg.ImplementationID,
		arg.CanonicalPath,
		arg.Branch,
		arg.FirstSeenAt,
		arg.LastSeenAt,
	)
	return err
}
