// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: commits.sql

package db

import (
	"context"
)

const countCommitsForImplementation = `-- name: CountCommitsForImplementation :one
select count(*) from implementation_commits
where implementation_id = ?
`

func (q *Queries) CountCommitsForImplementation(ctx context.Context, implementationID string) (int64, error) {
	row := q.queryRow(ctx, q.countCommitsForImplementationStmt, countCommitsForImplementation, implementationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const findImplementationByCommit = `-- name: FindImplementationByCommit :one
select implementation_id from implementation_commits
where canonical_path = ? and commit_hash = ?
limit 1
`

type FindImplementationByCommitParams struct {
	CanonicalPath string `json:"canonical_path"`
	CommitHash    string `json:"commit_hash"`
}

func (q *Queries) FindImplementationByCommit(ctx context.Context, arg FindImplementationByCommitParams) (string, error) {
	row := q.queryRow(ctx, q.findImplementationByCommitStmt, findImplementationByCommit, arg.CanonicalPath, arg.CommitHash)
	var implementation_id string
	err := row.Scan(&implementation_id)
	return implementation_id, err
}

const insertImplementationCommit = `-- name: InsertImplementationCommit :exec
insert or ignore into implementation_commits (
    implementation_id, canonical_path, commit_hash,
    attached_at, attach_rule
) values (?, ?, ?, ?, ?)
`

type InsertImplementationCommitParams struct {
	ImplementationID string `json:"implementation_id"`
	CanonicalPath    string `json:"canonical_path"`
	CommitHash       string `json:"commit_hash"`
	AttachedAt       int64  `json:"attached_at"`
	AttachRule       string `json:"attach_rule"`
}

func (q *Queries) InsertImplementationCommit(ctx context.Context, arg InsertImplementationCommitParams) error {
	_, err := q.exec(ctx, q.insertImplementationCommitStmt, insertImplementationCommit,
		arg.ImplementationID,
		arg.CanonicalPath,
		arg.CommitHash,
		arg.AttachedAt,
		arg.AttachRule,
	)
	return err
}

const listImplementationCommits = `-- name: ListImplementationCommits :many
select implementation_id, canonical_path, commit_hash, attached_at, attach_rule from implementation_commits
where implementation_id = ?
order by attached_at asc
`

func (q *Queries) ListImplementationCommits(ctx context.Context, implementationID string) ([]ImplementationCommit, error) {
	rows, err := q.query(ctx, q.listImplementationCommitsStmt, listImplementationCommits, implementationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ImplementationCommit{}
	for rows.Next() {
		var i ImplementationCommit
		if err := rows.Scan(
			&i.ImplementationID,
			&i.CanonicalPath,
			&i.CommitHash,
			&i.AttachedAt,
			&i.AttachRule,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moveCommits = `-- name: MoveCommits :exec
update implementation_commits
set implementation_id = ?1
where implementation_id = ?2
`

type MoveCommitsParams struct {
	TargetID string `json:"target_id"`
	SourceID string `json:"source_id"`
}

func (q *Queries) MoveCommits(ctx context.Context, arg MoveCommitsParams) error {
	_, err := q.exec(ctx, q.moveCommitsStmt, moveCommits, arg.TargetID, arg.SourceID)
	return err
}
