// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: conflicts.sql

package db

import (
	"context"
	"database/sql"
)

const countUnresolvedConflicts = `-- name: CountUnresolvedConflicts :one
select count(*) from observation_conflicts
where resolved = 0
`

func (q *Queries) CountUnresolvedConflicts(ctx context.Context) (int64, error) {
	row := q.queryRow(ctx, q.countUnresolvedConflictsStmt, countUnresolvedConflicts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertConflict = `-- name: InsertConflict :exec
insert into observation_conflicts (
    conflict_id, observation_id, candidate_a, candidate_b,
    rule_name, resolved, created_at
) values (?, ?, ?, ?, ?, 0, ?)
`

type InsertConflictParams struct {
	ConflictID    string `json:"conflict_id"`
	ObservationID string `json:"observation_id"`
	CandidateA    string `json:"candidate_a"`
	CandidateB    string `json:"candidate_b"`
	RuleName      string `json:"rule_name"`
	CreatedAt     int64  `json:"created_at"`
}

func (q *Queries) InsertConflict(ctx context.Context, arg InsertConflictParams) error {
	_, err := q.exec(ctx, q.insertConflictStmt, insertConflict,
		arg.ConflictID,
		arg.ObservationID,
		arg.CandidateA,
		arg.CandidateB,
		arg.RuleName,
		arg.CreatedAt,
	)
	return err
}

const resolveConflict = `-- name: ResolveConflict :exec
update observation_conflicts
set resolved = 1, resolution = ?
where conflict_id = ?
`

type ResolveConflictParams struct {
	Resolution sql.NullString `json:"resolution"`
	ConflictID string         `json:"conflict_id"`
}

func (q *Queries) ResolveConflict(ctx context.Context, arg ResolveConflictParams) error {
	_, err := q.exec(ctx, q.resolveConflictStmt, resolveConflict, arg.Resolution, arg.ConflictID)
	return err
}
