// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.countCommitsForImplementationStmt, err = db.PrepareContext(ctx, countCommitsForImplementation); err != nil {
		return nil, fmt.Errorf("error preparing query CountCommitsForImplementation: %w", err)
	}
	if q.countFailedObservationsStmt, err = db.PrepareContext(ctx, countFailedObservations); err != nil {
		return nil, fmt.Errorf("error preparing query CountFailedObservations: %w", err)
	}
	if q.countReposForImplementationStmt, err = db.PrepareContext(ctx, countReposForImplementation); err != nil {
		return nil, fmt.Errorf("error preparing query CountReposForImplementation: %w", err)
	}
	if q.findActiveImplementationByBranchStmt, err = db.PrepareContext(ctx, findActiveImplementationByBranch); err != nil {
		return nil, fmt.Errorf("error preparing query FindActiveImplementationByBranch: %w", err)
	}
	if q.findImplementationByCommitStmt, err = db.PrepareContext(ctx, findImplementationByCommit); err != nil {
		return nil, fmt.Errorf("error preparing query FindImplementationByCommit: %w", err)
	}
	if q.findImplementationByProviderSessionStmt, err = db.PrepareContext(ctx, findImplementationByProviderSession); err != nil {
		return nil, fmt.Errorf("error preparing query FindImplementationByProviderSession: %w", err)
	}
	if q.findImplementationsByLocalSessionStmt, err = db.PrepareContext(ctx, findImplementationsByLocalSession); err != nil {
		return nil, fmt.Errorf("error preparing query FindImplementationsByLocalSession: %w", err)
	}
	if q.getImplementationStmt, err = db.PrepareContext(ctx, getImplementation); err != nil {
		return nil, fmt.Errorf("error preparing query GetImplementation: %w", err)
	}
	if q.getProviderSessionOwnerStmt, err = db.PrepareContext(ctx, getProviderSessionOwner); err != nil {
		return nil, fmt.Errorf("error preparing query GetProviderSessionOwner: %w", err)
	}
	if q.insertConflictStmt, err = db.PrepareContext(ctx, insertConflict); err != nil {
		return nil, fmt.Errorf("error preparing query InsertConflict: %w", err)
	}
	if q.insertImplementationStmt, err = db.PrepareContext(ctx, insertImplementation); err != nil {
		return nil, fmt.Errorf("error preparing query InsertImplementation: %w", err)
	}
	if q.insertImplementationCommitStmt, err = db.PrepareContext(ctx, insertImplementationCommit); err != nil {
		return nil, fmt.Errorf("error preparing query InsertImplementationCommit: %w", err)
	}
	if q.insertObservationStmt, err = db.PrepareContext(ctx, insertObservation); err != nil {
		return nil, fmt.Errorf("error preparing query InsertObservation: %w", err)
	}
	if q.insertProviderSessionStmt, err = db.PrepareContext(ctx, insertProviderSession); err != nil {
		return nil, fmt.Errorf("error preparing query InsertProviderSession: %w", err)
	}
	if q.listActiveOrMultiRepoStmt, err = db.PrepareContext(ctx, listActiveOrMultiRepo); err != nil {
		return nil, fmt.Errorf("error preparing query ListActiveOrMultiRepo: %w", err)
	}
	if q.listAllImplementationsStmt, err = db.PrepareContext(ctx, listAllImplementations); err != nil {
		return nil, fmt.Errorf("error preparing query ListAllImplementations: %w", err)
	}
	if q.listBranchesForImplementationStmt, err = db.PrepareContext(ctx, listBranchesForImplementation); err != nil {
		return nil, fmt.Errorf("error preparing query ListBranchesForImplementation: %w", err)
	}
	if q.listDeferredObservationsStmt, err = db.PrepareContext(ctx, listDeferredObservations); err != nil {
		return nil, fmt.Errorf("error preparing query ListDeferredObservations: %w", err)
	}
	if q.listImplementationCommitsStmt, err = db.PrepareContext(ctx, listImplementationCommits); err != nil {
		return nil, fmt.Errorf("error preparing query ListImplementationCommits: %w", err)
	}
	if q.listImplementationReposStmt, err = db.PrepareContext(ctx, listImplementationRepos); err != nil {
		return nil, fmt.Errorf("error preparing query ListImplementationRepos: %w", err)
	}
	if q.listImplementationsByStateStmt, err = db.PrepareContext(ctx, listImplementationsByState); err != nil {
		return nil, fmt.Errorf("error preparing query ListImplementationsByState: %w", err)
	}
	if q.listMultiRepoImplementationsStmt, err = db.PrepareContext(ctx, listMultiRepoImplementations); err != nil {
		return nil, fmt.Errorf("error preparing query ListMultiRepoImplementations: %w", err)
	}
	if q.listPendingObservationsStmt, err = db.PrepareContext(ctx, listPendingObservations); err != nil {
		return nil, fmt.Errorf("error preparing query ListPendingObservations: %w", err)
	}
	if q.listProviderSessionsForImplementationStmt, err = db.PrepareContext(ctx, listProviderSessionsForImplementation); err != nil {
		return nil, fmt.Errorf("error preparing query ListProviderSessionsForImplementation: %w", err)
	}
	if q.listRepoSessionsForImplementationStmt, err = db.PrepareContext(ctx, listRepoSessionsForImplementation); err != nil {
		return nil, fmt.Errorf("error preparing query ListRepoSessionsForImplementation: %w", err)
	}
	if q.listRetryableObservationsStmt, err = db.PrepareContext(ctx, listRetryableObservations); err != nil {
		return nil, fmt.Errorf("error preparing query ListRetryableObservations: %w", err)
	}
	if q.listStaleImplementationsStmt, err = db.PrepareContext(ctx, listStaleImplementations); err != nil {
		return nil, fmt.Errorf("error preparing query ListStaleImplementations: %w", err)
	}
	if q.listUnresolvedConflictsStmt, err = db.PrepareContext(ctx, listUnresolvedConflicts); err != nil {
		return nil, fmt.Errorf("error preparing query ListUnresolvedConflicts: %w", err)
	}
	if q.markDormantStmt, err = db.PrepareContext(ctx, markDormant); err != nil {
		return nil, fmt.Errorf("error preparing query MarkDormant: %w", err)
	}
	if q.markObservationConflictStmt, err = db.PrepareContext(ctx, markObservationConflict); err != nil {
		return nil, fmt.Errorf("error preparing query MarkObservationConflict: %w", err)
	}
	if q.markObservationDeferredStmt, err = db.PrepareContext(ctx, markObservationDeferred); err != nil {
		return nil, fmt.Errorf("error preparing query MarkObservationDeferred: %w", err)
	}
	if q.markObservationFailedStmt, err = db.PrepareContext(ctx, markObservationFailed); err != nil {
		return nil, fmt.Errorf("error preparing query MarkObservationFailed: %w", err)
	}
	if q.markObservationReconciledStmt, err = db.PrepareContext(ctx, markObservationReconciled); err != nil {
		return nil, fmt.Errorf("error preparing query MarkObservationReconciled: %w", err)
	}
	if q.pruneReconciledObservationsStmt, err = db.PrepareContext(ctx, pruneReconciledObservations); err != nil {
		return nil, fmt.Errorf("error preparing query PruneReconciledObservations: %w", err)
	}
	if q.resolveConflictStmt, err = db.PrepareContext(ctx, resolveConflict); err != nil {
		return nil, fmt.Errorf("error preparing query ResolveConflict: %w", err)
	}
	if q.updateImplementationActivityStmt, err = db.PrepareContext(ctx, updateImplementationActivity); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateImplementationActivity: %w", err)
	}
	if q.updateImplementationStateStmt, err = db.PrepareContext(ctx, updateImplementationState); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateImplementationState: %w", err)
	}
	if q.updateImplementationTitleStmt, err = db.PrepareContext(ctx, updateImplementationTitle); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateImplementationTitle: %w", err)
	}
	if q.upsertImplementationBranchStmt, err = db.PrepareContext(ctx, upsertImplementationBranch); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertImplementationBranch: %w", err)
	}
	if q.upsertImplementationRepoStmt, err = db.PrepareContext(ctx, upsertImplementationRepo); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertImplementationRepo: %w", err)
	}
	if q.upsertRepoSessionStmt, err = db.PrepareContext(ctx, upsertRepoSession); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertRepoSession: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.countCommitsForImplementationStmt != nil {
		if cerr := q.countCommitsForImplementationStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countCommitsForImplementationStmt: %w", cerr)
		}
	}
	if q.countFailedObservationsStmt != nil {
		if cerr := q.countFailedObservationsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countFailedObservationsStmt: %w", cerr)
		}
	}
	if q.countReposForImplementationStmt != nil {
		if cerr := q.countReposForImplementationStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countReposForImplementationStmt: %w", cerr)
		}
	}
	if q.findActiveImplementationByBranchStmt != nil {
		if cerr := q.findActiveImplementationByBranchStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing findActiveImplementationByBranchStmt: %w", cerr)
		}
	}
	if q.findImplementationByCommitStmt != nil {
		if cerr := q.findImplementationByCommitStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing findImplementationByCommitStmt: %w", cerr)
		}
	}
	if q.findImplementationByProviderSessionStmt != nil {
		if cerr := q.findImplementationByProviderSessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing findImplementationByProviderSessionStmt: %w", cerr)
		}
	}
	if q.findImplementationsByLocalSessionStmt != nil {
		if cerr := q.findImplementationsByLocalSessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing findImplementationsByLocalSessionStmt: %w", cerr)
		}
	}
	if q.getImplementationStmt != nil {
		if cerr := q.getImplementationStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getImplementationStmt: %w", cerr)
		}
	}
	if q.getProviderSessionOwnerStmt != nil {
		if cerr := q.getProviderSessionOwnerStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getProviderSessionOwnerStmt: %w", cerr)
		}
	}
	if q.insertConflictStmt != nil {
		if cerr := q.insertConflictStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertConflictStmt: %w", cerr)
		}
	}
	if q.insertImplementationStmt != nil {
		if cerr := q.insertImplementationStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertImplementationStmt: %w", cerr)
		}
	}
	if q.insertImplementationCommitStmt != nil {
		if cerr := q.insertImplementationCommitStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertImplementationCommitStmt: %w", cerr)
		}
	}
	if q.insertObservationStmt != nil {
		if cerr := q.insertObservationStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertObservationStmt: %w", cerr)
		}
	}
	if q.insertProviderSessionStmt != nil {
		if cerr := q.insertProviderSessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertProviderSessionStmt: %w", cerr)
		}
	}
	if q.listActiveOrMultiRepoStmt != nil {
		if cerr := q.listActiveOrMultiRepoStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listActiveOrMultiRepoStmt: %w", cerr)
		}
	}
	if q.listAllImplementationsStmt != nil {
		if cerr := q.listAllImplementationsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listAllImplementationsStmt: %w", cerr)
		}
	}
	if q.listBranchesForImplementationStmt != nil {
		if cerr := q.listBranchesForImplementationStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listBranchesForImplementationStmt: %w", cerr)
		}
	}
	if q.listDeferredObservationsStmt != nil {
		if cerr := q.listDeferredObservationsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listDeferredObservationsStmt: %w", cerr)
		}
	}
	if q.listImplementationCommitsStmt != nil {
		if cerr := q.listImplementationCommitsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listImplementationCommitsStmt: %w", cerr)
		}
	}
	if q.listImplementationReposStmt != nil {
		if cerr := q.listImplementationReposStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listImplementationReposStmt: %w", cerr)
		}
	}
	if q.listImplementationsByStateStmt != nil {
		if cerr := q.listImplementationsByStateStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listImplementationsByStateStmt: %w", cerr)
		}
	}
	if q.listMultiRepoImplementationsStmt != nil {
		if cerr := q.listMultiRepoImplementationsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listMultiRepoImplementationsStmt: %w", cerr)
		}
	}
	if q.listPendingObservationsStmt != nil {
		if cerr := q.listPendingObservationsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listPendingObservationsStmt: %w", cerr)
		}
	}
	if q.listProviderSessionsForImplementationStmt != nil {
		if cerr := q.listProviderSessionsForImplementationStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listProviderSessionsForImplementationStmt: %w", cerr)
		}
	}
	if q.listRepoSessionsForImplementationStmt != nil {
		if cerr := q.listRepoSessionsForImplementationStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listRepoSessionsForImplementationStmt: %w", cerr)
		}
	}
	if q.listRetryableObservationsStmt != nil {
		if cerr := q.listRetryableObservationsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listRetryableObservationsStmt: %w", cerr)
		}
	}
	if q.listStaleImplementationsStmt != nil {
		if cerr := q.listStaleImplementationsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listStaleImplementationsStmt: %w", cerr)
		}
	}
	if q.listUnresolvedConflictsStmt != nil {
		if cerr := q.listUnresolvedConflictsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listUnresolvedConflictsStmt: %w", cerr)
		}
	}
	if q.markDormantStmt != nil {
		if cerr := q.markDormantStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing markDormantStmt: %w", cerr)
		}
	}
	if q.markObservationConflictStmt != nil {
		if cerr := q.markObservationConflictStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing markObservationConflictStmt: %w", cerr)
		}
	}
	if q.markObservationDeferredStmt != nil {
		if cerr := q.markObservationDeferredStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing markObservationDeferredStmt: %w", cerr)
		}
	}
	if q.markObservationFailedStmt != nil {
		if cerr := q.markObservationFailedStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing markObservationFailedStmt: %w", cerr)
		}
	}
	if q.markObservationReconciledStmt != nil {
		if cerr := q.markObservationReconciledStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing markObservationReconciledStmt: %w", cerr)
		}
	}
	if q.pruneReconciledObservationsStmt != nil {
		if cerr := q.pruneReconciledObservationsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing pruneReconciledObservationsStmt: %w", cerr)
		}
	}
	if q.resolveConflictStmt != nil {
		if cerr := q.resolveConflictStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing resolveConflictStmt: %w", cerr)
		}
	}
	if q.updateImplementationActivityStmt != nil {
		if cerr := q.updateImplementationActivityStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateImplementationActivityStmt: %w", cerr)
		}
	}
	if q.updateImplementationStateStmt != nil {
		if cerr := q.updateImplementationStateStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateImplementationStateStmt: %w", cerr)
		}
	}
	if q.updateImplementationTitleStmt != nil {
		if cerr := q.updateImplementationTitleStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateImplementationTitleStmt: %w", cerr)
		}
	}
	if q.upsertImplementationBranchStmt != nil {
		if cerr := q.upsertImplementationBranchStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertImplementationBranchStmt: %w", cerr)
		}
	}
	if q.upsertImplementationRepoStmt != nil {
		if cerr := q.upsertImplementationRepoStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertImplementationRepoStmt: %w", cerr)
		}
	}
	if q.upsertRepoSessionStmt != nil {
		if cerr := q.upsertRepoSessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertRepoSessionStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                                        DBTX
	tx                                        *sql.Tx
	countCommitsForImplementationStmt         *sql.Stmt
	countFailedObservationsStmt               *sql.Stmt
	countReposForImplementationStmt           *sql.Stmt
	findActiveImplementationByBranchStmt      *sql.Stmt
	findImplementationByCommitStmt            *sql.Stmt
	findImplementationByProviderSessionStmt   *sql.Stmt
	findImplementationsByLocalSessionStmt     *sql.Stmt
	getImplementationStmt                     *sql.Stmt
	getProviderSessionOwnerStmt               *sql.Stmt
	insertConflictStmt                        *sql.Stmt
	insertImplementationStmt                  *sql.Stmt
	insertImplementationCommitStmt            *sql.Stmt
	insertObservationStmt                     *sql.Stmt
	insertProviderSessionStmt                 *sql.Stmt
	listActiveOrMultiRepoStmt                 *sql.Stmt
	listAllImplementationsStmt                *sql.Stmt
	listBranchesForImplementationStmt         *sql.Stmt
	listDeferredObservationsStmt              *sql.Stmt
	listImplementationCommitsStmt             *sql.Stmt
	listImplementationReposStmt               *sql.Stmt
	listImplementationsByStateStmt            *sql.Stmt
	listMultiRepoImplementationsStmt          *sql.Stmt
	listPendingObservationsStmt               *sql.Stmt
	listProviderSessionsForImplementationStmt *sql.Stmt
	listRepoSessionsForImplementationStmt     *sql.Stmt
	listRetryableObservationsStmt             *sql.Stmt
	listStaleImplementationsStmt              *sql.Stmt
	listUnresolvedConflictsStmt               *sql.Stmt
	markDormantStmt                           *sql.Stmt
	markObservationConflictStmt               *sql.Stmt
	markObservationDeferredStmt               *sql.Stmt
	markObservationFailedStmt                 *sql.Stmt
	markObservationReconciledStmt             *sql.Stmt
	pruneReconciledObservationsStmt           *sql.Stmt
	resolveConflictStmt                       *sql.Stmt
	updateImplementationActivityStmt          *sql.Stmt
	updateImplementationStateStmt             *sql.Stmt
	updateImplementationTitleStmt             *sql.Stmt
	upsertImplementationBranchStmt            *sql.Stmt
	upsertImplementationRepoStmt              *sql.Stmt
	upsertRepoSessionStmt                     *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                                        tx,
		tx:                                        tx,
		countCommitsForImplementationStmt:         q.countCommitsForImplementationStmt,
		countFailedObservationsStmt:               q.countFailedObservationsStmt,
		countReposForImplementationStmt:           q.countReposForImplementationStmt,
		findActiveImplementationByBranchStmt:      q.findActiveImplementationByBranchStmt,
		findImplementationByCommitStmt:            q.findImplementationByCommitStmt,
		findImplementationByProviderSessionStmt:   q.findImplementationByProviderSessionStmt,
		findImplementationsByLocalSessionStmt:     q.findImplementationsByLocalSessionStmt,
		getImplementationStmt:                     q.getImplementationStmt,
		getProviderSessionOwnerStmt:               q.getProviderSessionOwnerStmt,
		insertConflictStmt:                        q.insertConflictStmt,
		insertImplementationStmt:                  q.insertImplementationStmt,
		insertImplementationCommitStmt:            q.insertImplementationCommitStmt,
		insertObservationStmt:                     q.insertObservationStmt,
		insertProviderSessionStmt:                 q.insertProviderSessionStmt,
		listActiveOrMultiRepoStmt:                 q.listActiveOrMultiRepoStmt,
		listAllImplementationsStmt:                q.listAllImplementationsStmt,
		listBranchesForImplementationStmt:         q.listBranchesForImplementationStmt,
		listDeferredObservationsStmt:              q.listDeferredObservationsStmt,
		listImplementationCommitsStmt:             q.listImplementationCommitsStmt,
		listImplementationReposStmt:               q.listImplementationReposStmt,
		listImplementationsByStateStmt:            q.listImplementationsByStateStmt,
		listMultiRepoImplementationsStmt:          q.listMultiRepoImplementationsStmt,
		listPendingObservationsStmt:               q.listPendingObservationsStmt,
		listProviderSessionsForImplementationStmt: q.listProviderSessionsForImplementationStmt,
		listRepoSessionsForImplementationStmt:     q.listRepoSessionsForImplementationStmt,
		listRetryableObservationsStmt:             q.listRetryableObservationsStmt,
		listStaleImplementationsStmt:              q.listStaleImplementationsStmt,
		listUnresolvedConflictsStmt:               q.listUnresolvedConflictsStmt,
		markDormantStmt:                           q.markDormantStmt,
		markObservationConflictStmt:               q.markObservationConflictStmt,
		markObservationDeferredStmt:               q.markObservationDeferredStmt,
		markObservationFailedStmt:                 q.markObservationFailedStmt,
		markObservationReconciledStmt:             q.markObservationReconciledStmt,
		pruneReconciledObservationsStmt:           q.pruneReconciledObservationsStmt,
		resolveConflictStmt:                       q.resolveConflictStmt,
		updateImplementationActivityStmt:          q.updateImplementationActivityStmt,
		updateImplementationStateStmt:             q.updateImplementationStateStmt,
		updateImplementationTitleStmt:             q.updateImplementationTitleStmt,
		upsertImplementationBranchStmt:            q.upsertImplementationBranchStmt,
		upsertImplementationRepoStmt:              q.upsertImplementationRepoStmt,
		upsertRepoSessionStmt:                     q.upsertRepoSessionStmt,
	}
}
