// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: implementations.sql

package db

import (
	"context"
	"database/sql"
	"strings"
)

const countImplementationsByState = `-- name: CountImplementationsByState :one
select count(*) from implementations
where state in (/*SLICE:states*/?)
`

func (q *Queries) CountImplementationsByState(ctx context.Context, states []string) (int64, error) {
	query := countImplementationsByState
	var queryParams []interface{}
	if len(states) > 0 {
		for _, v := range states {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:states*/?", strings.Repeat(",?", len(states))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:states*/?", "NULL", 1)
	}
	row := q.queryRow(ctx, nil, query, queryParams...)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getImplementation = `-- name: GetImplementation :one
select implementation_id, title, state, created_at, last_activity_at, closed_at, metadata_json from implementations where implementation_id = ?
`

func (q *Queries) GetImplementation(ctx context.Context, implementationID string) (Implementation, error) {
	row := q.queryRow(ctx, q.getImplementationStmt, getImplementation, implementationID)
	var i Implementation
	err := row.Scan(
		&i.ImplementationID,
		&i.Title,
		&i.State,
		&i.CreatedAt,
		&i.LastActivityAt,
		&i.ClosedAt,
		&i.MetadataJson,
	)
	return i, err
}

const insertImplementation = `-- name: InsertImplementation :exec
insert into implementations (implementation_id, state, created_at, last_activity_at)
values (?, 'active', ?, ?)
`

type InsertImplementationParams struct {
	ImplementationID string `json:"implementation_id"`
	CreatedAt        int64  `json:"created_at"`
	LastActivityAt   int64  `json:"last_activity_at"`
}

func (q *Queries) InsertImplementation(ctx context.Context, arg InsertImplementationParams) error {
	_, err := q.exec(ctx, q.insertImplementationStmt, insertImplementation, arg.ImplementationID, arg.CreatedAt, arg.LastActivityAt)
	return err
}

const listActiveOrMultiRepo = `-- name: ListActiveOrMultiRepo :many
select i.implementation_id, i.title, i.state, i.created_at, i.last_activity_at, i.closed_at, i.metadata_json,
    (select count(distinct canonical_path) from implementation_repos where implementation_id = i.implementation_id) as repo_count,
    (select count(*) from implementation_commits where implementation_id = i.implementation_id) as commit_count
from implementations i
where i.state = 'active'
   or (select count(distinct canonical_path) from implementation_repos
       where implementation_id = i.implementation_id) > 1
order by i.last_activity_at desc
limit ?
`

type ListActiveOrMultiRepoRow struct {
	ImplementationID string         `json:"implementation_id"`
	Title            sql.NullString `json:"title"`
	State            string         `json:"state"`
	CreatedAt        int64          `json:"created_at"`
	LastActivityAt   int64          `json:"last_activity_at"`
	ClosedAt         sql.NullInt64  `json:"closed_at"`
	MetadataJson     sql.NullString `json:"metadata_json"`
	RepoCount        int64          `json:"repo_count"`
	CommitCount      int64          `json:"commit_count"`
}

func (q *Queries) ListActiveOrMultiRepo(ctx context.Context, limit int64) ([]ListActiveOrMultiRepoRow, error) {
	rows, err := q.query(ctx, q.listActiveOrMultiRepoStmt, listActiveOrMultiRepo, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveOrMultiRepoRow{}
	for rows.Next() {
		var i ListActiveOrMultiRepoRow
		if err := rows.Scan(
			&i.ImplementationID,
			&i.Title,
			&i.State,
			&i.CreatedAt,
			&i.LastActivityAt,
			&i.ClosedAt,
			&i.MetadataJson,
			&i.RepoCount,
			&i.CommitCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllImplementations = `-- name: ListAllImplementations :many
select i.implementation_id, i.title, i.state, i.created_at, i.last_activity_at, i.closed_at, i.metadata_json,
    (select count(distinct canonical_path) from implementation_repos where implementation_id = i.implementation_id) as repo_count,
    (select count(*) from implementation_commits where implementation_id = i.implementation_id) as commit_count
from implementations i
order by i.last_activity_at desc
limit ?
`

type ListAllImplementationsRow struct {
	ImplementationID string         `json:"implementation_id"`
	Title            sql.NullString `json:"title"`
	State            string         `json:"state"`
	CreatedAt        int64          `json:"created_at"`
	LastActivityAt   int64          `json:"last_activity_at"`
	ClosedAt         sql.NullInt64  `json:"closed_at"`
	MetadataJson     sql.NullString `json:"metadata_json"`
	RepoCount        int64          `json:"repo_count"`
	CommitCount      int64          `json:"commit_count"`
}

func (q *Queries) ListAllImplementations(ctx context.Context, limit int64) ([]ListAllImplementationsRow, error) {
	rows, err := q.query(ctx, q.listAllImplementationsStmt, listAllImplementations, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllImplementationsRow{}
	for rows.Next() {
		var i ListAllImplementationsRow
		if err := rows.Scan(
			&i.ImplementationID,
			&i.Title,
			&i.State,
			&i.CreatedAt,
			&i.LastActivityAt,
			&i.ClosedAt,
			&i.MetadataJson,
			&i.RepoCount,
			&i.CommitCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listImplementationsByState = `-- name: ListImplementationsByState :many
select i.implementation_id, i.title, i.state, i.created_at, i.last_activity_at, i.closed_at, i.metadata_json,
    (select count(distinct canonical_path) from implementation_repos where implementation_id = i.implementation_id) as repo_count,
    (select count(*) from implementation_commits where implementation_id = i.implementation_id) as commit_count
from implementations i
where i.state in (/*SLICE:states*/?)
order by i.last_activity_at desc
limit ?
`

type ListImplementationsByStateParams struct {
	States []string `json:"states"`
	Limit  int64    `json:"limit"`
}

type ListImplementationsByStateRow struct {
	ImplementationID string         `json:"implementation_id"`
	Title            sql.NullString `json:"title"`
	State            string         `json:"state"`
	CreatedAt        int64          `json:"created_at"`
	LastActivityAt   int64          `json:"last_activity_at"`
	ClosedAt         sql.NullInt64  `json:"closed_at"`
	MetadataJson     sql.NullString `json:"metadata_json"`
	RepoCount        int64          `json:"repo_count"`
	CommitCount      int64          `json:"commit_count"`
}

func (q *Queries) ListImplementationsByState(ctx context.Context, arg ListImplementationsByStateParams) ([]ListImplementationsByStateRow, error) {
	query := listImplementationsByState
	var queryParams []interface{}
	if len(arg.States) > 0 {
		for _, v := range arg.States {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:states*/?", strings.Repeat(",?", len(arg.States))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:states*/?", "NULL", 1)
	}
	queryParams = append(queryParams, arg.Limit)
	rows, err := q.query(ctx, nil, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListImplementationsByStateRow{}
	for rows.Next() {
		var i ListImplementationsByStateRow
		if err := rows.Scan(
			&i.ImplementationID,
			&i.Title,
			&i.State,
			&i.CreatedAt,
			&i.LastActivityAt,
			&i.ClosedAt,
			&i.MetadataJson,
			&i.RepoCount,
			&i.CommitCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaleImplementations = `-- name: ListStaleImplementations :many
select implementation_id, title, state, created_at, last_activity_at, closed_at, metadata_json from implementations
where state = 'dormant'
  and last_activity_at < ?
order by last_activity_at asc
`

func (q *Queries) ListStaleImplementations(ctx context.Context, lastActivityAt int64) ([]Implementation, error) {
	rows, err := q.query(ctx, q.listStaleImplementationsStmt, listStaleImplementations, lastActivityAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Implementation{}
	for rows.Next() {
		var i Implementation
		if err := rows.Scan(
			&i.ImplementationID,
			&i.Title,
			&i.State,
			&i.CreatedAt,
			&i.LastActivityAt,
			&i.ClosedAt,
			&i.MetadataJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDormant = `-- name: MarkDormant :execresult
update implementations
set state = 'dormant'
where state = 'active'
  and last_activity_at < ?
`

func (q *Queries) MarkDormant(ctx context.Context, lastActivityAt int64) (sql.Result, error) {
	return q.exec(ctx, q.markDormantStmt, markDormant, lastActivityAt)
}

const resolveImplementationByPrefix = `-- name: ResolveImplementationByPrefix :many
select implementation_id from implementations
where implementation_id like ?1 || '%'
limit 10
`

func (q *Queries) ResolveImplementationByPrefix(ctx context.Context, prefix sql.NullString) ([]string, error) {
	rows, err := q.query(ctx, q.resolveImplementationByPrefixStmt, resolveImplementationByPrefix, prefix)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var implementation_id string
		if err := rows.Scan(&implementation_id); err != nil {
			return nil, err
		}
		items = append(items, implementation_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateImplementationActivity = `-- name: UpdateImplementationActivity :exec
update implementations set last_activity_at = ? where implementation_id = ?
`

type UpdateImplementationActivityParams struct {
	LastActivityAt   int64  `json:"last_activity_at"`
	ImplementationID string `json:"implementation_id"`
}

func (q *Queries) UpdateImplementationActivity(ctx context.Context, arg UpdateImplementationActivityParams) error {
	_, err := q.exec(ctx, q.updateImplementationActivityStmt, updateImplementationActivity, arg.LastActivityAt, arg.ImplementationID)
	return err
}

const updateImplementationMetadata = `-- name: UpdateImplementationMetadata :exec
update implementations set metadata_json = ? where implementation_id = ?
`

type UpdateImplementationMetadataParams struct {
	MetadataJson     sql.NullString `json:"metadata_json"`
	ImplementationID string         `json:"implementation_id"`
}

func (q *Queries) UpdateImplementationMetadata(ctx context.Context, arg UpdateImplementationMetadataParams) error {
	_, err := q.exec(ctx, q.updateImplementationMetadataStmt, updateImplementationMetadata, arg.MetadataJson, arg.ImplementationID)
	return err
}

const updateImplementationState = `-- name: UpdateImplementationState :exec
update implementations set state = ?, closed_at = ? where implementation_id = ?
`

type UpdateImplementationStateParams struct {
	State            string        `json:"state"`
	ClosedAt         sql.NullInt64 `json:"closed_at"`
	ImplementationID string        `json:"implementation_id"`
}

func (q *Queries) UpdateImplementationState(ctx context.Context, arg UpdateImplementationStateParams) error {
	_, err := q.exec(ctx, q.updateImplementationStateStmt, updateImplementationState, arg.State, arg.ClosedAt, arg.ImplementationID)
	return err
}

const updateImplementationTitle = `-- name: UpdateImplementationTitle :exec
update implementations set title = ? where implementation_id = ?
`

type UpdateImplementationTitleParams struct {
	Title            sql.NullString `json:"title"`
	ImplementationID string         `json:"implementation_id"`
}

func (q *Queries) UpdateImplementationTitle(ctx context.Context, arg UpdateImplementationTitleParams) error {
	_, err := q.exec(ctx, q.updateImplementationTitleStmt, updateImplementationTitle, arg.Title, arg.ImplementationID)
	return err
}
