// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type Implementation struct {
	ImplementationID string         `json:"implementation_id"`
	Title            sql.NullString `json:"title"`
	State            string         `json:"state"`
	CreatedAt        int64          `json:"created_at"`
	LastActivityAt   int64          `json:"last_activity_at"`
	ClosedAt         sql.NullInt64  `json:"closed_at"`
	MetadataJson     sql.NullString `json:"metadata_json"`
}

type ImplementationBranch struct {
	ImplementationID string `json:"implementation_id"`
	CanonicalPath    string `json:"canonical_path"`
	Branch           string `json:"branch"`
	FirstSeenAt      int64  `json:"first_seen_at"`
	LastSeenAt       int64  `json:"last_seen_at"`
}

type ImplementationCommit struct {
	ImplementationID string `json:"implementation_id"`
	CanonicalPath    string `json:"canonical_path"`
	CommitHash       string `json:"commit_hash"`
	AttachedAt       int64  `json:"attached_at"`
	AttachRule       string `json:"attach_rule"`
}

type ImplementationProviderSession struct {
	ImplementationID  string         `json:"implementation_id"`
	Provider          string         `json:"provider"`
	ProviderSessionID string         `json:"provider_session_id"`
	SourceProjectPath sql.NullString `json:"source_project_path"`
	AttachRule        string         `json:"attach_rule"`
	AttachedAt        int64          `json:"attached_at"`
}

type ImplementationRepo struct {
	ImplementationID string `json:"implementation_id"`
	CanonicalPath    string `json:"canonical_path"`
	DisplayName      string `json:"display_name"`
	RepoRole         string `json:"repo_role"`
	FirstSeenAt      int64  `json:"first_seen_at"`
	LastSeenAt       int64  `json:"last_seen_at"`
}

type ImplementationRepoSession struct {
	ImplementationID  string `json:"implementation_id"`
	Provider          string `json:"provider"`
	ProviderSessionID string `json:"provider_session_id"`
	CanonicalPath     string `json:"canonical_path"`
	SessionID         string `json:"session_id"`
	FirstSeenAt       int64  `json:"first_seen_at"`
	LastSeenAt        int64  `json:"last_seen_at"`
}

type Observation struct {
	ObservationID     string         `json:"observation_id"`
	Provider          string         `json:"provider"`
	ProviderSessionID string         `json:"provider_session_id"`
	ParentSessionID   sql.NullString `json:"parent_session_id"`
	SourceProjectPath sql.NullString `json:"source_project_path"`
	TargetRepoPath    string         `json:"target_repo_path"`
	EventTs           int64          `json:"event_ts"`
	CreatedAt         int64          `json:"created_at"`
	Reconciled        int64          `json:"reconciled"`
	ReconcileAttempts int64          `json:"reconcile_attempts"`
	LastError         sql.NullString `json:"last_error"`
}

type ObservationConflict struct {
	ConflictID    string         `json:"conflict_id"`
	ObservationID string         `json:"observation_id"`
	CandidateA    string         `json:"candidate_a"`
	CandidateB    string         `json:"candidate_b"`
	RuleName      string         `json:"rule_name"`
	Resolved      int64          `json:"resolved"`
	Resolution    sql.NullString `json:"resolution"`
	CreatedAt     int64          `json:"created_at"`
}
