// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: observations.sql

package db

import (
	"context"
	"database/sql"
)

const countFailedObservations = `-- name: CountFailedObservations :one
select count(*) from observations
where reconciled = 3
  and reconcile_attempts >= ?
`

func (q *Queries) CountFailedObservations(ctx context.Context, reconcileAttempts int64) (int64, error) {
	row := q.queryRow(ctx, q.countFailedObservationsStmt, countFailedObservations, reconcileAttempts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertObservation = `-- name: InsertObservation :exec
insert into observations (
    observation_id, provider, provider_session_id, parent_session_id,
    source_project_path, target_repo_path,
    event_ts, created_at, reconciled
) values (?, ?, ?, ?, ?, ?, ?, ?, 0)
`

type InsertObservationParams struct {
	ObservationID     string         `json:"observation_id"`
	Provider          string         `json:"provider"`
	ProviderSessionID string         `json:"provider_session_id"`
	ParentSessionID   sql.NullString `json:"parent_session_id"`
	SourceProjectPath sql.NullString `json:"source_project_path"`
	TargetRepoPath    string         `json:"target_repo_path"`
	EventTs           int64          `json:"event_ts"`
	CreatedAt         int64          `json:"created_at"`
}

func (q *Queries) InsertObservation(ctx context.Context, arg InsertObservationParams) error {
	_, err := q.exec(ctx, q.insertObservationStmt, insertObservation,
		arg.ObservationID,
		arg.Provider,
		arg.ProviderSessionID,
		arg.ParentSessionID,
		arg.SourceProjectPath,
		arg.TargetRepoPath,
		arg.EventTs,
		arg.CreatedAt,
	)
	return err
}

const listDeferredObservations = `-- name: ListDeferredObservations :many
select observation_id, provider, provider_session_id, parent_session_id, source_project_path, target_repo_path, event_ts, created_at, reconciled, reconcile_attempts, last_error from observations
where reconciled = 4
order by created_at asc
limit ?
`

func (q *Queries) ListDeferredObservations(ctx context.Context, limit int64) ([]Observation, error) {
	rows, err := q.query(ctx, q.listDeferredObservationsStmt, listDeferredObservations, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Observation{}
	for rows.Next() {
		var i Observation
		if err := rows.Scan(
			&i.ObservationID,
			&i.Provider,
			&i.ProviderSessionID,
			&i.ParentSessionID,
			&i.SourceProjectPath,
			&i.TargetRepoPath,
			&i.EventTs,
			&i.CreatedAt,
			&i.Reconciled,
			&i.ReconcileAttempts,
			&i.LastError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingObservations = `-- name: ListPendingObservations :many
select observation_id, provider, provider_session_id, parent_session_id, source_project_path, target_repo_path, event_ts, created_at, reconciled, reconcile_attempts, last_error from observations
where reconciled = 0
order by
    case when parent_session_id is null or parent_session_id = '' then 0 else 1 end asc,
    created_at asc
limit ?
`

func (q *Queries) ListPendingObservations(ctx context.Context, limit int64) ([]Observation, error) {
	rows, err := q.query(ctx, q.listPendingObservationsStmt, listPendingObservations, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Observation{}
	for rows.Next() {
		var i Observation
		if err := rows.Scan(
			&i.ObservationID,
			&i.Provider,
			&i.ProviderSessionID,
			&i.ParentSessionID,
			&i.SourceProjectPath,
			&i.TargetRepoPath,
			&i.EventTs,
			&i.CreatedAt,
			&i.Reconciled,
			&i.ReconcileAttempts,
			&i.LastError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRetryableObservations = `-- name: ListRetryableObservations :many
select observation_id, provider, provider_session_id, parent_session_id, source_project_path, target_repo_path, event_ts, created_at, reconciled, reconcile_attempts, last_error from observations
where reconciled = 3
  and reconcile_attempts < ?
order by created_at asc
limit ?
`

type ListRetryableObservationsParams struct {
	ReconcileAttempts int64 `json:"reconcile_attempts"`
	Limit             int64 `json:"limit"`
}

func (q *Queries) ListRetryableObservations(ctx context.Context, arg ListRetryableObservationsParams) ([]Observation, error) {
	rows, err := q.query(ctx, q.listRetryableObservationsStmt, listRetryableObservations, arg.ReconcileAttempts, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Observation{}
	for rows.Next() {
		var i Observation
		if err := rows.Scan(
			&i.ObservationID,
			&i.Provider,
			&i.ProviderSessionID,
			&i.ParentSessionID,
			&i.SourceProjectPath,
			&i.TargetRepoPath,
			&i.EventTs,
			&i.CreatedAt,
			&i.Reconciled,
			&i.ReconcileAttempts,
			&i.LastError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markObservationConflict = `-- name: MarkObservationConflict :exec
update observations set reconciled = 2 where observation_id = ?
`

func (q *Queries) MarkObservationConflict(ctx context.Context, observationID string) error {
	_, err := q.exec(ctx, q.markObservationConflictStmt, markObservationConflict, observationID)
	return err
}

const markObservationDeferred = `-- name: MarkObservationDeferred :exec
update observations
set reconciled = 4,
    reconcile_attempts = reconcile_attempts + 1
where observation_id = ?
`

func (q *Queries) MarkObservationDeferred(ctx context.Context, observationID string) error {
	_, err := q.exec(ctx, q.markObservationDeferredStmt, markObservationDeferred, observationID)
	return err
}

const markObservationFailed = `-- name: MarkObservationFailed :exec
update observations
set reconciled = 3,
    reconcile_attempts = reconcile_attempts + 1,
    last_error = ?
where observation_id = ?
`

type MarkObservationFailedParams struct {
	LastError     sql.NullString `json:"last_error"`
	ObservationID string         `json:"observation_id"`
}

func (q *Queries) MarkObservationFailed(ctx context.Context, arg MarkObservationFailedParams) error {
	_, err := q.exec(ctx, q.markObservationFailedStmt, markObservationFailed, arg.LastError, arg.ObservationID)
	return err
}

const markObservationReconciled = `-- name: MarkObservationReconciled :exec
update observations set reconciled = 1 where observation_id = ?
`

func (q *Queries) MarkObservationReconciled(ctx context.Context, observationID string) error {
	_, err := q.exec(ctx, q.markObservationReconciledStmt, markObservationReconciled, observationID)
	return err
}

const pruneReconciledObservations = `-- name: PruneReconciledObservations :execresult
delete from observations
where reconciled = 1
  and created_at < ?
`

func (q *Queries) PruneReconciledObservations(ctx context.Context, createdAt int64) (sql.Result, error) {
	return q.exec(ctx, q.pruneReconciledObservationsStmt, pruneReconciledObservations, createdAt)
}
