// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: provider_sessions.sql

package db

import (
	"context"
	"database/sql"
)

const deleteProviderSession = `-- name: DeleteProviderSession :exec
delete from implementation_provider_sessions
where implementation_id = ? and provider = ? and provider_session_id = ?
`

type DeleteProviderSessionParams struct {
	ImplementationID  string `json:"implementation_id"`
	Provider          string `json:"provider"`
	ProviderSessionID string `json:"provider_session_id"`
}

func (q *Queries) DeleteProviderSession(ctx context.Context, arg DeleteProviderSessionParams) error {
	_, err := q.exec(ctx, q.deleteProviderSessionStmt, deleteProviderSession, arg.ImplementationID, arg.Provider, arg.ProviderSessionID)
	return err
}

const findImplementationByProviderSession = `-- name: FindImplementationByProviderSession :one
select i.implementation_id, i.title, i.state, i.created_at, i.last_activity_at, i.closed_at, i.metadata_json from implementations i
join implementation_provider_sessions s on i.implementation_id = s.implementation_id
where s.provider = ? and s.provider_session_id = ?
  and i.state != 'closed'
order by i.last_activity_at desc
limit 1
`

type FindImplementationByProviderSessionParams struct {
	Provider          string `json:"provider"`
	ProviderSessionID string `json:"provider_session_id"`
}

func (q *Queries) FindImplementationByProviderSession(ctx context.Context, arg FindImplementationByProviderSessionParams) (Implementation, error) {
	row := q.queryRow(ctx, q.findImplementationByProviderSessionStmt, findImplementationByProviderSession, arg.Provider, arg.ProviderSessionID)
	var i Implementation
	err := row.Scan(
		&i.ImplementationID,
		&i.Title,
		&i.State,
		&i.CreatedAt,
		&i.LastActivityAt,
		&i.ClosedAt,
		&i.MetadataJson,
	)
	return i, err
}

const getProviderSessionOwner = `-- name: GetProviderSessionOwner :one
select s.implementation_id from implementation_provider_sessions s
join implementations i on i.implementation_id = s.implementation_id
where s.provider = ? and s.provider_session_id = ?
  and i.state != 'closed'
order by i.last_activity_at desc
limit 1
`

type GetProviderSessionOwnerParams struct {
	Provider          string `json:"provider"`
	ProviderSessionID string `json:"provider_session_id"`
}

func (q *Queries) GetProviderSessionOwner(ctx context.Context, arg GetProviderSessionOwnerParams) (string, error) {
	row := q.queryRow(ctx, q.getProviderSessionOwnerStmt, getProviderSessionOwner, arg.Provider, arg.ProviderSessionID)
	var implementation_id string
	err := row.Scan(&implementation_id)
	return implementation_id, err
}

const insertProviderSession = `-- name: InsertProviderSession :exec
insert into implementation_provider_sessions (
    implementation_id, provider, provider_session_id,
    source_project_path, attach_rule, attached_at
) values (?, ?, ?, ?, ?, ?)
`

type InsertProviderSessionParams struct {
	ImplementationID  string         `json:"implementation_id"`
	Provider          string         `json:"provider"`
	ProviderSessionID string         `json:"provider_session_id"`
	SourceProjectPath sql.NullString `json:"source_project_path"`
	AttachRule        string         `json:"attach_rule"`
	AttachedAt        int64          `json:"attached_at"`
}

func (q *Queries) InsertProviderSession(ctx context.Context, arg InsertProviderSessionParams) error {
	_, err := q.exec(ctx, q.insertProviderSessionStmt, insertProviderSession,
		arg.ImplementationID,
		arg.Provider,
		arg.ProviderSessionID,
		arg.SourceProjectPath,
		arg.AttachRule,
		arg.AttachedAt,
	)
	return err
}

const listProviderSessionsForImplementation = `-- name: ListProviderSessionsForImplementation :many
select implementation_id, provider, provider_session_id, source_project_path, attach_rule, attached_at from implementation_provider_sessions
where implementation_id = ?
order by attached_at asc
`

func (q *Queries) ListProviderSessionsForImplementation(ctx context.Context, implementationID string) ([]ImplementationProviderSession, error) {
	rows, err := q.query(ctx, q.listProviderSessionsForImplementationStmt, listProviderSessionsForImplementation, implementationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ImplementationProviderSession{}
	for rows.Next() {
		var i ImplementationProviderSession
		if err := rows.Scan(
			&i.ImplementationID,
			&i.Provider,
			&i.ProviderSessionID,
			&i.SourceProjectPath,
			&i.AttachRule,
			&i.AttachedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moveProviderSessions = `-- name: MoveProviderSessions :exec
update implementation_provider_sessions
set implementation_id = ?1
where implementation_id = ?2
`

type MoveProviderSessionsParams struct {
	TargetID string `json:"target_id"`
	SourceID string `json:"source_id"`
}

func (q *Queries) MoveProviderSessions(ctx context.Context, arg MoveProviderSessionsParams) error {
	_, err := q.exec(ctx, q.moveProviderSessionsStmt, moveProviderSessions, arg.TargetID, arg.SourceID)
	return err
}
