// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: repos.sql

package db

import (
	"context"
)

const countReposForImplementation = `-- name: CountReposForImplementation :one
select count(distinct canonical_path) from implementation_repos
where implementation_id = ?
`

func (q *Queries) CountReposForImplementation(ctx context.Context, implementationID string) (int64, error) {
	row := q.queryRow(ctx, q.countReposForImplementationStmt, countReposForImplementation, implementationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listImplementationRepos = `-- name: ListImplementationRepos :many
select implementation_id, canonical_path, display_name, repo_role, first_seen_at, last_seen_at from implementation_repos
where implementation_id = ?
order by first_seen_at asc
`

func (q *Queries) ListImplementationRepos(ctx context.Context, implementationID string) ([]ImplementationRepo, error) {
	rows, err := q.query(ctx, q.listImplementationReposStmt, listImplementationRepos, implementationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ImplementationRepo{}
	for rows.Next() {
		var i ImplementationRepo
		if err := rows.Scan(
			&i.ImplementationID,
			&i.CanonicalPath,
			&i.DisplayName,
			&i.RepoRole,
			&i.FirstSeenAt,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertImplementationRepo = `-- name: UpsertImplementationRepo :exec
insert into implementation_repos (
    implementation_id, canonical_path, display_name,
    repo_role, first_seen_at, last_seen_at
) values (?, ?, ?, ?, ?, ?)
on conflict (implementation_id, canonical_path) do update
set last_seen_at = excluded.last_seen_at,
    repo_role = case
        when implementation_repos.repo_role = 'origin' then 'origin'
        when excluded.repo_role = 'origin' then 'origin'
        else excluded.repo_role
    end
`

type UpsertImplementationRepoParams struct {
	ImplementationID string `json:"implementation_id"`
	CanonicalPath    string `json:"canonical_path"`
	DisplayName      string `json:"display_name"`
	RepoRole         string `json:"repo_role"`
	FirstSeenAt      int64  `json:"first_seen_at"`
	LastSeenAt       int64  `json:"last_seen_at"`
}

func (q *Queries) UpsertImplementationRepo(ctx context.Context, arg UpsertImplementationRepoParams) error {
	_, err := q.exec(ctx, q.upsertImplementationRepoStmt, upsertImplementationRepo,
		arg.ImplementationID,
		arg.CanonicalPath,
		arg.DisplayName,
		arg.RepoRole,
		arg.FirstSeenAt,
		arg.LastSeenAt,
	)
	return err
}
