// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: repo_sessions.sql

package db

import (
	"context"
)

const deleteRepoSessionsByProviderSession = `-- name: DeleteRepoSessionsByProviderSession :exec
delete from implementation_repo_sessions
where implementation_id = ?
  and provider = ?
  and provider_session_id = ?
`

type DeleteRepoSessionsByProviderSessionParams struct {
	ImplementationID  string `json:"implementation_id"`
	Provider          string `json:"provider"`
	ProviderSessionID string `json:"provider_session_id"`
}

func (q *Queries) DeleteRepoSessionsByProviderSession(ctx context.Context, arg DeleteRepoSessionsByProviderSessionParams) error {
	_, err := q.exec(ctx, q.deleteRepoSessionsByProviderSessionStmt, deleteRepoSessionsByProviderSession, arg.ImplementationID, arg.Provider, arg.ProviderSessionID)
	return err
}

const findImplementationsByLocalSession = `-- name: FindImplementationsByLocalSession :many
select i.implementation_id, i.title, i.state, i.created_at, i.last_activity_at, i.closed_at, i.metadata_json from implementations i
join implementation_repo_sessions rs on i.implementation_id = rs.implementation_id
where rs.session_id = ?
order by
    case i.state when 'active' then 0 when 'dormant' then 1 else 2 end asc,
    i.last_activity_at desc
`

func (q *Queries) FindImplementationsByLocalSession(ctx context.Context, sessionID string) ([]Implementation, error) {
	rows, err := q.query(ctx, q.findImplementationsByLocalSessionStmt, findImplementationsByLocalSession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Implementation{}
	for rows.Next() {
		var i Implementation
		if err := rows.Scan(
			&i.ImplementationID,
			&i.Title,
			&i.State,
			&i.CreatedAt,
			&i.LastActivityAt,
			&i.ClosedAt,
			&i.MetadataJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRepoSessionsForImplementation = `-- name: ListRepoSessionsForImplementation :many
select implementation_id, provider, provider_session_id, canonical_path, session_id, first_seen_at, last_seen_at from implementation_repo_sessions
where implementation_id = ?
order by first_seen_at asc
`

func (q *Queries) ListRepoSessionsForImplementation(ctx context.Context, implementationID string) ([]ImplementationRepoSession, error) {
	rows, err := q.query(ctx, q.listRepoSessionsForImplementationStmt, listRepoSessionsForImplementation, implementationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ImplementationRepoSession{}
	for rows.Next() {
		var i ImplementationRepoSession
		if err := rows.Scan(
			&i.ImplementationID,
			&i.Provider,
			&i.ProviderSessionID,
			&i.CanonicalPath,
			&i.SessionID,
			&i.FirstSeenAt,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moveRepoSessions = `-- name: MoveRepoSessions :exec
update implementation_repo_sessions
set implementation_id = ?1
where implementation_id = ?2
`

type MoveRepoSessionsParams struct {
	TargetID string `json:"target_id"`
	SourceID string `json:"source_id"`
}

func (q *Queries) MoveRepoSessions(ctx context.Context, arg MoveRepoSessionsParams) error {
	_, err := q.exec(ctx, q.moveRepoSessionsStmt, moveRepoSessions, arg.TargetID, arg.SourceID)
	return err
}

const upsertRepoSession = `-- name: UpsertRepoSession :exec
insert into implementation_repo_sessions (
    implementation_id, provider, provider_session_id,
    canonical_path, session_id, first_seen_at, last_seen_at
) values (?, ?, ?, ?, ?, ?, ?)
on conflict (implementation_id, canonical_path, session_id) do update
set last_seen_at = excluded.last_seen_at
`

type UpsertRepoSessionParams struct {
	ImplementationID  string `json:"implementation_id"`
	Provider          string `json:"provider"`
	ProviderSessionID string `json:"provider_session_id"`
	CanonicalPath     string `json:"canonical_path"`
	SessionID         string `json:"session_id"`
	FirstSeenAt       int64  `json:"first_seen_at"`
	LastSeenAt        int64  `json:"last_seen_at"`
}

func (q *Queries) UpsertRepoSession(ctx context.Context, arg UpsertRepoSessionParams) error {
	_, err := q.exec(ctx, q.upsertRepoSessionStmt, upsertRepoSession,
		arg.ImplementationID,
		arg.Provider,
		arg.ProviderSessionID,
		arg.CanonicalPath,
		arg.SessionID,
		arg.FirstSeenAt,
		arg.LastSeenAt,
	)
	return err
}
